load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "generateopensearch_lib",
    srcs = ["main.go"],
    importpath = "github.com/candacelabs/csf/tools/generateopensearch",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "generateopensearch",
    embed = [":generateopensearch_lib"],
    visibility = ["//visibility:public"],
)
