// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/services/candaceos/harness (interfaces: IHost)
//
// Generated by this command:
//
//	mockgen -destination=mock_host_test.go -package=externalconsumer_test github.com/candacelabs/csf/services/candaceos/harness IHost
//

// Package externalconsumer_test is a generated GoMock package.
package externalconsumer_test

import (
	context "context"
	reflect "reflect"

	candaceosv1 "github.com/candacelabs/csf/proto/candace/candaceos/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockIHost is a mock of IHost interface.
type MockIHost struct {
	ctrl     *gomock.Controller
	recorder *MockIHostMockRecorder
	isgomock struct{}
}

// MockIHostMockRecorder is the mock recorder for MockIHost.
type MockIHostMockRecorder struct {
	mock *MockIHost
}

// NewMockIHost creates a new mock instance.
func NewMockIHost(ctrl *gomock.Controller) *MockIHost {
	mock := &MockIHost{ctrl: ctrl}
	mock.recorder = &MockIHostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHost) EXPECT() *MockIHostMockRecorder {
	return m.recorder
}

// FleetStatus mocks base method.
func (m *MockIHost) FleetStatus(ctx context.Context) (*candaceosv1.HarnessFleetStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FleetStatus", ctx)
	ret0, _ := ret[0].(*candaceosv1.HarnessFleetStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FleetStatus indicates an expected call of FleetStatus.
func (mr *MockIHostMockRecorder) FleetStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FleetStatus", reflect.TypeOf((*MockIHost)(nil).FleetStatus), ctx)
}

// Publish mocks base method.
func (m *MockIHost) Publish(ctx context.Context, event *candaceosv1.HarnessEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockIHostMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIHost)(nil).Publish), ctx, event)
}

// Reconcile mocks base method.
func (m *MockIHost) Reconcile(ctx context.Context, request *candaceosv1.HarnessReconcileRequest) (*candaceosv1.ReconcileEvidence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, request)
	ret0, _ := ret[0].(*candaceosv1.ReconcileEvidence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockIHostMockRecorder) Reconcile(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockIHost)(nil).Reconcile), ctx, request)
}
