// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mock_executor_test.go -package=agent_test
//

// Package agent_test is a generated GoMock package.
package agent_test

import (
	context "context"
	reflect "reflect"

	agent "github.com/candacelabs/csf/app/candaceos-agent/internal/agent"
	candaceosv1 "github.com/candacelabs/csf/proto/candace/candaceos/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockIExecutor is a mock of IExecutor interface.
type MockIExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockIExecutorMockRecorder
	isgomock struct{}
}

// MockIExecutorMockRecorder is the mock recorder for MockIExecutor.
type MockIExecutorMockRecorder struct {
	mock *MockIExecutor
}

// NewMockIExecutor creates a new mock instance.
func NewMockIExecutor(ctrl *gomock.Controller) *MockIExecutor {
	mock := &MockIExecutor{ctrl: ctrl}
	mock.recorder = &MockIExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExecutor) EXPECT() *MockIExecutorMockRecorder {
	return m.recorder
}

// DryRun mocks base method.
func (m *MockIExecutor) DryRun() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRun")
	ret0, _ := ret[0].(bool)
	return ret0
}

// DryRun indicates an expected call of DryRun.
func (mr *MockIExecutorMockRecorder) DryRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRun", reflect.TypeOf((*MockIExecutor)(nil).DryRun))
}

// Execute mocks base method.
func (m *MockIExecutor) Execute(ctx context.Context, plan agent.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockIExecutorMockRecorder) Execute(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIExecutor)(nil).Execute), ctx, plan)
}

// Plan mocks base method.
func (m *MockIExecutor) Plan(ctx context.Context, assignment *candaceosv1.Assignment) (agent.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plan", ctx, assignment)
	ret0, _ := ret[0].(agent.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Plan indicates an expected call of Plan.
func (mr *MockIExecutorMockRecorder) Plan(ctx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockIExecutor)(nil).Plan), ctx, assignment)
}

// Workspace mocks base method.
func (m *MockIExecutor) Workspace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Workspace")
	ret0, _ := ret[0].(string)
	return ret0
}

// Workspace indicates an expected call of Workspace.
func (mr *MockIExecutorMockRecorder) Workspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Workspace", reflect.TypeOf((*MockIExecutor)(nil).Workspace))
}

// MockIComposeProcessExecutor is a mock of IComposeProcessExecutor interface.
type MockIComposeProcessExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockIComposeProcessExecutorMockRecorder
	isgomock struct{}
}

// MockIComposeProcessExecutorMockRecorder is the mock recorder for MockIComposeProcessExecutor.
type MockIComposeProcessExecutorMockRecorder struct {
	mock *MockIComposeProcessExecutor
}

// NewMockIComposeProcessExecutor creates a new mock instance.
func NewMockIComposeProcessExecutor(ctrl *gomock.Controller) *MockIComposeProcessExecutor {
	mock := &MockIComposeProcessExecutor{ctrl: ctrl}
	mock.recorder = &MockIComposeProcessExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIComposeProcessExecutor) EXPECT() *MockIComposeProcessExecutorMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockIComposeProcessExecutor) Resolve(executable string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", executable)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIComposeProcessExecutorMockRecorder) Resolve(executable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIComposeProcessExecutor)(nil).Resolve), executable)
}

// Run mocks base method.
func (m *MockIComposeProcessExecutor) Run(ctx context.Context, invocation agent.ComposeInvocation) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, invocation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIComposeProcessExecutorMockRecorder) Run(ctx, invocation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIComposeProcessExecutor)(nil).Run), ctx, invocation)
}
