// Refinement annotations shared by Liquid Proto contracts.
//
// protoc-gen-liquidproto compiles these predicates into native Go checks and
// emits direct message validation boundaries.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: liquidproto/v1/refinement.proto

package liquidv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldRefinement attaches predicates to a singular protobuf scalar or enum,
// independently to the keys and values of a string-keyed scalar map, or an
// explicit nested-message validation call.
type FieldRefinement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Boolean expression over `this`, using comparisons, &&, ||, !, len(), and
	// matches().
	Expr string `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	// Boolean expression applied to every key in a string-keyed scalar map.
	MapKeyExpr string `protobuf:"bytes,2,opt,name=map_key_expr,json=mapKeyExpr,proto3" json:"map_key_expr,omitempty"`
	// Boolean expression applied to every value in a string-keyed scalar map.
	MapValueExpr string `protobuf:"bytes,3,opt,name=map_value_expr,json=mapValueExpr,proto3" json:"map_value_expr,omitempty"`
	// Calls the target message's generated validator when this singular message
	// field is present. It cannot be combined with expr or map predicates.
	Recurse       bool `protobuf:"varint,4,opt,name=recurse,proto3" json:"recurse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldRefinement) Reset() {
	*x = FieldRefinement{}
	mi := &file_liquidproto_v1_refinement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldRefinement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldRefinement) ProtoMessage() {}

func (x *FieldRefinement) ProtoReflect() protoreflect.Message {
	mi := &file_liquidproto_v1_refinement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldRefinement.ProtoReflect.Descriptor instead.
func (*FieldRefinement) Descriptor() ([]byte, []int) {
	return file_liquidproto_v1_refinement_proto_rawDescGZIP(), []int{0}
}

func (x *FieldRefinement) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *FieldRefinement) GetMapKeyExpr() string {
	if x != nil {
		return x.MapKeyExpr
	}
	return ""
}

func (x *FieldRefinement) GetMapValueExpr() string {
	if x != nil {
		return x.MapValueExpr
	}
	return ""
}

func (x *FieldRefinement) GetRecurse() bool {
	if x != nil {
		return x.Recurse
	}
	return false
}

var file_liquidproto_v1_refinement_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldRefinement)(nil),
		Field:         51234,
		Name:          "candace.liquid.v1.field",
		Tag:           "bytes,51234,opt,name=field",
		Filename:      "liquidproto/v1/refinement.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// 51234 is retained from the research implementation. Changing it would
	// silently reinterpret existing descriptors, so it is part of the wire
	// contract.
	//
	// optional candace.liquid.v1.FieldRefinement field = 51234;
	E_Field = &file_liquidproto_v1_refinement_proto_extTypes[0]
)

var File_liquidproto_v1_refinement_proto protoreflect.FileDescriptor

const file_liquidproto_v1_refinement_proto_rawDesc = "" +
	"\n" +
	"\x1fliquidproto/v1/refinement.proto\x12\x11candace.liquid.v1\x1a google/protobuf/descriptor.proto\"\x87\x01\n" +
	"\x0fFieldRefinement\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12 \n" +
	"\fmap_key_expr\x18\x02 \x01(\tR\n" +
	"mapKeyExpr\x12$\n" +
	"\x0emap_value_expr\x18\x03 \x01(\tR\fmapValueExpr\x12\x18\n" +
	"\arecurse\x18\x04 \x01(\bR\arecurse:Y\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xa2\x90\x03 \x01(\v2\".candace.liquid.v1.FieldRefinementR\x05fieldB8Z6github.com/candacelabs/csf/pkg/liquidproto/v1;liquidv1b\x06proto3"

var (
	file_liquidproto_v1_refinement_proto_rawDescOnce sync.Once
	file_liquidproto_v1_refinement_proto_rawDescData []byte
)

func file_liquidproto_v1_refinement_proto_rawDescGZIP() []byte {
	file_liquidproto_v1_refinement_proto_rawDescOnce.Do(func() {
		file_liquidproto_v1_refinement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liquidproto_v1_refinement_proto_rawDesc), len(file_liquidproto_v1_refinement_proto_rawDesc)))
	})
	return file_liquidproto_v1_refinement_proto_rawDescData
}

var file_liquidproto_v1_refinement_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_liquidproto_v1_refinement_proto_goTypes = []any{
	(*FieldRefinement)(nil),           // 0: candace.liquid.v1.FieldRefinement
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_liquidproto_v1_refinement_proto_depIdxs = []int32{
	1, // 0: candace.liquid.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 1: candace.liquid.v1.field:type_name -> candace.liquid.v1.FieldRefinement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_liquidproto_v1_refinement_proto_init() }
func file_liquidproto_v1_refinement_proto_init() {
	if File_liquidproto_v1_refinement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liquidproto_v1_refinement_proto_rawDesc), len(file_liquidproto_v1_refinement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_liquidproto_v1_refinement_proto_goTypes,
		DependencyIndexes: file_liquidproto_v1_refinement_proto_depIdxs,
		MessageInfos:      file_liquidproto_v1_refinement_proto_msgTypes,
		ExtensionInfos:    file_liquidproto_v1_refinement_proto_extTypes,
	}.Build()
	File_liquidproto_v1_refinement_proto = out.File
	file_liquidproto_v1_refinement_proto_goTypes = nil
	file_liquidproto_v1_refinement_proto_depIdxs = nil
}
