load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "component",
    srcs = ["component.go"],
    importpath = "github.com/candacelabs/csf/services/candaceos/component",
    visibility = ["//visibility:public"],
)

go_test(
    name = "component_test",
    srcs = [
        "component_test.go",
        "cycle_internal_test.go",
    ],
    embed = [":component"],
    deps = [
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
