// Package candacenet.warden.v1 is the Protocol-Buffers source of truth for the
// candacenet warden node-to-node wire contracts: the cluster RPCs
// (vote/heartbeat/identify), the server-streaming cluster watch, and the
// durable persistent-state record.
//
// -----------------------------------------------------------------------------
// Field-number policy (this file is the authority; numbers are the only literals
// permitted in this schema, by mandate)
// -----------------------------------------------------------------------------
//   * Numbers 1-15 encode as a single tag byte on the binary wire and are
//     reserved for the current, frequently-set ("hot") fields of every message.
//     Every message defined here fits entirely within the 1-15 band today.
//   * Field numbers are assigned in declaration order starting at 1. Declaration
//     order is also protojson's field-output order, so keeping declaration order
//     aligned with the historical Go struct order keeps the JSON rendering
//     familiar.
//   * A shipped field number is permanent: never renumber it and never reuse it
//     for a different field. Removing a field REQUIRES a `reserved <number>;` and
//     `reserved "<name>";` declaration in the same message so no later field can
//     silently reoccupy the slot or name.
//   * Growth is additive-only within a version: new fields take the next free
//     number (spilling past 15 only once the hot band is full). Any breaking
//     change (renumber, retype, delete-without-reserve, semantic reinterpretation)
//     requires a new package version directory (candacenet.warden.v2).
//   * `buf breaking` enforces this mechanically against the last committed schema.
//
// -----------------------------------------------------------------------------
// Relationship to the current JSON wire (services/warden: wire.go, types.go)
// -----------------------------------------------------------------------------
// This schema mirrors the frozen Go wire types 1:1 in field names and meaning.
// It is the source of truth for the forthcoming gRPC transport; the existing
// HTTP/JSON transport and its contract goldens are intentionally left in place
// and unchanged. Where a follow-up worker renders these messages with protojson,
// canonical protobuf-JSON differs from today's encoding/json output in ways that
// are inherent to the proto3 JSON mapping and are accepted, documented deltas:
//   * 64-bit integers (uint64 term/version/…) render as JSON *strings*
//     ("7"), not bare numbers (7). This is mandatory proto3 JSON and unavoidable.
//   * Zero-valued scalar fields are omitted by default (no EmitUnpopulated); the
//     historical encoding/json output emits them (e.g. "term":0). A DiscardUnknown
//     reader reconstructs the zero, so the semantics are identical.
//   * snake_case names are preserved ONLY when the renderer sets
//     protojson.MarshalOptions{UseProtoNames: true}; the default emits lowerCamel
//     (candidateId). No json_name overrides are used because UseProtoNames covers
//     the whole schema uniformly.
//   * timestamps render per google.protobuf.Timestamp (RFC 3339, 0/3/6/9
//     fractional digits) and are omitted entirely when unset, rather than
//     appearing as the Go zero instant "0001-01-01T00:00:00Z".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: warden/v1/warden.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH
// The brief fixes both the package (candacenet.warden.v1) and the on-disk path
// (services/warden/proto/warden/v1/warden.proto). The path omits the org
// "candacenet" segment that PACKAGE_DIRECTORY_MATCH would require, so the rule is
// intentionally waived for this package. The version-suffixed leaf (warden/v1)
// still guarantees per-version isolation.

package wardenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node is a member of the cluster peer set: a stable id plus the host:port its
// warden HTTP/RPC server listens on over the tailnet.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// addr is the "host:port" the node's warden server listens on (e.g.
	// "203.0.113.10:7717").
	Addr          string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_warden_v1_warden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// Membership is the effective voting configuration. It is persisted, changed
// ONLY by the leader one node at a time, and disseminated via heartbeats. Quorum
// is always computed over voters, never over a discovery roster or "reachable
// peers", so unreachability can never shrink the quorum denominator.
//
// Identity is the (version, created_in_term) pair, not a bare version: a leader
// that persists a new version and is deposed before disseminating it leaves a
// config sharing that version with the next leader's, and only the higher
// created_in_term wins (see the Go Membership.Supersedes contract).
type Membership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version increases by one per membership change.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// created_in_term is the term of the leader that minted this membership; it
	// disambiguates sibling configurations of equal version.
	CreatedInTerm uint64 `protobuf:"varint,2,opt,name=created_in_term,json=createdInTerm,proto3" json:"created_in_term,omitempty"`
	// voters is the full voting member set, canonically sorted by Node.id.
	Voters        []*Node `protobuf:"bytes,3,rep,name=voters,proto3" json:"voters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_warden_v1_warden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{1}
}

func (x *Membership) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Membership) GetCreatedInTerm() uint64 {
	if x != nil {
		return x.CreatedInTerm
	}
	return 0
}

func (x *Membership) GetVoters() []*Node {
	if x != nil {
		return x.Voters
	}
	return nil
}

// PeerView is one row of a ClusterView: a single peer as observed by the view's
// source node.
type PeerView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Node  *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// status is the liveness classification ("unknown"|"alive"|"suspect"|"dead"),
	// carried as a string so the exact frozen wire values survive verbatim.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// last_seen is the source's last successful contact with this peer; unset when
	// the peer has never been seen.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// latency_ms is the most recent heartbeat round-trip in milliseconds as
	// measured by the source (0 if unknown).
	LatencyMs float64 `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// member classifies membership standing ("voter"|"observer"|"discovered").
	// Empty is treated as "voter" for backward compatibility, matching the JSON
	// wire's omitempty behavior.
	Member        string `protobuf:"bytes,5,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerView) Reset() {
	*x = PeerView{}
	mi := &file_warden_v1_warden_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerView) ProtoMessage() {}

func (x *PeerView) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerView.ProtoReflect.Descriptor instead.
func (*PeerView) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{2}
}

func (x *PeerView) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *PeerView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PeerView) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *PeerView) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PeerView) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

// ClusterView is a point-in-time snapshot of the cluster as known by one node.
// The leader produces authoritative views from its own liveness tracking and
// piggybacks them on heartbeats; followers cache the most recent leader view so
// every node's dashboard shows the same state. With no fresh leader view a node
// falls back to its own observations with authoritative == false.
type ClusterView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// self is the node rendering this view.
	Self string `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	// role is self's current election role ("follower"|"candidate"|"leader"),
	// carried as a string to preserve the frozen wire values verbatim.
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// term is self's current term.
	Term uint64 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	// leader_id is the current known leader, or "" if leaderless/unknown.
	LeaderId string `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// source is the node whose observations produced peers (the leader for
	// authoritative views; self for local fallback views).
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// authoritative is true when peers reflects the current leader's liveness
	// tracking (self is the leader, or the view came from the leader within the
	// freshness window).
	Authoritative bool `protobuf:"varint,6,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	// updated_at is when source produced the peer observations.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// peers contains every cluster member including self and source, sorted by
	// Node.id.
	Peers []*PeerView `protobuf:"bytes,8,rep,name=peers,proto3" json:"peers,omitempty"`
	// elections_started counts elections self has started since boot.
	ElectionsStarted uint64 `protobuf:"varint,9,opt,name=elections_started,json=electionsStarted,proto3" json:"elections_started,omitempty"`
	// membership is the effective voting configuration this view was rendered
	// under.
	Membership    *Membership `protobuf:"bytes,10,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterView) Reset() {
	*x = ClusterView{}
	mi := &file_warden_v1_warden_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterView) ProtoMessage() {}

func (x *ClusterView) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterView.ProtoReflect.Descriptor instead.
func (*ClusterView) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterView) GetSelf() string {
	if x != nil {
		return x.Self
	}
	return ""
}

func (x *ClusterView) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ClusterView) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ClusterView) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *ClusterView) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ClusterView) GetAuthoritative() bool {
	if x != nil {
		return x.Authoritative
	}
	return false
}

func (x *ClusterView) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ClusterView) GetPeers() []*PeerView {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ClusterView) GetElectionsStarted() uint64 {
	if x != nil {
		return x.ElectionsStarted
	}
	return 0
}

func (x *ClusterView) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

// PersistentState is the durable election state (Raft current term + vote).
// Persisting the term and the vote cast in it guarantees a node can never vote
// twice in the same term across restarts, which is what makes majority quorum
// imply at most one leader per term. This is the on-disk state-file record.
type PersistentState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// current_term is the highest term this node has observed.
	CurrentTerm uint64 `protobuf:"varint,1,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	// voted_for is the candidate this node granted its vote to in current_term
	// ("" if none).
	VotedFor string `protobuf:"bytes,2,opt,name=voted_for,json=votedFor,proto3" json:"voted_for,omitempty"`
	// membership is the effective voting configuration, persisted so a restart
	// resumes with the same quorum denominator (unset in state written before
	// membership support; the config seed applies then).
	Membership    *Membership `protobuf:"bytes,3,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistentState) Reset() {
	*x = PersistentState{}
	mi := &file_warden_v1_warden_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistentState) ProtoMessage() {}

func (x *PersistentState) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistentState.ProtoReflect.Descriptor instead.
func (*PersistentState) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{4}
}

func (x *PersistentState) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *PersistentState) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

func (x *PersistentState) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

// VoteRequest asks a peer for its vote in candidate_id's election for term.
type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_warden_v1_warden_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{5}
}

func (x *VoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

// VoteResponse replies to a VoteRequest. term is the voter's current term after
// processing the request (a candidate seeing a higher term must step down).
type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Granted       bool                   `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	VoterId       string                 `protobuf:"bytes,3,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_warden_v1_warden_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{6}
}

func (x *VoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *VoteResponse) GetVoterId() string {
	if x != nil {
		return x.VoterId
	}
	return ""
}

// HeartbeatRequest is sent by the leader to every peer at the heartbeat
// interval. It asserts leadership for term and optionally carries the leader's
// authoritative view and effective membership.
type HeartbeatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Term     uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// view is the leader's current authoritative cluster view; unset means "no
	// view conveyed" (followers keep their previous cached view).
	View *ClusterView `protobuf:"bytes,3,opt,name=view,proto3" json:"view,omitempty"`
	// membership is the leader's effective voting configuration; unset means "no
	// change conveyed". Receivers with a lower local (version, created_in_term)
	// persist-then-adopt it, only from the leader they currently accept.
	Membership    *Membership `protobuf:"bytes,4,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_warden_v1_warden_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HeartbeatRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *HeartbeatRequest) GetView() *ClusterView {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *HeartbeatRequest) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

// HeartbeatResponse acknowledges a heartbeat. ok is false when the receiver
// rejects the sender as leader (stale term); term then tells the stale leader
// the newer term so it can step down.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_warden_v1_warden_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// IdentifyRequest is the request for the cluster-identity handshake. It is
// intentionally empty today but declared as its own message (rather than
// google.protobuf.Empty) so the handshake can grow request fields compatibly.
type IdentifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	mi := &file_warden_v1_warden_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyRequest.ProtoReflect.Descriptor instead.
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{9}
}

// IdentifyResponse answers the Identify handshake. A caller treats a node as a
// same-cluster warden only when cluster_id matches its local configuration.
type IdentifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	mi := &file_warden_v1_warden_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyResponse.ProtoReflect.Descriptor instead.
func (*IdentifyResponse) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{10}
}

func (x *IdentifyResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *IdentifyResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *IdentifyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ClusterViewCursor is the dedup/resume key for the cluster watch. It is the
// (membership.version, membership.created_in_term, view.updated_at) triple
// derived from a ClusterView. Two updates carrying an equal cursor represent the
// same observable cluster state; a client that has already applied a cursor may
// skip a repeat, and may present a known cursor when (re)opening a watch to
// suppress a redundant initial snapshot.
type ClusterViewCursor struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MembershipVersion       uint64                 `protobuf:"varint,1,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	MembershipCreatedInTerm uint64                 `protobuf:"varint,2,opt,name=membership_created_in_term,json=membershipCreatedInTerm,proto3" json:"membership_created_in_term,omitempty"`
	ViewUpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=view_updated_at,json=viewUpdatedAt,proto3" json:"view_updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ClusterViewCursor) Reset() {
	*x = ClusterViewCursor{}
	mi := &file_warden_v1_warden_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterViewCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterViewCursor) ProtoMessage() {}

func (x *ClusterViewCursor) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterViewCursor.ProtoReflect.Descriptor instead.
func (*ClusterViewCursor) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{11}
}

func (x *ClusterViewCursor) GetMembershipVersion() uint64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

func (x *ClusterViewCursor) GetMembershipCreatedInTerm() uint64 {
	if x != nil {
		return x.MembershipCreatedInTerm
	}
	return 0
}

func (x *ClusterViewCursor) GetViewUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ViewUpdatedAt
	}
	return nil
}

// WatchClusterRequest opens a server-streaming cluster watch.
type WatchClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// since is an optional resume cursor. When set, the server SHOULD suppress the
	// initial snapshot if its current state matches `since`, emitting only
	// subsequent changes. When unset, the server emits the current snapshot first,
	// then one update per change.
	Since         *ClusterViewCursor `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchClusterRequest) Reset() {
	*x = WatchClusterRequest{}
	mi := &file_warden_v1_warden_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchClusterRequest) ProtoMessage() {}

func (x *WatchClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchClusterRequest.ProtoReflect.Descriptor instead.
func (*WatchClusterRequest) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{12}
}

func (x *WatchClusterRequest) GetSince() *ClusterViewCursor {
	if x != nil {
		return x.Since
	}
	return nil
}

// ClusterViewUpdate is one element of the WatchCluster stream. Updates are
// FULL SNAPSHOTS, never diffs: each carries the complete current ClusterView.
// This keeps the protocol stateless and self-healing — a client that drops or
// reconnects re-syncs from the next update with no replay bookkeeping.
//
// Ordering and dedup: updates are keyed by `cursor`, the
// (membership.version, membership.created_in_term, view.updated_at) triple.
// The server emits an update whenever any keyed component advances (a membership
// change bumps version/created_in_term; a fresh view bumps view.updated_at).
// Consumers dedup and order by cursor rather than by stream arrival.
type ClusterViewUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// view is the complete current cluster snapshot.
	View *ClusterView `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	// cursor is the dedup/resume key derived from view.
	Cursor        *ClusterViewCursor `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterViewUpdate) Reset() {
	*x = ClusterViewUpdate{}
	mi := &file_warden_v1_warden_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterViewUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterViewUpdate) ProtoMessage() {}

func (x *ClusterViewUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterViewUpdate.ProtoReflect.Descriptor instead.
func (*ClusterViewUpdate) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{13}
}

func (x *ClusterViewUpdate) GetView() *ClusterView {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *ClusterViewUpdate) GetCursor() *ClusterViewCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

var File_warden_v1_warden_proto protoreflect.FileDescriptor

const file_warden_v1_warden_proto_rawDesc = "" +
	"\n" +
	"\x16warden/v1/warden.proto\x12\x14candacenet.warden.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\x82\x01\n" +
	"\n" +
	"Membership\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12&\n" +
	"\x0fcreated_in_term\x18\x02 \x01(\x04R\rcreatedInTerm\x122\n" +
	"\x06voters\x18\x03 \x03(\v2\x1a.candacenet.warden.v1.NodeR\x06voters\"\xc2\x01\n" +
	"\bPeerView\x12.\n" +
	"\x04node\x18\x01 \x01(\v2\x1a.candacenet.warden.v1.NodeR\x04node\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\x12\x16\n" +
	"\x06member\x18\x05 \x01(\tR\x06member\"\x84\x03\n" +
	"\vClusterView\x12\x12\n" +
	"\x04self\x18\x01 \x01(\tR\x04self\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\tR\bleaderId\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12$\n" +
	"\rauthoritative\x18\x06 \x01(\bR\rauthoritative\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x124\n" +
	"\x05peers\x18\b \x03(\v2\x1e.candacenet.warden.v1.PeerViewR\x05peers\x12+\n" +
	"\x11elections_started\x18\t \x01(\x04R\x10electionsStarted\x12@\n" +
	"\n" +
	"membership\x18\n" +
	" \x01(\v2 .candacenet.warden.v1.MembershipR\n" +
	"membership\"\x93\x01\n" +
	"\x0fPersistentState\x12!\n" +
	"\fcurrent_term\x18\x01 \x01(\x04R\vcurrentTerm\x12\x1b\n" +
	"\tvoted_for\x18\x02 \x01(\tR\bvotedFor\x12@\n" +
	"\n" +
	"membership\x18\x03 \x01(\v2 .candacenet.warden.v1.MembershipR\n" +
	"membership\"D\n" +
	"\vVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\"W\n" +
	"\fVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\x12\x19\n" +
	"\bvoter_id\x18\x03 \x01(\tR\avoterId\"\xbc\x01\n" +
	"\x10HeartbeatRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x125\n" +
	"\x04view\x18\x03 \x01(\v2!.candacenet.warden.v1.ClusterViewR\x04view\x12@\n" +
	"\n" +
	"membership\x18\x04 \x01(\v2 .candacenet.warden.v1.MembershipR\n" +
	"membership\"P\n" +
	"\x11HeartbeatResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"\x11\n" +
	"\x0fIdentifyRequest\"d\n" +
	"\x10IdentifyResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xc3\x01\n" +
	"\x11ClusterViewCursor\x12-\n" +
	"\x12membership_version\x18\x01 \x01(\x04R\x11membershipVersion\x12;\n" +
	"\x1amembership_created_in_term\x18\x02 \x01(\x04R\x17membershipCreatedInTerm\x12B\n" +
	"\x0fview_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rviewUpdatedAt\"T\n" +
	"\x13WatchClusterRequest\x12=\n" +
	"\x05since\x18\x01 \x01(\v2'.candacenet.warden.v1.ClusterViewCursorR\x05since\"\x8b\x01\n" +
	"\x11ClusterViewUpdate\x125\n" +
	"\x04view\x18\x01 \x01(\v2!.candacenet.warden.v1.ClusterViewR\x04view\x12?\n" +
	"\x06cursor\x18\x02 \x01(\v2'.candacenet.warden.v1.ClusterViewCursorR\x06cursor2\xfd\x02\n" +
	"\rWardenService\x12M\n" +
	"\x04Vote\x12!.candacenet.warden.v1.VoteRequest\x1a\".candacenet.warden.v1.VoteResponse\x12\\\n" +
	"\tHeartbeat\x12&.candacenet.warden.v1.HeartbeatRequest\x1a'.candacenet.warden.v1.HeartbeatResponse\x12Y\n" +
	"\bIdentify\x12%.candacenet.warden.v1.IdentifyRequest\x1a&.candacenet.warden.v1.IdentifyResponse\x12d\n" +
	"\fWatchCluster\x12).candacenet.warden.v1.WatchClusterRequest\x1a'.candacenet.warden.v1.ClusterViewUpdate0\x01BEZCgithub.com/candacelabs/csf/services/warden/proto/warden/v1;wardenv1b\x06proto3"

var (
	file_warden_v1_warden_proto_rawDescOnce sync.Once
	file_warden_v1_warden_proto_rawDescData []byte
)

func file_warden_v1_warden_proto_rawDescGZIP() []byte {
	file_warden_v1_warden_proto_rawDescOnce.Do(func() {
		file_warden_v1_warden_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warden_v1_warden_proto_rawDesc), len(file_warden_v1_warden_proto_rawDesc)))
	})
	return file_warden_v1_warden_proto_rawDescData
}

var file_warden_v1_warden_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_warden_v1_warden_proto_goTypes = []any{
	(*Node)(nil),                  // 0: candacenet.warden.v1.Node
	(*Membership)(nil),            // 1: candacenet.warden.v1.Membership
	(*PeerView)(nil),              // 2: candacenet.warden.v1.PeerView
	(*ClusterView)(nil),           // 3: candacenet.warden.v1.ClusterView
	(*PersistentState)(nil),       // 4: candacenet.warden.v1.PersistentState
	(*VoteRequest)(nil),           // 5: candacenet.warden.v1.VoteRequest
	(*VoteResponse)(nil),          // 6: candacenet.warden.v1.VoteResponse
	(*HeartbeatRequest)(nil),      // 7: candacenet.warden.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 8: candacenet.warden.v1.HeartbeatResponse
	(*IdentifyRequest)(nil),       // 9: candacenet.warden.v1.IdentifyRequest
	(*IdentifyResponse)(nil),      // 10: candacenet.warden.v1.IdentifyResponse
	(*ClusterViewCursor)(nil),     // 11: candacenet.warden.v1.ClusterViewCursor
	(*WatchClusterRequest)(nil),   // 12: candacenet.warden.v1.WatchClusterRequest
	(*ClusterViewUpdate)(nil),     // 13: candacenet.warden.v1.ClusterViewUpdate
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_warden_v1_warden_proto_depIdxs = []int32{
	0,  // 0: candacenet.warden.v1.Membership.voters:type_name -> candacenet.warden.v1.Node
	0,  // 1: candacenet.warden.v1.PeerView.node:type_name -> candacenet.warden.v1.Node
	14, // 2: candacenet.warden.v1.PeerView.last_seen:type_name -> google.protobuf.Timestamp
	14, // 3: candacenet.warden.v1.ClusterView.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: candacenet.warden.v1.ClusterView.peers:type_name -> candacenet.warden.v1.PeerView
	1,  // 5: candacenet.warden.v1.ClusterView.membership:type_name -> candacenet.warden.v1.Membership
	1,  // 6: candacenet.warden.v1.PersistentState.membership:type_name -> candacenet.warden.v1.Membership
	3,  // 7: candacenet.warden.v1.HeartbeatRequest.view:type_name -> candacenet.warden.v1.ClusterView
	1,  // 8: candacenet.warden.v1.HeartbeatRequest.membership:type_name -> candacenet.warden.v1.Membership
	14, // 9: candacenet.warden.v1.ClusterViewCursor.view_updated_at:type_name -> google.protobuf.Timestamp
	11, // 10: candacenet.warden.v1.WatchClusterRequest.since:type_name -> candacenet.warden.v1.ClusterViewCursor
	3,  // 11: candacenet.warden.v1.ClusterViewUpdate.view:type_name -> candacenet.warden.v1.ClusterView
	11, // 12: candacenet.warden.v1.ClusterViewUpdate.cursor:type_name -> candacenet.warden.v1.ClusterViewCursor
	5,  // 13: candacenet.warden.v1.WardenService.Vote:input_type -> candacenet.warden.v1.VoteRequest
	7,  // 14: candacenet.warden.v1.WardenService.Heartbeat:input_type -> candacenet.warden.v1.HeartbeatRequest
	9,  // 15: candacenet.warden.v1.WardenService.Identify:input_type -> candacenet.warden.v1.IdentifyRequest
	12, // 16: candacenet.warden.v1.WardenService.WatchCluster:input_type -> candacenet.warden.v1.WatchClusterRequest
	6,  // 17: candacenet.warden.v1.WardenService.Vote:output_type -> candacenet.warden.v1.VoteResponse
	8,  // 18: candacenet.warden.v1.WardenService.Heartbeat:output_type -> candacenet.warden.v1.HeartbeatResponse
	10, // 19: candacenet.warden.v1.WardenService.Identify:output_type -> candacenet.warden.v1.IdentifyResponse
	13, // 20: candacenet.warden.v1.WardenService.WatchCluster:output_type -> candacenet.warden.v1.ClusterViewUpdate
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_warden_v1_warden_proto_init() }
func file_warden_v1_warden_proto_init() {
	if File_warden_v1_warden_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warden_v1_warden_proto_rawDesc), len(file_warden_v1_warden_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warden_v1_warden_proto_goTypes,
		DependencyIndexes: file_warden_v1_warden_proto_depIdxs,
		MessageInfos:      file_warden_v1_warden_proto_msgTypes,
	}.Build()
	File_warden_v1_warden_proto = out.File
	file_warden_v1_warden_proto_goTypes = nil
	file_warden_v1_warden_proto_depIdxs = nil
}
