load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "chaossrv_lib",
    srcs = ["main.go"],
    importpath = "github.com/candacelabs/csf/pkg/gotth/test/internal/chaos/cmd/chaossrv",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/gotth/live",
        "@com_github_a_h_templ//:templ",
    ],
)

go_binary(
    name = "chaossrv",
    embed = [":chaossrv_lib"],
    visibility = ["//pkg/gotth/test:__subpackages__"],
)
