// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CandaceosActivityReceipt struct {
	ReceiptID     int64              `json:"receipt_id"`
	EntityType    string             `json:"entity_type"`
	EntityID      string             `json:"entity_id"`
	Kind          string             `json:"kind"`
	Summary       string             `json:"summary"`
	PayloadSha256 pgtype.Text        `json:"payload_sha256"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type CandaceosAppRevision struct {
	AppRevisionID    string             `json:"app_revision_id"`
	AppName          string             `json:"app_name"`
	SourceRepository string             `json:"source_repository"`
	SourceRevision   string             `json:"source_revision"`
	SourceSha256     string             `json:"source_sha256"`
	ComposeFile      string             `json:"compose_file"`
	ImageDigest      pgtype.Text        `json:"image_digest"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CandaceosDeployment struct {
	DeploymentID  string             `json:"deployment_id"`
	AppRevisionID string             `json:"app_revision_id"`
	ProjectName   string             `json:"project_name"`
	WorkspacePath string             `json:"workspace_path"`
	DesiredState  string             `json:"desired_state"`
	PlacementMode string             `json:"placement_mode"`
	ExactNodeID   pgtype.Text        `json:"exact_node_id"`
	Replicas      int32              `json:"replicas"`
	Stateful      bool               `json:"stateful"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CandaceosDeploymentLabel struct {
	DeploymentID string `json:"deployment_id"`
	LabelKey     string `json:"label_key"`
	LabelValue   string `json:"label_value"`
}

type CandaceosDeploymentRollout struct {
	RolloutID     string             `json:"rollout_id"`
	DeploymentID  string             `json:"deployment_id"`
	AppRevisionID string             `json:"app_revision_id"`
	DesiredState  string             `json:"desired_state"`
	RequestedAt   pgtype.Timestamptz `json:"requested_at"`
}

type CandaceosDeploymentRun struct {
	RunID         string             `json:"run_id"`
	DeploymentID  string             `json:"deployment_id"`
	AppRevisionID string             `json:"app_revision_id"`
	NodeID        string             `json:"node_id"`
	WardenTerm    int64              `json:"warden_term"`
	LeaderID      string             `json:"leader_id"`
	Status        string             `json:"status"`
	DryRun        pgtype.Bool        `json:"dry_run"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	RequestedAt   pgtype.Timestamptz `json:"requested_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	RolloutID     string             `json:"rollout_id"`
	DesiredState  string             `json:"desired_state"`
}

type CandaceosNode struct {
	NodeID     string             `json:"node_id"`
	Address    string             `json:"address"`
	Role       string             `json:"role"`
	Status     string             `json:"status"`
	WardenTerm int64              `json:"warden_term"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

type CandaceosNodeLabel struct {
	NodeID     string `json:"node_id"`
	LabelKey   string `json:"label_key"`
	LabelValue string `json:"label_value"`
}

type CandaceosOperatorApproval struct {
	ApprovalID    string             `json:"approval_id"`
	RunID         pgtype.Text        `json:"run_id"`
	ToolCallID    pgtype.Text        `json:"tool_call_id"`
	RequestKind   string             `json:"request_kind"`
	Title         string             `json:"title"`
	Detail        string             `json:"detail"`
	Risk          string             `json:"risk"`
	PayloadSha256 string             `json:"payload_sha256"`
	Status        string             `json:"status"`
	RequestedAt   pgtype.Timestamptz `json:"requested_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy    pgtype.Text        `json:"resolved_by"`
}

type CandaceosOperatorRun struct {
	RunID      string             `json:"run_id"`
	SessionID  string             `json:"session_id"`
	Title      string             `json:"title"`
	Prompt     string             `json:"prompt"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type CandaceosPossiblyActiveDeploymentNode struct {
	DeploymentID string `json:"deployment_id"`
	NodeID       string `json:"node_id"`
}

type CandaceosSchemaMigration struct {
	Version   int32              `json:"version"`
	Name      string             `json:"name"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}
