// Code generated by pkg/widget/internal/uigen from the NodeStatus widget document. DO NOT EDIT.

// Package nodestatus is the generated NodeStatus widget.
//
// Edit the widget document and regenerate; edits here are overwritten.
package nodestatus

import (
	"context"
	"strconv"

	"github.com/a-h/templ"

	"github.com/candacelabs/csf/pkg/gotth/live"
	"github.com/candacelabs/csf/pkg/widget"
)

// This widget's identity. The region is the only one that crosses the wire: a
// patch names it, so changing it is a client-visible change. The palette is a
// name a host resolves to values; this widget carries no colour of its own.
// The title id is what the widget's landmark is labelled by.
const (
	NodeStatusName    = "NodeStatus"
	NodeStatusRegion  = "widget.node-status"
	NodeStatusPalette = "fieldStation"
	NodeStatusTitleID = "widget.node-status-title"
)

// The wire names this widget accepts. The set is exhaustive and default-deny:
// a name absent from the registration is refused before any reducer runs.
const (
	NodeStatusEventHealth = "widget.node-status.health"
)

// The wire field names each event carries. They are the other half of an
// event's contract: the widget reads these out of a delivery, and whatever
// produced the delivery wrote them in. Registration.Payloads carries the same
// names as data, for a host that fills an event it cannot name at compile time.
const (
	NodeStatusEventHealthFieldReachable = "reachable"
)

// NodeStatusState is this widget's own state, and the type argument every
// method below is written in. The host holds it without knowing it; nothing
// in this file asserts it back, because nothing in this file ever loses it.
type NodeStatusState struct {
	// Reachable is the "reachable" state field, declared type flag.
	Reachable bool
}

// NodeStatus is the generated NodeStatus widget.
//
// I is the HOST's identity type, threaded through and never read: a widget
// document names no host, no address and no credential, so nothing here can
// look at an identity. It is a type parameter because the SDK's contract
// carries one — live.Session stopped erasing the application's identity type
// on 2026-09-03 — and a generated widget must fit whatever host registers it.
type NodeStatus[I live.IIdentity] struct {
	region string
}

// NewNodeStatus returns the widget a host registers, instantiated on that
// host's own identity type.
func NewNodeStatus[I live.IIdentity]() *NodeStatus[I] { return NewNodeStatusAt[I](NodeStatusRegion) }

// NewNodeStatusAt gives one instance its host-assigned region. The host validates
// region syntax and uniqueness when assembling its live configuration.
func NewNodeStatusAt[I live.IIdentity](region string) *NodeStatus[I] {
	return &NodeStatus[I]{region: region}
}

// The contract, asserted at one instantiation. Anonymous is the identity a
// host with no accounts uses, and any other I satisfies the same interfaces:
// nothing below branches on it.
var (
	_ widget.IWidget[NodeStatusState, live.AnonymousIdentity] = (*NodeStatus[live.AnonymousIdentity])(nil)
	_ widget.IDirtyDeclarer[NodeStatusState]                  = (*NodeStatus[live.AnonymousIdentity])(nil)
)

// Register declares this instance's definition and assigned region.
//
// Events are the names a browser may send; Internal are the names only a
// declared stream delivers, which the host routes without registering.
func (instance *NodeStatus[I]) Register() widget.Registration {
	return widget.Registration{
		Name:     NodeStatusName,
		Region:   instance.region,
		Internal: []string{NodeStatusEventHealth},
		Streams: []widget.StreamDeclaration{
			{Name: "healthWatch", Source: "widget.node-status.watch", Delivers: NodeStatusEventHealth},
		},
		Payloads: []widget.EventPayload{
			{Event: NodeStatusEventHealth, Fields: []string{
				NodeStatusEventHealthFieldReachable,
			}},
		},
	}
}

// Mount opens one session's copy of the widget. It schedules no effect: the
// streams this widget declared are the host's to open, because a widget document
// names no host, no address and no credential.
func (instance *NodeStatus[I]) Mount(
	ctx context.Context, session live.Session[I],
) (NodeStatusState, []live.Effect[I], error) {
	return NodeStatusState{}, nil, nil
}

// Reduce is the pure transition from one state to the next. It performs no I/O,
// reads no clock and mutates nothing it was given.
func (instance *NodeStatus[I]) Reduce(
	state NodeStatusState, event live.Event,
) (NodeStatusState, []live.Effect[I]) {
	current := state
	switch event.Name {
	case NodeStatusEventHealth:
		if raw, present := event.Fields.Lookup(NodeStatusEventHealthFieldReachable); present {
			current.Reachable = widget.ParseFlag(raw, current.Reachable)
		}
	}
	return current, nil
}

// Render draws the widget's live region. It is a pure function of state:
// equal state renders byte-identical markup.
func (instance *NodeStatus[I]) Render(state NodeStatusState) templ.Component {
	return NodeStatusViewAt(state, instance.region)
}

// Dirty reports whether a transition may have changed this widget's markup: the
// state fields its bindings, its predicates and its tick read, and no others.
func (instance *NodeStatus[I]) Dirty(previous NodeStatusState, next NodeStatusState) bool {
	return previous.Reachable != next.Reachable
}

// Unmount releases what the session held. This widget holds nothing.
func (instance *NodeStatus[I]) Unmount(ctx context.Context, session live.Session[I], state NodeStatusState) {
}

// Snapshot projects state into ordered name/value pairs, in state-field
// declaration order.
func (instance *NodeStatus[I]) Snapshot(state NodeStatusState) widget.Snapshot {
	return widget.Snapshot{
		Widget: NodeStatusName,
		Fields: []widget.SnapshotField{
			{Name: "reachable", Value: strconv.FormatBool(state.Reachable)},
		},
	}
}

// StatusText is the "statusText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state NodeStatusState) StatusText() string {
	if state.Reachable {
		return "reachable"
	}
	return "unreachable"
}

// SceneDescriptionText is the "sceneDescriptionText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state NodeStatusState) SceneDescriptionText() string {
	if state.Reachable {
		return "One node; its health check is passing."
	}
	return "One node; its health check is failing."
}

// TitleLabel is the "titleLabel" label.
func (state NodeStatusState) TitleLabel() string {
	return "Node status"
}

// SceneDescriptionLabel is the "sceneDescriptionLabel" label.
func (state NodeStatusState) SceneDescriptionLabel() string {
	return state.SceneDescriptionText()
}

// NodeALabel is the "nodeALabel" label.
func (state NodeStatusState) NodeALabel() string {
	return "node-a"
}

// StatusLabel is the "statusLabel" label.
func (state NodeStatusState) StatusLabel() string {
	return state.StatusText()
}
