load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fleet",
    srcs = [
        "client.go",
        "configured.go",
    ],
    importpath = "github.com/candacelabs/csf/services/candaceos/fleet",
    visibility = ["//visibility:public"],
)

go_test(
    name = "fleet_test",
    srcs = ["client_test.go"],
    deps = [
        ":fleet",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
