load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "clusterheartbeats",
    srcs = [
        "view_templ.go",
        "widget.gen.go",
    ],
    importpath = "github.com/candacelabs/csf/examples/widget/clusterheartbeats",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/gotth/live",
        "//pkg/widget",
        "@com_github_a_h_templ//:templ",
        "@com_github_a_h_templ//runtime",
    ],
)
