// Liquid Proto contract for the Copilot CLI adapter's tunables.
//
// Every number the adapter reads at runtime is DECLARED here and its bounds
// are compiled into a generated Validate function; the Go struct, its
// defaults and its validation are projections of this file. Nothing in the
// adapter's Go source declares a tunable literal (operator ruling of
// 2026-09-04, PR #165: configs are derived from a declaration, not defined in
// source).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: candace/copilot/v1/adapter.proto

package copilotv1

import (
	_ "github.com/candacelabs/csf/pkg/liquidproto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdapterConfig is the whole tunable surface of the adapter. It is supplied
// through the WithConfig functional option; the option's zero argument means
// "the declared defaults", which DefaultAdapterConfig builds.
type AdapterConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Milliseconds the session-event stream waits between store polls. Small
	// enough that a browser sees a lifecycle event promptly, large enough that
	// one open EventSource is not a busy loop against PostgreSQL.
	EventStreamPollMillis int64 `protobuf:"varint,1,opt,name=event_stream_poll_millis,json=eventStreamPollMillis,proto3" json:"event_stream_poll_millis,omitempty"`
	// Rows one stream poll may drain from session_events at a time. Bounds the
	// memory of a replay after a long disconnect.
	EventStreamPageSize uint32 `protobuf:"varint,2,opt,name=event_stream_page_size,json=eventStreamPageSize,proto3" json:"event_stream_page_size,omitempty"`
	// Page size a list endpoint uses when the caller names none. The contract's
	// own maximum bounds the upper end.
	DefaultPageLimit uint32 `protobuf:"varint,3,opt,name=default_page_limit,json=defaultPageLimit,proto3" json:"default_page_limit,omitempty"`
	// Milliseconds allowed for a process-owned durability transition after an
	// external SDK call has returned. It is independent of the HTTP request,
	// which may already have been canceled by a disconnected browser.
	DurableTransitionTimeoutMillis int64 `protobuf:"varint,4,opt,name=durable_transition_timeout_millis,json=durableTransitionTimeoutMillis,proto3" json:"durable_transition_timeout_millis,omitempty"`
	// Number of exited terminal snapshots/output buffers retained for reconnect
	// and inspection. Running terminals are never evicted.
	TerminalHistoryLimit uint32 `protobuf:"varint,5,opt,name=terminal_history_limit,json=terminalHistoryLimit,proto3" json:"terminal_history_limit,omitempty"`
	// Maximum UTF-8 bytes written into one durable assistantDelta event from
	// correlated, conforming projector input. The OpenAPI text limit is also
	// 65536 code points, so this byte bound is stricter for non-ASCII text.
	AssistantDeltaMaxBytes uint32 `protobuf:"varint,6,opt,name=assistant_delta_max_bytes,json=assistantDeltaMaxBytes,proto3" json:"assistant_delta_max_bytes,omitempty"`
	// Milliseconds a correlated, conforming in-memory same-turn projector batch
	// may wait for a boundary before atomic projection. A hard crash can lose
	// this live-preview window; the completed transcript remains canonical.
	AssistantDeltaFlushMillis int64 `protobuf:"varint,7,opt,name=assistant_delta_flush_millis,json=assistantDeltaFlushMillis,proto3" json:"assistant_delta_flush_millis,omitempty"`
	// Correlated, conforming source receipts retained in one projector batch.
	// This bounds projector memory even when a source emits empty deltas.
	AssistantDeltaMaxEvents uint32 `protobuf:"varint,8,opt,name=assistant_delta_max_events,json=assistantDeltaMaxEvents,proto3" json:"assistant_delta_max_events,omitempty"`
	// Maximum UTF-8 bytes accepted from one correlated, conforming projector
	// source delta. Larger preview input is rejected; the completed assistant
	// message remains authoritative. With assistant_delta_max_bytes this bounds
	// one accepted source to at most 64 inserts.
	AssistantDeltaSourceMaxBytes uint32 `protobuf:"varint,9,opt,name=assistant_delta_source_max_bytes,json=assistantDeltaSourceMaxBytes,proto3" json:"assistant_delta_source_max_bytes,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AdapterConfig) Reset() {
	*x = AdapterConfig{}
	mi := &file_candace_copilot_v1_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterConfig) ProtoMessage() {}

func (x *AdapterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_candace_copilot_v1_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterConfig.ProtoReflect.Descriptor instead.
func (*AdapterConfig) Descriptor() ([]byte, []int) {
	return file_candace_copilot_v1_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *AdapterConfig) GetEventStreamPollMillis() int64 {
	if x != nil {
		return x.EventStreamPollMillis
	}
	return 0
}

func (x *AdapterConfig) GetEventStreamPageSize() uint32 {
	if x != nil {
		return x.EventStreamPageSize
	}
	return 0
}

func (x *AdapterConfig) GetDefaultPageLimit() uint32 {
	if x != nil {
		return x.DefaultPageLimit
	}
	return 0
}

func (x *AdapterConfig) GetDurableTransitionTimeoutMillis() int64 {
	if x != nil {
		return x.DurableTransitionTimeoutMillis
	}
	return 0
}

func (x *AdapterConfig) GetTerminalHistoryLimit() uint32 {
	if x != nil {
		return x.TerminalHistoryLimit
	}
	return 0
}

func (x *AdapterConfig) GetAssistantDeltaMaxBytes() uint32 {
	if x != nil {
		return x.AssistantDeltaMaxBytes
	}
	return 0
}

func (x *AdapterConfig) GetAssistantDeltaFlushMillis() int64 {
	if x != nil {
		return x.AssistantDeltaFlushMillis
	}
	return 0
}

func (x *AdapterConfig) GetAssistantDeltaMaxEvents() uint32 {
	if x != nil {
		return x.AssistantDeltaMaxEvents
	}
	return 0
}

func (x *AdapterConfig) GetAssistantDeltaSourceMaxBytes() uint32 {
	if x != nil {
		return x.AssistantDeltaSourceMaxBytes
	}
	return 0
}

// TraceExportConfig configures one bounded OTLP delivery goroutine in the caller's
// process. Credentials are private deployment inputs, never observation data.
type TraceExportConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EndpointUrl          string                 `protobuf:"bytes,1,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	PublicKey            string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	SecretKey            string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	PollMillis           int64                  `protobuf:"varint,4,opt,name=poll_millis,json=pollMillis,proto3" json:"poll_millis,omitempty"`
	RequestTimeoutMillis int64                  `protobuf:"varint,5,opt,name=request_timeout_millis,json=requestTimeoutMillis,proto3" json:"request_timeout_millis,omitempty"`
	LeaseSeconds         int32                  `protobuf:"varint,6,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	MaxAttempts          int32                  `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	MaxRequestBytes      int64                  `protobuf:"varint,8,opt,name=max_request_bytes,json=maxRequestBytes,proto3" json:"max_request_bytes,omitempty"`
	WorkbenchUrl         string                 `protobuf:"bytes,9,opt,name=workbench_url,json=workbenchUrl,proto3" json:"workbench_url,omitempty"`
	RetryBaseSeconds     int32                  `protobuf:"varint,10,opt,name=retry_base_seconds,json=retryBaseSeconds,proto3" json:"retry_base_seconds,omitempty"`
	RetryMaxSeconds      int32                  `protobuf:"varint,11,opt,name=retry_max_seconds,json=retryMaxSeconds,proto3" json:"retry_max_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TraceExportConfig) Reset() {
	*x = TraceExportConfig{}
	mi := &file_candace_copilot_v1_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceExportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceExportConfig) ProtoMessage() {}

func (x *TraceExportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_candace_copilot_v1_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceExportConfig.ProtoReflect.Descriptor instead.
func (*TraceExportConfig) Descriptor() ([]byte, []int) {
	return file_candace_copilot_v1_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *TraceExportConfig) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *TraceExportConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *TraceExportConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *TraceExportConfig) GetPollMillis() int64 {
	if x != nil {
		return x.PollMillis
	}
	return 0
}

func (x *TraceExportConfig) GetRequestTimeoutMillis() int64 {
	if x != nil {
		return x.RequestTimeoutMillis
	}
	return 0
}

func (x *TraceExportConfig) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *TraceExportConfig) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *TraceExportConfig) GetMaxRequestBytes() int64 {
	if x != nil {
		return x.MaxRequestBytes
	}
	return 0
}

func (x *TraceExportConfig) GetWorkbenchUrl() string {
	if x != nil {
		return x.WorkbenchUrl
	}
	return ""
}

func (x *TraceExportConfig) GetRetryBaseSeconds() int32 {
	if x != nil {
		return x.RetryBaseSeconds
	}
	return 0
}

func (x *TraceExportConfig) GetRetryMaxSeconds() int32 {
	if x != nil {
		return x.RetryMaxSeconds
	}
	return 0
}

var File_candace_copilot_v1_adapter_proto protoreflect.FileDescriptor

const file_candace_copilot_v1_adapter_proto_rawDesc = "" +
	"\n" +
	" candace/copilot/v1/adapter.proto\x12\x12candace.copilot.v1\x1a\x1fliquidproto/v1/refinement.proto\"\xe3\x06\n" +
	"\rAdapterConfig\x12Z\n" +
	"\x18event_stream_poll_millis\x18\x01 \x01(\x03B!\x92\x82\x19\x1d\n" +
	"\x1bthis >= 10 && this <= 60000R\x15eventStreamPollMillis\x12T\n" +
	"\x16event_stream_page_size\x18\x02 \x01(\rB\x1f\x92\x82\x19\x1b\n" +
	"\x19this >= 1 && this <= 5000R\x13eventStreamPageSize\x12L\n" +
	"\x12default_page_limit\x18\x03 \x01(\rB\x1e\x92\x82\x19\x1a\n" +
	"\x18this >= 1 && this <= 200R\x10defaultPageLimit\x12n\n" +
	"!durable_transition_timeout_millis\x18\x04 \x01(\x03B#\x92\x82\x19\x1f\n" +
	"\x1dthis >= 100 && this <= 120000R\x1edurableTransitionTimeoutMillis\x12U\n" +
	"\x16terminal_history_limit\x18\x05 \x01(\rB\x1f\x92\x82\x19\x1b\n" +
	"\x19this >= 1 && this <= 1000R\x14terminalHistoryLimit\x12^\n" +
	"\x19assistant_delta_max_bytes\x18\x06 \x01(\rB#\x92\x82\x19\x1f\n" +
	"\x1dthis >= 1024 && this <= 65536R\x16assistantDeltaMaxBytes\x12`\n" +
	"\x1cassistant_delta_flush_millis\x18\a \x01(\x03B\x1f\x92\x82\x19\x1b\n" +
	"\x19this >= 1 && this <= 1000R\x19assistantDeltaFlushMillis\x12\\\n" +
	"\x1aassistant_delta_max_events\x18\b \x01(\rB\x1f\x92\x82\x19\x1b\n" +
	"\x19this >= 1 && this <= 1024R\x17assistantDeltaMaxEvents\x12k\n" +
	" assistant_delta_source_max_bytes\x18\t \x01(\rB#\x92\x82\x19\x1f\n" +
	"\x1dthis >= 1024 && this <= 65536R\x1cassistantDeltaSourceMaxBytes\"\xe4\x05\n" +
	"\x11TraceExportConfig\x123\n" +
	"\fendpoint_url\x18\x01 \x01(\tB\x10\x92\x82\x19\f\n" +
	"\n" +
	"this != \"\"R\vendpointUrl\x12/\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\x10\x92\x82\x19\f\n" +
	"\n" +
	"this != \"\"R\tpublicKey\x12/\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tB\x10\x92\x82\x19\f\n" +
	"\n" +
	"this != \"\"R\tsecretKey\x12C\n" +
	"\vpoll_millis\x18\x04 \x01(\x03B\"\x92\x82\x19\x1e\n" +
	"\x1cthis >= 100 && this <= 60000R\n" +
	"pollMillis\x12X\n" +
	"\x16request_timeout_millis\x18\x05 \x01(\x03B\"\x92\x82\x19\x1e\n" +
	"\x1cthis >= 100 && this <= 30000R\x14requestTimeoutMillis\x12D\n" +
	"\rlease_seconds\x18\x06 \x01(\x05B\x1f\x92\x82\x19\x1b\n" +
	"\x19this >= 35 && this <= 300R\fleaseSeconds\x12@\n" +
	"\fmax_attempts\x18\a \x01(\x05B\x1d\x92\x82\x19\x19\n" +
	"\x17this >= 1 && this <= 20R\vmaxAttempts\x12Q\n" +
	"\x11max_request_bytes\x18\b \x01(\x03B%\x92\x82\x19!\n" +
	"\x1fthis >= 4096 && this <= 4194304R\x0fmaxRequestBytes\x12#\n" +
	"\rworkbench_url\x18\t \x01(\tR\fworkbenchUrl\x12K\n" +
	"\x12retry_base_seconds\x18\n" +
	" \x01(\x05B\x1d\x92\x82\x19\x19\n" +
	"\x17this >= 1 && this <= 60R\x10retryBaseSeconds\x12L\n" +
	"\x11retry_max_seconds\x18\v \x01(\x05B \x92\x82\x19\x1c\n" +
	"\x1athis >= 60 && this <= 3600R\x0fretryMaxSecondsBXZVgithub.com/candacelabs/csf/services/copilot-adapter/proto/candace/copilot/v1;copilotv1b\x06proto3"

var (
	file_candace_copilot_v1_adapter_proto_rawDescOnce sync.Once
	file_candace_copilot_v1_adapter_proto_rawDescData []byte
)

func file_candace_copilot_v1_adapter_proto_rawDescGZIP() []byte {
	file_candace_copilot_v1_adapter_proto_rawDescOnce.Do(func() {
		file_candace_copilot_v1_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_candace_copilot_v1_adapter_proto_rawDesc), len(file_candace_copilot_v1_adapter_proto_rawDesc)))
	})
	return file_candace_copilot_v1_adapter_proto_rawDescData
}

var file_candace_copilot_v1_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_candace_copilot_v1_adapter_proto_goTypes = []any{
	(*AdapterConfig)(nil),     // 0: candace.copilot.v1.AdapterConfig
	(*TraceExportConfig)(nil), // 1: candace.copilot.v1.TraceExportConfig
}
var file_candace_copilot_v1_adapter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_candace_copilot_v1_adapter_proto_init() }
func file_candace_copilot_v1_adapter_proto_init() {
	if File_candace_copilot_v1_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_candace_copilot_v1_adapter_proto_rawDesc), len(file_candace_copilot_v1_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_candace_copilot_v1_adapter_proto_goTypes,
		DependencyIndexes: file_candace_copilot_v1_adapter_proto_depIdxs,
		MessageInfos:      file_candace_copilot_v1_adapter_proto_msgTypes,
	}.Build()
	File_candace_copilot_v1_adapter_proto = out.File
	file_candace_copilot_v1_adapter_proto_goTypes = nil
	file_candace_copilot_v1_adapter_proto_depIdxs = nil
}
