// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: candace/copilot/v1/adapter.proto

package copilotv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/csf/pkg/liquidproto"
)

// ValidateAdapterConfig checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateAdapterConfig(message *AdapterConfig) error {
	if message == nil {
		return fmt.Errorf("ValidateAdapterConfig: nil *AdapterConfig")
	}
	if !(message.EventStreamPollMillis >= 10 && message.EventStreamPollMillis <= 60000) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "event_stream_poll_millis",
			Predicate: "this >= 10 && this <= 60000",
			Value:     message.EventStreamPollMillis,
		}
	}
	if !(message.EventStreamPageSize >= 1 && message.EventStreamPageSize <= 5000) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "event_stream_page_size",
			Predicate: "this >= 1 && this <= 5000",
			Value:     message.EventStreamPageSize,
		}
	}
	if !(message.DefaultPageLimit >= 1 && message.DefaultPageLimit <= 200) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "default_page_limit",
			Predicate: "this >= 1 && this <= 200",
			Value:     message.DefaultPageLimit,
		}
	}
	if !(message.DurableTransitionTimeoutMillis >= 100 && message.DurableTransitionTimeoutMillis <= 120000) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "durable_transition_timeout_millis",
			Predicate: "this >= 100 && this <= 120000",
			Value:     message.DurableTransitionTimeoutMillis,
		}
	}
	if !(message.TerminalHistoryLimit >= 1 && message.TerminalHistoryLimit <= 1000) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "terminal_history_limit",
			Predicate: "this >= 1 && this <= 1000",
			Value:     message.TerminalHistoryLimit,
		}
	}
	if !(message.AssistantDeltaMaxBytes >= 1024 && message.AssistantDeltaMaxBytes <= 65536) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "assistant_delta_max_bytes",
			Predicate: "this >= 1024 && this <= 65536",
			Value:     message.AssistantDeltaMaxBytes,
		}
	}
	if !(message.AssistantDeltaFlushMillis >= 1 && message.AssistantDeltaFlushMillis <= 1000) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "assistant_delta_flush_millis",
			Predicate: "this >= 1 && this <= 1000",
			Value:     message.AssistantDeltaFlushMillis,
		}
	}
	if !(message.AssistantDeltaMaxEvents >= 1 && message.AssistantDeltaMaxEvents <= 1024) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "assistant_delta_max_events",
			Predicate: "this >= 1 && this <= 1024",
			Value:     message.AssistantDeltaMaxEvents,
		}
	}
	if !(message.AssistantDeltaSourceMaxBytes >= 1024 && message.AssistantDeltaSourceMaxBytes <= 65536) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.AdapterConfig",
			Field:     "assistant_delta_source_max_bytes",
			Predicate: "this >= 1024 && this <= 65536",
			Value:     message.AssistantDeltaSourceMaxBytes,
		}
	}
	return nil
}

// ValidateTraceExportConfig checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateTraceExportConfig(message *TraceExportConfig) error {
	if message == nil {
		return fmt.Errorf("ValidateTraceExportConfig: nil *TraceExportConfig")
	}
	if !(message.EndpointUrl != "") {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "endpoint_url",
			Predicate: "this != \"\"",
			Value:     message.EndpointUrl,
		}
	}
	if !(message.PublicKey != "") {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "public_key",
			Predicate: "this != \"\"",
			Value:     message.PublicKey,
		}
	}
	if !(message.SecretKey != "") {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "secret_key",
			Predicate: "this != \"\"",
			Value:     message.SecretKey,
		}
	}
	if !(message.PollMillis >= 100 && message.PollMillis <= 60000) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "poll_millis",
			Predicate: "this >= 100 && this <= 60000",
			Value:     message.PollMillis,
		}
	}
	if !(message.RequestTimeoutMillis >= 100 && message.RequestTimeoutMillis <= 30000) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "request_timeout_millis",
			Predicate: "this >= 100 && this <= 30000",
			Value:     message.RequestTimeoutMillis,
		}
	}
	if !(message.LeaseSeconds >= 35 && message.LeaseSeconds <= 300) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "lease_seconds",
			Predicate: "this >= 35 && this <= 300",
			Value:     message.LeaseSeconds,
		}
	}
	if !(message.MaxAttempts >= 1 && message.MaxAttempts <= 20) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "max_attempts",
			Predicate: "this >= 1 && this <= 20",
			Value:     message.MaxAttempts,
		}
	}
	if !(message.MaxRequestBytes >= 4096 && message.MaxRequestBytes <= 4194304) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "max_request_bytes",
			Predicate: "this >= 4096 && this <= 4194304",
			Value:     message.MaxRequestBytes,
		}
	}
	if !(message.RetryBaseSeconds >= 1 && message.RetryBaseSeconds <= 60) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "retry_base_seconds",
			Predicate: "this >= 1 && this <= 60",
			Value:     message.RetryBaseSeconds,
		}
	}
	if !(message.RetryMaxSeconds >= 60 && message.RetryMaxSeconds <= 3600) {
		return &liquidproto.Error{
			Message:   "candace.copilot.v1.TraceExportConfig",
			Field:     "retry_max_seconds",
			Predicate: "this >= 60 && this <= 3600",
			Value:     message.RetryMaxSeconds,
		}
	}
	return nil
}
