load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "copilot",
    srcs = [
        "adapter.pb.go",
        "adapter_liquid.pb.go",
    ],
    importpath = "github.com/candacelabs/csf/services/copilot-adapter/proto/candace/copilot/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/liquidproto",
        "//pkg/liquidproto/v1:liquidproto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
