// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package copilotbridge

import (
	api "github.com/candacelabs/csf/services/copilot-adapter/gen/api"
	rpc "github.com/github/copilot-sdk/go/rpc"
)

type iUsageConverterImpl struct{}

func (c *iUsageConverterImpl) Checkpoint(source rpc.SessionUsageCheckpointData) api.UsageObservation {
	var apiUsageObservation api.UsageObservation
	pFloat64 := source.TotalNanoAiu
	apiUsageObservation.NanoAiu = &pFloat64
	if source.TotalPremiumRequests != nil {
		xfloat64 := *source.TotalPremiumRequests
		apiUsageObservation.PremiumRequests = &xfloat64
	}
	return apiUsageObservation
}
func (c *iUsageConverterImpl) ModelCall(source rpc.AssistantUsageData) api.UsageObservation {
	var apiUsageObservation api.UsageObservation
	if source.APICallID != nil {
		xstring := *source.APICallID
		apiUsageObservation.ApiCallId = &xstring
	}
	if source.Duration != nil {
		xint64 := *source.Duration
		apiUsageObservation.ApiDurationMs = &xint64
	}
	if source.Cost != nil {
		xfloat64 := *source.Cost
		apiUsageObservation.BillingMultiplier = &xfloat64
	}
	if source.CacheReadTokens != nil {
		xint642 := *source.CacheReadTokens
		apiUsageObservation.CacheReadTokens = &xint642
	}
	if source.CacheWriteTokens != nil {
		xint643 := *source.CacheWriteTokens
		apiUsageObservation.CacheWriteTokens = &xint643
	}
	if source.InputTokens != nil {
		xint644 := *source.InputTokens
		apiUsageObservation.InputTokens = &xint644
	}
	pString := source.Model
	apiUsageObservation.Model = &pString
	if source.OutputTokens != nil {
		xint645 := *source.OutputTokens
		apiUsageObservation.OutputTokens = &xint645
	}
	if source.ProviderCallID != nil {
		xstring2 := *source.ProviderCallID
		apiUsageObservation.ProviderCallId = &xstring2
	}
	if source.ReasoningTokens != nil {
		xint646 := *source.ReasoningTokens
		apiUsageObservation.ReasoningTokens = &xint646
	}
	if source.ServiceRequestID != nil {
		xstring3 := *source.ServiceRequestID
		apiUsageObservation.ServiceRequestId = &xstring3
	}
	return apiUsageObservation
}
func (c *iUsageConverterImpl) Shutdown(source rpc.SessionShutdownData) api.UsageObservation {
	var apiUsageObservation api.UsageObservation
	if source.TotalNanoAiu != nil {
		xfloat64 := *source.TotalNanoAiu
		apiUsageObservation.NanoAiu = &xfloat64
	}
	if source.TotalPremiumRequests != nil {
		xfloat642 := *source.TotalPremiumRequests
		apiUsageObservation.PremiumRequests = &xfloat642
	}
	return apiUsageObservation
}
