// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package copilotadapter

import (
	"database/sql"
	api "github.com/candacelabs/csf/services/copilot-adapter/gen/api"
	storedb "github.com/candacelabs/csf/services/copilot-adapter/storedb"
	uuid "github.com/google/uuid"
	v5 "github.com/guregu/null/v5"
)

type iViewConverterImpl struct{}

func (c *iViewConverterImpl) Session(source storedb.Session) api.Session {
	var apiSession api.Session
	apiSession.CreatedAt = utcTimePointer(source.CreatedAt)
	apiSession.DisplayName = source.DisplayName
	apiSession.FailureCode = api.FailureCode(source.FailureCode)
	if source.FailureReason.Ptr() != nil {
		xstring := *source.FailureReason.Ptr()
		apiSession.FailureReason = &xstring
	}
	apiSession.Id = c.uuidUUIDToPUuidUUID(source.ID)
	apiSession.LastTurnAt = nullTimePointer(source.LastTurnAt)
	apiSession.Model = source.Model
	apiSession.Permissions = permissionPolicyMode(source.PermissionMode)
	apiSession.Status = api.SessionStatus(source.Status)
	apiSession.UpdatedAt = utcTimePointer(source.UpdatedAt)
	apiSession.WorkingDirectory = source.WorkingDirectory
	apiSession.WorktreeId = c.uuidUUIDToPUuidUUID(source.WorktreeID)
	return apiSession
}
func (c *iViewConverterImpl) SessionEventVersion(source storedb.SessionEventVersion) api.Session {
	var apiSession api.Session
	apiSession.CreatedAt = utcTimePointer(source.CreatedAt)
	apiSession.DisplayName = source.DisplayName
	apiSession.FailureCode = api.FailureCode(source.FailureCode)
	if source.FailureReason.Ptr() != nil {
		xstring := *source.FailureReason.Ptr()
		apiSession.FailureReason = &xstring
	}
	apiSession.Id = c.uuidUUIDToPUuidUUID(source.ID)
	apiSession.LastTurnAt = nullTimePointer(source.LastTurnAt)
	apiSession.Model = source.Model
	apiSession.Permissions = permissionPolicyMode(source.PermissionMode)
	apiSession.Status = api.SessionStatus(source.Status)
	pInt64 := source.TurnCount
	apiSession.TurnCount = &pInt64
	apiSession.UpdatedAt = utcTimePointer(source.UpdatedAt)
	apiSession.WorkingDirectory = source.WorkingDirectory
	apiSession.WorktreeId = c.uuidUUIDToPUuidUUID(source.WorktreeID)
	return apiSession
}
func (c *iViewConverterImpl) SessionRequest(source storedb.PendingRequest) api.SessionRequest {
	var apiSessionRequest api.SessionRequest
	apiSessionRequest.CreatedAt = utcTimePointer(source.CreatedAt)
	apiSessionRequest.Id = c.uuidUUIDToPUuidUUID(source.ID)
	apiSessionRequest.Kind = api.SessionRequestKind(source.Kind)
	apiSessionRequest.Prompt = source.Prompt
	apiSessionRequest.ResolvedAt = nullTimePointer(source.ResolvedAt)
	apiSessionRequest.SessionId = c.uuidUUIDToPUuidUUID(source.SessionID)
	apiSessionRequest.Status = api.SessionRequestStatus(source.Status)
	if source.ToolName.Ptr() != nil {
		xstring := *source.ToolName.Ptr()
		apiSessionRequest.ToolName = &xstring
	}
	apiSessionRequest.TurnId = c.pUuidUUIDToPUuidUUID(source.TurnID)
	return apiSessionRequest
}
func (c *iViewConverterImpl) SessionRequestEventVersion(source storedb.RequestEventVersion) api.SessionRequest {
	var apiSessionRequest api.SessionRequest
	apiSessionRequest.CreatedAt = utcTimePointer(source.CreatedAt)
	apiSessionRequest.Id = c.uuidUUIDToPUuidUUID(source.ID)
	apiSessionRequest.Kind = api.SessionRequestKind(source.Kind)
	apiSessionRequest.Prompt = source.Prompt
	apiSessionRequest.ResolvedAt = nullTimePointer(source.ResolvedAt)
	apiSessionRequest.SessionId = c.uuidUUIDToPUuidUUID(source.SessionID)
	apiSessionRequest.Status = api.SessionRequestStatus(source.Status)
	if source.ToolName.Ptr() != nil {
		xstring := *source.ToolName.Ptr()
		apiSessionRequest.ToolName = &xstring
	}
	apiSessionRequest.TurnId = c.pUuidUUIDToPUuidUUID(source.TurnID)
	return apiSessionRequest
}
func (c *iViewConverterImpl) SessionTelemetry(source storedb.ListSessionTelemetryRow) api.SessionTelemetry {
	var apiSessionTelemetry api.SessionTelemetry
	if source.ApiDurationMs.Ptr() != nil {
		xint64 := *source.ApiDurationMs.Ptr()
		apiSessionTelemetry.ApiDurationMs = &xint64
	}
	if source.CacheReadTokens.Ptr() != nil {
		xint642 := *source.CacheReadTokens.Ptr()
		apiSessionTelemetry.CacheReadTokens = &xint642
	}
	if source.CacheWriteTokens.Ptr() != nil {
		xint643 := *source.CacheWriteTokens.Ptr()
		apiSessionTelemetry.CacheWriteTokens = &xint643
	}
	apiSessionTelemetry.CreatedAt = utcTime(source.CreatedAt)
	apiSessionTelemetry.DisplayName = source.DisplayName
	apiSessionTelemetry.DurationKnownTurnCount = source.DurationKnownTurnCount
	if source.DurationSeconds.Ptr() != nil {
		xfloat64 := *source.DurationSeconds.Ptr()
		apiSessionTelemetry.DurationSeconds = &xfloat64
	}
	if source.InputTokens.Ptr() != nil {
		xint644 := *source.InputTokens.Ptr()
		apiSessionTelemetry.InputTokens = &xint644
	}
	apiSessionTelemetry.KnownCompletedTurnCount = source.KnownCompletedTurnCount
	apiSessionTelemetry.KnownStartedTurnCount = source.KnownStartedTurnCount
	apiSessionTelemetry.LatestCompletedAt = nullTimePointer(source.LatestTurnCompletedAt)
	apiSessionTelemetry.LatestStartedAt = nullTimePointer(source.LatestTurnStartedAt)
	apiSessionTelemetry.LatestTurnId = c.pUuidUUIDToPUuidUUID(source.LatestTurnID)
	if source.LatestTurnStatus.Ptr() != nil {
		xstring := *source.LatestTurnStatus.Ptr()
		apiSessionTelemetry.LatestTurnStatus = &xstring
	}
	apiSessionTelemetry.LatestUsageAt = nullTimePointer(source.LatestUsageAt)
	apiSessionTelemetry.Model = source.Model
	apiSessionTelemetry.ObservedModelCallCount = source.ObservedModelCallCount
	if source.OutputTokens.Ptr() != nil {
		xint645 := *source.OutputTokens.Ptr()
		apiSessionTelemetry.OutputTokens = &xint645
	}
	if source.PremiumRequests.Ptr() != nil {
		xfloat642 := *source.PremiumRequests.Ptr()
		apiSessionTelemetry.PremiumRequests = &xfloat642
	}
	if source.ReasoningTokens.Ptr() != nil {
		xint646 := *source.ReasoningTokens.Ptr()
		apiSessionTelemetry.ReasoningTokens = &xint646
	}
	apiSessionTelemetry.SessionId = c.uuidUUIDToUuidUUID(source.SessionID)
	apiSessionTelemetry.Status = source.Status
	apiSessionTelemetry.TurnCount = source.TurnCount
	apiSessionTelemetry.UncorrelatedUsageCount = source.UncorrelatedUsageCount
	apiSessionTelemetry.UpdatedAt = utcTime(source.UpdatedAt)
	return apiSessionTelemetry
}
func (c *iViewConverterImpl) SubagentEventVersion(source storedb.SubagentEventVersion) api.Subagent {
	var apiSubagent api.Subagent
	pInt64 := source.ActivityCount
	apiSubagent.ActivityCount = &pInt64
	apiSubagent.CompletedAt = nullTimePointer(source.CompletedAt)
	pString := source.DisplayName
	apiSubagent.DisplayName = &pString
	pString2 := source.ID
	apiSubagent.Id = &pString2
	apiSubagent.SessionId = c.uuidUUIDToPUuidUUID(source.SessionID)
	apiSubagent.StartedAt = utcTimePointer(source.StartedAt)
	apiSubagent.Status = api.SubagentStatus(source.Status)
	if source.Summary.Ptr() != nil {
		xstring := *source.Summary.Ptr()
		apiSubagent.Summary = &xstring
	}
	apiSubagent.TurnId = c.pUuidUUIDToPUuidUUID(source.TurnID)
	apiSubagent.UpdatedAt = utcTimePointer(source.UpdatedAt)
	return apiSubagent
}
func (c *iViewConverterImpl) TraceCount(source storedb.CountTraceDeliveriesRow) api.TraceDeliveryCount {
	var apiTraceDeliveryCount api.TraceDeliveryCount
	apiTraceDeliveryCount.Count = source.Count
	apiTraceDeliveryCount.State = api.TraceDeliveryCountState(source.Status)
	return apiTraceDeliveryCount
}
func (c *iViewConverterImpl) TraceDelivery(source storedb.ClaimTraceDeliveryRow) storedb.TraceDelivery {
	var storedbTraceDelivery storedb.TraceDelivery
	storedbTraceDelivery.DeliveryID = source.DeliveryID
	storedbTraceDelivery.SessionID = c.uuidUUIDToUuidUUID(source.SessionID)
	storedbTraceDelivery.TurnID = c.pUuidUUIDToPUuidUUID(source.TurnID)
	storedbTraceDelivery.UsageEventID = c.nullStringToNullString(source.UsageEventID)
	storedbTraceDelivery.Status = source.Status
	storedbTraceDelivery.Attempts = source.Attempts
	storedbTraceDelivery.Generation = source.Generation
	storedbTraceDelivery.LeaseUntil = c.nullTimeToNullTime(source.LeaseUntil)
	storedbTraceDelivery.NextAttemptAt = utcTime(source.NextAttemptAt)
	storedbTraceDelivery.LastError = source.LastError
	storedbTraceDelivery.AcceptedAt = c.nullTimeToNullTime(source.AcceptedAt)
	return storedbTraceDelivery
}
func (c *iViewConverterImpl) TranscriptItem(source storedb.TranscriptItem) api.TranscriptItem {
	var apiTranscriptItem api.TranscriptItem
	if source.Author.Ptr() != nil {
		xstring := *source.Author.Ptr()
		apiTranscriptItem.Author = &xstring
	}
	apiTranscriptItem.Kind = api.TranscriptItemKind(source.Kind)
	apiTranscriptItem.OccurredAt = utcTimePointer(source.OccurredAt)
	pInt64 := source.Seq
	apiTranscriptItem.Seq = &pInt64
	apiTranscriptItem.SessionId = c.uuidUUIDToPUuidUUID(source.SessionID)
	apiTranscriptItem.Text = source.Body
	if source.ToolCallID.Ptr() != nil {
		xstring2 := *source.ToolCallID.Ptr()
		apiTranscriptItem.ToolCallId = &xstring2
	}
	if source.ToolName.Ptr() != nil {
		xstring3 := *source.ToolName.Ptr()
		apiTranscriptItem.ToolName = &xstring3
	}
	apiTranscriptItem.TurnId = c.pUuidUUIDToPUuidUUID(source.TurnID)
	return apiTranscriptItem
}
func (c *iViewConverterImpl) Turn(source storedb.Turn) api.Turn {
	var apiTurn api.Turn
	apiTurn.CompletedAt = nullTimePointer(source.CompletedAt)
	apiTurn.CreatedAt = utcTimePointer(source.CreatedAt)
	apiTurn.Id = c.uuidUUIDToPUuidUUID(source.ID)
	apiTurn.SessionId = c.uuidUUIDToPUuidUUID(source.SessionID)
	apiTurn.StartedAt = nullTimePointer(source.StartedAt)
	apiTurn.Status = api.TurnStatus(source.Status)
	return apiTurn
}
func (c *iViewConverterImpl) TurnEventVersion(source storedb.TurnEventVersion) api.Turn {
	var apiTurn api.Turn
	apiTurn.CompletedAt = nullTimePointer(source.CompletedAt)
	apiTurn.CreatedAt = utcTimePointer(source.CreatedAt)
	apiTurn.Id = c.uuidUUIDToPUuidUUID(source.ID)
	apiTurn.SessionId = c.uuidUUIDToPUuidUUID(source.SessionID)
	apiTurn.StartedAt = nullTimePointer(source.StartedAt)
	apiTurn.Status = api.TurnStatus(source.Status)
	return apiTurn
}
func (c *iViewConverterImpl) UsageInsert(source api.UsageObservation) storedb.InsertProviderUsageEventParams {
	var storedbInsertProviderUsageEventParams storedb.InsertProviderUsageEventParams
	storedbInsertProviderUsageEventParams.Kind = string(source.Kind)
	storedbInsertProviderUsageEventParams.Model = v5.StringFromPtr(source.Model)
	storedbInsertProviderUsageEventParams.ApiCallID = v5.StringFromPtr(source.ApiCallId)
	storedbInsertProviderUsageEventParams.ProviderCallID = v5.StringFromPtr(source.ProviderCallId)
	storedbInsertProviderUsageEventParams.ServiceRequestID = v5.StringFromPtr(source.ServiceRequestId)
	storedbInsertProviderUsageEventParams.InputTokens = v5.IntFromPtr(source.InputTokens)
	storedbInsertProviderUsageEventParams.OutputTokens = v5.IntFromPtr(source.OutputTokens)
	storedbInsertProviderUsageEventParams.CacheReadTokens = v5.IntFromPtr(source.CacheReadTokens)
	storedbInsertProviderUsageEventParams.CacheWriteTokens = v5.IntFromPtr(source.CacheWriteTokens)
	storedbInsertProviderUsageEventParams.ReasoningTokens = v5.IntFromPtr(source.ReasoningTokens)
	storedbInsertProviderUsageEventParams.ApiDurationMs = v5.IntFromPtr(source.ApiDurationMs)
	storedbInsertProviderUsageEventParams.BillingMultiplier = v5.FloatFromPtr(source.BillingMultiplier)
	storedbInsertProviderUsageEventParams.PremiumRequests = v5.FloatFromPtr(source.PremiumRequests)
	storedbInsertProviderUsageEventParams.NanoAiu = v5.FloatFromPtr(source.NanoAiu)
	return storedbInsertProviderUsageEventParams
}
func (c *iViewConverterImpl) WorkspaceTaskLink(source storedb.SessionTask) api.WorkspaceTaskLink {
	var apiWorkspaceTaskLink api.WorkspaceTaskLink
	apiWorkspaceTaskLink.Generation = source.Generation
	apiWorkspaceTaskLink.SessionId = c.uuidUUIDToUuidUUID(source.SessionID)
	apiWorkspaceTaskLink.TaskUrl = source.TaskUrl
	return apiWorkspaceTaskLink
}
func (c *iViewConverterImpl) WorkspaceWorktree(source storedb.Worktree) api.WorkspaceWorktree {
	var apiWorkspaceWorktree api.WorkspaceWorktree
	apiWorkspaceWorktree.BaseRef = source.BaseRef
	apiWorkspaceWorktree.Id = c.uuidUUIDToUuidUUID(source.ID)
	apiWorkspaceWorktree.Managed = source.Managed
	apiWorkspaceWorktree.Path = source.Path
	apiWorkspaceWorktree.RepositoryId = source.RepositoryID
	return apiWorkspaceWorktree
}
func (c *iViewConverterImpl) nullStringToNullString(source v5.String) v5.String {
	var nullString v5.String
	nullString.NullString = c.sqlNullStringToSqlNullString(source.NullString)
	return nullString
}
func (c *iViewConverterImpl) nullTimeToNullTime(source v5.Time) v5.Time {
	var nullTime v5.Time
	nullTime.NullTime = c.sqlNullTimeToSqlNullTime(source.NullTime)
	return nullTime
}
func (c *iViewConverterImpl) pUuidUUIDToPUuidUUID(source *uuid.UUID) *uuid.UUID {
	var pUuidUUID *uuid.UUID
	if source != nil {
		uuidUUID := c.uuidUUIDToUuidUUID((*source))
		pUuidUUID = &uuidUUID
	}
	return pUuidUUID
}
func (c *iViewConverterImpl) sqlNullStringToSqlNullString(source sql.NullString) sql.NullString {
	var sqlNullString sql.NullString
	sqlNullString.String = source.String
	sqlNullString.Valid = source.Valid
	return sqlNullString
}
func (c *iViewConverterImpl) sqlNullTimeToSqlNullTime(source sql.NullTime) sql.NullTime {
	var sqlNullTime sql.NullTime
	sqlNullTime.Time = utcTime(source.Time)
	sqlNullTime.Valid = source.Valid
	return sqlNullTime
}
func (c *iViewConverterImpl) uuidUUIDToPUuidUUID(source uuid.UUID) *uuid.UUID {
	uuidUUID := c.uuidUUIDToUuidUUID(source)
	return &uuidUUID
}
func (c *iViewConverterImpl) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
