/*
 * §6's statistics. Percentiles, bootstrap confidence intervals, and the
 * instability rule — implemented once so every dimension reports the same way.
 *
 * §6: "Report per-run p50 alongside the pooled p50/p95/p99. Percentiles, never
 * means, for latency (FR-73). Bootstrap 95 % confidence intervals (10 000
 * resamples) on the pooled p50 and p99. A difference whose CIs overlap is
 * reported as 'no measured difference', not as a win. Instability rule: if the
 * spread of per-run p50s exceeds 20 % of the pooled p50, the cell is marked
 * unstable, the whole cell is re-collected (not selectively), and the unstable
 * set is still published."
 *
 * The "no measured difference" rule is the one that matters most and is the
 * easiest to skip. compare() below returns that verdict as a value, not as a
 * suggestion, so a report generator cannot render a win out of overlapping
 * intervals without deliberately ignoring the field.
 */

/** Nearest-rank percentile. No interpolation: a percentile of a latency
 *  distribution should be a value that was actually observed. */
export function percentile(sorted, p) {
  if (sorted.length === 0) return null;
  const rank = Math.ceil((p / 100) * sorted.length);
  return sorted[Math.min(sorted.length - 1, Math.max(0, rank - 1))];
}

export function summarize(values) {
  const sorted = [...values].sort((a, b) => a - b);
  return {
    n: sorted.length,
    min: sorted[0] ?? null,
    p50: percentile(sorted, 50),
    p95: percentile(sorted, 95),
    p99: percentile(sorted, 99),
    max: sorted[sorted.length - 1] ?? null,
  };
}

/**
 * A deterministic PRNG for the bootstrap.
 *
 * Math.random() would make the published confidence interval unreproducible,
 * and FR-75 says a number that cannot be regenerated by the documented command
 * does not appear in the report. The seed is recorded with the result.
 */
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x9e3779b9) >>> 0;
    let z = s;
    z = Math.imul(z ^ (z >>> 16), 0x21f0aaad) >>> 0;
    z = Math.imul(z ^ (z >>> 15), 0x735a2d97) >>> 0;
    return ((z ^ (z >>> 15)) >>> 0) / 4294967296;
  };
}

/** §6: bootstrap 95 % CI, 10 000 resamples, on the pooled p50 and p99. */
export function bootstrapCI(values, p, { resamples = 10_000, seed = 0x5eed } = {}) {
  if (values.length === 0) return { lo: null, hi: null, resamples, seed };
  const next = rng(seed);
  const stats = new Array(resamples);
  const n = values.length;
  for (let r = 0; r < resamples; r++) {
    const sample = new Array(n);
    for (let i = 0; i < n; i++) sample[i] = values[Math.floor(next() * n)];
    sample.sort((a, b) => a - b);
    stats[r] = percentile(sample, p);
  }
  stats.sort((a, b) => a - b);
  return {
    lo: percentile(stats, 2.5),
    hi: percentile(stats, 97.5),
    resamples,
    seed,
  };
}

/**
 * §6's instability rule.
 *
 * "spread of per-run p50s exceeds 20 % of the pooled p50" — spread is taken as
 * max minus min across the five runs, which is the reading that flags a single
 * bad run. A standard deviation would let one outlier hide behind four good
 * runs, and one bad run in a cell is exactly the condition the rule exists to
 * surface.
 */
export function instability(perRunP50s, pooledP50) {
  if (perRunP50s.length === 0 || !pooledP50) return { unstable: false, spread: 0, ratio: 0 };
  const spread = Math.max(...perRunP50s) - Math.min(...perRunP50s);
  const ratio = spread / pooledP50;
  return { unstable: ratio > 0.2, spread, ratio, threshold: 0.2 };
}

/** One cell: every run's samples, pooled and per-run, with the §6 verdicts. */
export function cell(runs, { seed = 0x5eed } = {}) {
  const pooled = runs.flat();
  const summary = summarize(pooled);
  const perRunP50 = runs.map((values) => summarize(values).p50).filter((v) => v !== null);
  return {
    ...summary,
    perRunP50,
    ci: {
      p50: bootstrapCI(pooled, 50, { seed }),
      p99: bootstrapCI(pooled, 99, { seed }),
    },
    stability: instability(perRunP50, summary.p50),
    runs: runs.length,
  };
}

/**
 * §6's prominence-adjacent rule, made mechanical: overlapping CIs are NOT a
 * win.
 *
 * "A difference whose CIs overlap is reported as 'no measured difference', not
 * as a win." The verdict string is what a report renders; there is no numeric
 * "how much better" for an overlapping pair, deliberately, because that number
 * is what a reader would quote.
 */
export function compare(a, b, { labelA = 'A', labelB = 'B', p = 50 } = {}) {
  const ca = p === 50 ? a.ci.p50 : a.ci.p99;
  const cb = p === 50 ? b.ci.p50 : b.ci.p99;
  if (ca.lo === null || cb.lo === null) return { verdict: 'not measured' };

  const overlap = ca.lo <= cb.hi && cb.lo <= ca.hi;
  if (overlap) {
    return { verdict: 'no measured difference', a: ca, b: cb, p };
  }
  const winner = ca.hi < cb.lo ? labelA : labelB;
  return {
    verdict: `${winner} lower`,
    winner,
    a: ca,
    b: cb,
    p,
    ratio: p === 50 ? b.p50 / a.p50 : b.p99 / a.p99,
  };
}
