// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=internal/mocks/http.gen.go -package=csfmocks
//

// Package csfmocks is a generated GoMock package.
package csfmocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIHTTPDoer is a mock of IHTTPDoer interface.
type MockIHTTPDoer struct {
	ctrl     *gomock.Controller
	recorder *MockIHTTPDoerMockRecorder
	isgomock struct{}
}

// MockIHTTPDoerMockRecorder is the mock recorder for MockIHTTPDoer.
type MockIHTTPDoerMockRecorder struct {
	mock *MockIHTTPDoer
}

// NewMockIHTTPDoer creates a new mock instance.
func NewMockIHTTPDoer(ctrl *gomock.Controller) *MockIHTTPDoer {
	mock := &MockIHTTPDoer{ctrl: ctrl}
	mock.recorder = &MockIHTTPDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHTTPDoer) EXPECT() *MockIHTTPDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockIHTTPDoer) Do(request *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", request)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockIHTTPDoerMockRecorder) Do(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockIHTTPDoer)(nil).Do), request)
}
