// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: candace/candaceos/v1/webui.proto

package candaceosv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/csf/pkg/liquidproto"
	regexp "regexp"
)

var (
	_liquidWebUIClawMessageRequestExpectedRunIdRe0 = regexp.MustCompile("^[A-Za-z0-9][A-Za-z0-9._:-]*$")
)

// ValidateWebUIPromptRequest checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateWebUIPromptRequest(message *WebUIPromptRequest) error {
	if message == nil {
		return fmt.Errorf("ValidateWebUIPromptRequest: nil *WebUIPromptRequest")
	}
	if !(len(message.Prompt) >= 1 && len(message.Prompt) <= 12000) {
		return &liquidproto.Error{
			Message:   "candace.candaceos.v1.WebUIPromptRequest",
			Field:     "prompt",
			Predicate: "len(this) >= 1 && len(this) <= 12000",
			Value:     message.Prompt,
		}
	}
	return nil
}

// ValidateWebUIClawMessageRequest checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateWebUIClawMessageRequest(message *WebUIClawMessageRequest) error {
	if message == nil {
		return fmt.Errorf("ValidateWebUIClawMessageRequest: nil *WebUIClawMessageRequest")
	}
	if !(len(message.Prompt) >= 1 && len(message.Prompt) <= 12000) {
		return &liquidproto.Error{
			Message:   "candace.candaceos.v1.WebUIClawMessageRequest",
			Field:     "prompt",
			Predicate: "len(this) >= 1 && len(this) <= 12000",
			Value:     message.Prompt,
		}
	}
	if !(message.Delivery == 1 || message.Delivery == 2) {
		return &liquidproto.Error{
			Message:   "candace.candaceos.v1.WebUIClawMessageRequest",
			Field:     "delivery",
			Predicate: "this == 1 || this == 2",
			Value:     message.Delivery,
		}
	}
	if !(len(message.ExpectedRunId) >= 1 && len(message.ExpectedRunId) <= 128 && _liquidWebUIClawMessageRequestExpectedRunIdRe0.MatchString(message.ExpectedRunId)) {
		return &liquidproto.Error{
			Message:   "candace.candaceos.v1.WebUIClawMessageRequest",
			Field:     "expected_run_id",
			Predicate: "len(this) >= 1 && len(this) <= 128 && matches(this, `^[A-Za-z0-9][A-Za-z0-9._:-]*$`)",
			Value:     message.ExpectedRunId,
		}
	}
	return nil
}

// ValidateWebUIApprovalRequest checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateWebUIApprovalRequest(message *WebUIApprovalRequest) error {
	if message == nil {
		return fmt.Errorf("ValidateWebUIApprovalRequest: nil *WebUIApprovalRequest")
	}
	if !(message.Decision == `approve` || message.Decision == `reject`) {
		return &liquidproto.Error{
			Message:   "candace.candaceos.v1.WebUIApprovalRequest",
			Field:     "decision",
			Predicate: "this == `approve` || this == `reject`",
			Value:     message.Decision,
		}
	}
	return nil
}
