// Portable cron contracts for HTTP and messaging boundaries.
//
// These messages are not a PostgreSQL storage format. Cron persistence uses
// service-owned relational migrations, queries, and generated SQLC bindings;
// callers map explicitly between those rows, the Go domain model, and these
// boundary messages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cron/v1/cron.proto

package cronv1

import (
	_ "github.com/candacelabs/csf/pkg/liquidproto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weekday int32

const (
	Weekday_WEEKDAY_UNSPECIFIED Weekday = 0
	Weekday_WEEKDAY_SUNDAY      Weekday = 1
	Weekday_WEEKDAY_MONDAY      Weekday = 2
	Weekday_WEEKDAY_TUESDAY     Weekday = 3
	Weekday_WEEKDAY_WEDNESDAY   Weekday = 4
	Weekday_WEEKDAY_THURSDAY    Weekday = 5
	Weekday_WEEKDAY_FRIDAY      Weekday = 6
	Weekday_WEEKDAY_SATURDAY    Weekday = 7
)

// Enum value maps for Weekday.
var (
	Weekday_name = map[int32]string{
		0: "WEEKDAY_UNSPECIFIED",
		1: "WEEKDAY_SUNDAY",
		2: "WEEKDAY_MONDAY",
		3: "WEEKDAY_TUESDAY",
		4: "WEEKDAY_WEDNESDAY",
		5: "WEEKDAY_THURSDAY",
		6: "WEEKDAY_FRIDAY",
		7: "WEEKDAY_SATURDAY",
	}
	Weekday_value = map[string]int32{
		"WEEKDAY_UNSPECIFIED": 0,
		"WEEKDAY_SUNDAY":      1,
		"WEEKDAY_MONDAY":      2,
		"WEEKDAY_TUESDAY":     3,
		"WEEKDAY_WEDNESDAY":   4,
		"WEEKDAY_THURSDAY":    5,
		"WEEKDAY_FRIDAY":      6,
		"WEEKDAY_SATURDAY":    7,
	}
)

func (x Weekday) Enum() *Weekday {
	p := new(Weekday)
	*p = x
	return p
}

func (x Weekday) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Weekday) Descriptor() protoreflect.EnumDescriptor {
	return file_cron_v1_cron_proto_enumTypes[0].Descriptor()
}

func (Weekday) Type() protoreflect.EnumType {
	return &file_cron_v1_cron_proto_enumTypes[0]
}

func (x Weekday) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Weekday.Descriptor instead.
func (Weekday) EnumDescriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{0}
}

type CronDialect int32

const (
	CronDialect_CRON_DIALECT_UNSPECIFIED CronDialect = 0
	// Robfig's standard five-field grammar, including descriptors such as
	// @daily. Interval scheduling should use IntervalSchedule instead.
	CronDialect_CRON_DIALECT_ROBFIG_STANDARD CronDialect = 1
)

// Enum value maps for CronDialect.
var (
	CronDialect_name = map[int32]string{
		0: "CRON_DIALECT_UNSPECIFIED",
		1: "CRON_DIALECT_ROBFIG_STANDARD",
	}
	CronDialect_value = map[string]int32{
		"CRON_DIALECT_UNSPECIFIED":     0,
		"CRON_DIALECT_ROBFIG_STANDARD": 1,
	}
)

func (x CronDialect) Enum() *CronDialect {
	p := new(CronDialect)
	*p = x
	return p
}

func (x CronDialect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CronDialect) Descriptor() protoreflect.EnumDescriptor {
	return file_cron_v1_cron_proto_enumTypes[1].Descriptor()
}

func (CronDialect) Type() protoreflect.EnumType {
	return &file_cron_v1_cron_proto_enumTypes[1]
}

func (x CronDialect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CronDialect.Descriptor instead.
func (CronDialect) EnumDescriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{1}
}

type CatchUpPolicy int32

const (
	CatchUpPolicy_CATCH_UP_POLICY_UNSPECIFIED CatchUpPolicy = 0
	CatchUpPolicy_CATCH_UP_POLICY_NONE        CatchUpPolicy = 1
	CatchUpPolicy_CATCH_UP_POLICY_LATEST      CatchUpPolicy = 2
	CatchUpPolicy_CATCH_UP_POLICY_ALL         CatchUpPolicy = 3
)

// Enum value maps for CatchUpPolicy.
var (
	CatchUpPolicy_name = map[int32]string{
		0: "CATCH_UP_POLICY_UNSPECIFIED",
		1: "CATCH_UP_POLICY_NONE",
		2: "CATCH_UP_POLICY_LATEST",
		3: "CATCH_UP_POLICY_ALL",
	}
	CatchUpPolicy_value = map[string]int32{
		"CATCH_UP_POLICY_UNSPECIFIED": 0,
		"CATCH_UP_POLICY_NONE":        1,
		"CATCH_UP_POLICY_LATEST":      2,
		"CATCH_UP_POLICY_ALL":         3,
	}
)

func (x CatchUpPolicy) Enum() *CatchUpPolicy {
	p := new(CatchUpPolicy)
	*p = x
	return p
}

func (x CatchUpPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatchUpPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_cron_v1_cron_proto_enumTypes[2].Descriptor()
}

func (CatchUpPolicy) Type() protoreflect.EnumType {
	return &file_cron_v1_cron_proto_enumTypes[2]
}

func (x CatchUpPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatchUpPolicy.Descriptor instead.
func (CatchUpPolicy) EnumDescriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{2}
}

type OverlapPolicy int32

const (
	OverlapPolicy_OVERLAP_POLICY_UNSPECIFIED OverlapPolicy = 0
	OverlapPolicy_OVERLAP_POLICY_SKIP        OverlapPolicy = 1
	OverlapPolicy_OVERLAP_POLICY_ALLOW       OverlapPolicy = 2
)

// Enum value maps for OverlapPolicy.
var (
	OverlapPolicy_name = map[int32]string{
		0: "OVERLAP_POLICY_UNSPECIFIED",
		1: "OVERLAP_POLICY_SKIP",
		2: "OVERLAP_POLICY_ALLOW",
	}
	OverlapPolicy_value = map[string]int32{
		"OVERLAP_POLICY_UNSPECIFIED": 0,
		"OVERLAP_POLICY_SKIP":        1,
		"OVERLAP_POLICY_ALLOW":       2,
	}
)

func (x OverlapPolicy) Enum() *OverlapPolicy {
	p := new(OverlapPolicy)
	*p = x
	return p
}

func (x OverlapPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverlapPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_cron_v1_cron_proto_enumTypes[3].Descriptor()
}

func (OverlapPolicy) Type() protoreflect.EnumType {
	return &file_cron_v1_cron_proto_enumTypes[3]
}

func (x OverlapPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverlapPolicy.Descriptor instead.
func (OverlapPolicy) EnumDescriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{3}
}

type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED RunState = 0
	RunState_RUN_STATE_PENDING     RunState = 1
	RunState_RUN_STATE_RUNNING     RunState = 2
	RunState_RUN_STATE_SUCCEEDED   RunState = 3
	RunState_RUN_STATE_FAILED      RunState = 4
	RunState_RUN_STATE_CANCELED    RunState = 5
	RunState_RUN_STATE_SKIPPED     RunState = 6
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_STATE_PENDING",
		2: "RUN_STATE_RUNNING",
		3: "RUN_STATE_SUCCEEDED",
		4: "RUN_STATE_FAILED",
		5: "RUN_STATE_CANCELED",
		6: "RUN_STATE_SKIPPED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED": 0,
		"RUN_STATE_PENDING":     1,
		"RUN_STATE_RUNNING":     2,
		"RUN_STATE_SUCCEEDED":   3,
		"RUN_STATE_FAILED":      4,
		"RUN_STATE_CANCELED":    5,
		"RUN_STATE_SKIPPED":     6,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_cron_v1_cron_proto_enumTypes[4].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_cron_v1_cron_proto_enumTypes[4]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{4}
}

// TimeOfDay is canonical 24-hour wall time. AM/PM exists only in the fluent
// Go DSL and is normalized before crossing a boundary.
type TimeOfDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          uint32                 `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute        uint32                 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeOfDay) Reset() {
	*x = TimeOfDay{}
	mi := &file_cron_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeOfDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeOfDay) ProtoMessage() {}

func (x *TimeOfDay) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeOfDay.ProtoReflect.Descriptor instead.
func (*TimeOfDay) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *TimeOfDay) GetHour() uint32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *TimeOfDay) GetMinute() uint32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type DailySchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *TimeOfDay             `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySchedule) Reset() {
	*x = DailySchedule{}
	mi := &file_cron_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySchedule) ProtoMessage() {}

func (x *DailySchedule) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySchedule.ProtoReflect.Descriptor instead.
func (*DailySchedule) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *DailySchedule) GetAt() *TimeOfDay {
	if x != nil {
		return x.At
	}
	return nil
}

type WeeklySchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weekday       Weekday                `protobuf:"varint,1,opt,name=weekday,proto3,enum=candace.cron.v1.Weekday" json:"weekday,omitempty"`
	At            *TimeOfDay             `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklySchedule) Reset() {
	*x = WeeklySchedule{}
	mi := &file_cron_v1_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklySchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklySchedule) ProtoMessage() {}

func (x *WeeklySchedule) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklySchedule.ProtoReflect.Descriptor instead.
func (*WeeklySchedule) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *WeeklySchedule) GetWeekday() Weekday {
	if x != nil {
		return x.Weekday
	}
	return Weekday_WEEKDAY_UNSPECIFIED
}

func (x *WeeklySchedule) GetAt() *TimeOfDay {
	if x != nil {
		return x.At
	}
	return nil
}

type MonthlyDaySchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayOfMonth    uint32                 `protobuf:"varint,1,opt,name=day_of_month,json=dayOfMonth,proto3" json:"day_of_month,omitempty"`
	At            *TimeOfDay             `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyDaySchedule) Reset() {
	*x = MonthlyDaySchedule{}
	mi := &file_cron_v1_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyDaySchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyDaySchedule) ProtoMessage() {}

func (x *MonthlyDaySchedule) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyDaySchedule.ProtoReflect.Descriptor instead.
func (*MonthlyDaySchedule) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{3}
}

func (x *MonthlyDaySchedule) GetDayOfMonth() uint32 {
	if x != nil {
		return x.DayOfMonth
	}
	return 0
}

func (x *MonthlyDaySchedule) GetAt() *TimeOfDay {
	if x != nil {
		return x.At
	}
	return nil
}

type MonthlyLastDaySchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *TimeOfDay             `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyLastDaySchedule) Reset() {
	*x = MonthlyLastDaySchedule{}
	mi := &file_cron_v1_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyLastDaySchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyLastDaySchedule) ProtoMessage() {}

func (x *MonthlyLastDaySchedule) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyLastDaySchedule.ProtoReflect.Descriptor instead.
func (*MonthlyLastDaySchedule) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{4}
}

func (x *MonthlyLastDaySchedule) GetAt() *TimeOfDay {
	if x != nil {
		return x.At
	}
	return nil
}

// IntervalSchedule is elapsed-time scheduling. anchor is optional desired
// configuration; when absent, the durable store establishes it exactly once
// and exposes the resulting value on JobStatus.
type IntervalSchedule struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IntervalNanoseconds int64                  `protobuf:"varint,1,opt,name=interval_nanoseconds,json=intervalNanoseconds,proto3" json:"interval_nanoseconds,omitempty"`
	Anchor              *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IntervalSchedule) Reset() {
	*x = IntervalSchedule{}
	mi := &file_cron_v1_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalSchedule) ProtoMessage() {}

func (x *IntervalSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalSchedule.ProtoReflect.Descriptor instead.
func (*IntervalSchedule) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{5}
}

func (x *IntervalSchedule) GetIntervalNanoseconds() int64 {
	if x != nil {
		return x.IntervalNanoseconds
	}
	return 0
}

func (x *IntervalSchedule) GetAnchor() *timestamppb.Timestamp {
	if x != nil {
		return x.Anchor
	}
	return nil
}

// RawCronSchedule is an explicit robfig-compatible escape hatch. The dialect
// is required so a future parser cannot silently reinterpret an expression.
type RawCronSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dialect       CronDialect            `protobuf:"varint,1,opt,name=dialect,proto3,enum=candace.cron.v1.CronDialect" json:"dialect,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawCronSchedule) Reset() {
	*x = RawCronSchedule{}
	mi := &file_cron_v1_cron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawCronSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCronSchedule) ProtoMessage() {}

func (x *RawCronSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCronSchedule.ProtoReflect.Descriptor instead.
func (*RawCronSchedule) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{6}
}

func (x *RawCronSchedule) GetDialect() CronDialect {
	if x != nil {
		return x.Dialect
	}
	return CronDialect_CRON_DIALECT_UNSPECIFIED
}

func (x *RawCronSchedule) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// ScheduleSpec is the versioned boundary representation produced by the
// fluent Go schedule DSL. Exactly one rule must be set.
type ScheduleSpec struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Timezone string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// Types that are valid to be assigned to Rule:
	//
	//	*ScheduleSpec_Daily
	//	*ScheduleSpec_Weekly
	//	*ScheduleSpec_MonthlyDay
	//	*ScheduleSpec_MonthlyLastDay
	//	*ScheduleSpec_Interval
	//	*ScheduleSpec_RawCron
	Rule          isScheduleSpec_Rule `protobuf_oneof:"rule"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleSpec) Reset() {
	*x = ScheduleSpec{}
	mi := &file_cron_v1_cron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSpec) ProtoMessage() {}

func (x *ScheduleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSpec.ProtoReflect.Descriptor instead.
func (*ScheduleSpec) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleSpec) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ScheduleSpec) GetRule() isScheduleSpec_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *ScheduleSpec) GetDaily() *DailySchedule {
	if x != nil {
		if x, ok := x.Rule.(*ScheduleSpec_Daily); ok {
			return x.Daily
		}
	}
	return nil
}

func (x *ScheduleSpec) GetWeekly() *WeeklySchedule {
	if x != nil {
		if x, ok := x.Rule.(*ScheduleSpec_Weekly); ok {
			return x.Weekly
		}
	}
	return nil
}

func (x *ScheduleSpec) GetMonthlyDay() *MonthlyDaySchedule {
	if x != nil {
		if x, ok := x.Rule.(*ScheduleSpec_MonthlyDay); ok {
			return x.MonthlyDay
		}
	}
	return nil
}

func (x *ScheduleSpec) GetMonthlyLastDay() *MonthlyLastDaySchedule {
	if x != nil {
		if x, ok := x.Rule.(*ScheduleSpec_MonthlyLastDay); ok {
			return x.MonthlyLastDay
		}
	}
	return nil
}

func (x *ScheduleSpec) GetInterval() *IntervalSchedule {
	if x != nil {
		if x, ok := x.Rule.(*ScheduleSpec_Interval); ok {
			return x.Interval
		}
	}
	return nil
}

func (x *ScheduleSpec) GetRawCron() *RawCronSchedule {
	if x != nil {
		if x, ok := x.Rule.(*ScheduleSpec_RawCron); ok {
			return x.RawCron
		}
	}
	return nil
}

type isScheduleSpec_Rule interface {
	isScheduleSpec_Rule()
}

type ScheduleSpec_Daily struct {
	Daily *DailySchedule `protobuf:"bytes,2,opt,name=daily,proto3,oneof"`
}

type ScheduleSpec_Weekly struct {
	Weekly *WeeklySchedule `protobuf:"bytes,3,opt,name=weekly,proto3,oneof"`
}

type ScheduleSpec_MonthlyDay struct {
	MonthlyDay *MonthlyDaySchedule `protobuf:"bytes,4,opt,name=monthly_day,json=monthlyDay,proto3,oneof"`
}

type ScheduleSpec_MonthlyLastDay struct {
	MonthlyLastDay *MonthlyLastDaySchedule `protobuf:"bytes,5,opt,name=monthly_last_day,json=monthlyLastDay,proto3,oneof"`
}

type ScheduleSpec_Interval struct {
	Interval *IntervalSchedule `protobuf:"bytes,6,opt,name=interval,proto3,oneof"`
}

type ScheduleSpec_RawCron struct {
	RawCron *RawCronSchedule `protobuf:"bytes,7,opt,name=raw_cron,json=rawCron,proto3,oneof"`
}

func (*ScheduleSpec_Daily) isScheduleSpec_Rule() {}

func (*ScheduleSpec_Weekly) isScheduleSpec_Rule() {}

func (*ScheduleSpec_MonthlyDay) isScheduleSpec_Rule() {}

func (*ScheduleSpec_MonthlyLastDay) isScheduleSpec_Rule() {}

func (*ScheduleSpec_Interval) isScheduleSpec_Rule() {}

func (*ScheduleSpec_RawCron) isScheduleSpec_Rule() {}

// JobDefinition is the portable desired job configuration. The executable Go
// handler is registered locally by name and is deliberately not serializable.
type JobDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schedule      *ScheduleSpec          `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	CatchUpPolicy CatchUpPolicy          `protobuf:"varint,3,opt,name=catch_up_policy,json=catchUpPolicy,proto3,enum=candace.cron.v1.CatchUpPolicy" json:"catch_up_policy,omitempty"`
	OverlapPolicy OverlapPolicy          `protobuf:"varint,4,opt,name=overlap_policy,json=overlapPolicy,proto3,enum=candace.cron.v1.OverlapPolicy" json:"overlap_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDefinition) Reset() {
	*x = JobDefinition{}
	mi := &file_cron_v1_cron_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDefinition) ProtoMessage() {}

func (x *JobDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDefinition.ProtoReflect.Descriptor instead.
func (*JobDefinition) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{8}
}

func (x *JobDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobDefinition) GetSchedule() *ScheduleSpec {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *JobDefinition) GetCatchUpPolicy() CatchUpPolicy {
	if x != nil {
		return x.CatchUpPolicy
	}
	return CatchUpPolicy_CATCH_UP_POLICY_UNSPECIFIED
}

func (x *JobDefinition) GetOverlapPolicy() OverlapPolicy {
	if x != nil {
		return x.OverlapPolicy
	}
	return OverlapPolicy_OVERLAP_POLICY_UNSPECIFIED
}

// Invocation identifies one scheduled occurrence. occurrence_id is stable for
// a given job name and scheduled time and is the handler's idempotency key.
type Invocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OccurrenceId  string                 `protobuf:"bytes,1,opt,name=occurrence_id,json=occurrenceId,proto3" json:"occurrence_id,omitempty"`
	JobName       string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Attempt       uint32                 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invocation) Reset() {
	*x = Invocation{}
	mi := &file_cron_v1_cron_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invocation) ProtoMessage() {}

func (x *Invocation) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invocation.ProtoReflect.Descriptor instead.
func (*Invocation) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{9}
}

func (x *Invocation) GetOccurrenceId() string {
	if x != nil {
		return x.OccurrenceId
	}
	return ""
}

func (x *Invocation) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Invocation) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Invocation) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Invocation) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type RunSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invocation    *Invocation            `protobuf:"bytes,1,opt,name=invocation,proto3" json:"invocation,omitempty"`
	State         RunState               `protobuf:"varint,2,opt,name=state,proto3,enum=candace.cron.v1.RunState" json:"state,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ErrorSummary  string                 `protobuf:"bytes,5,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	SkipReason    string                 `protobuf:"bytes,6,opt,name=skip_reason,json=skipReason,proto3" json:"skip_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_cron_v1_cron_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{10}
}

func (x *RunSummary) GetInvocation() *Invocation {
	if x != nil {
		return x.Invocation
	}
	return nil
}

func (x *RunSummary) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *RunSummary) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *RunSummary) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RunSummary) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

func (x *RunSummary) GetSkipReason() string {
	if x != nil {
		return x.SkipReason
	}
	return ""
}

// JobStatus is a read-only status projection suitable for an authenticated
// Gin route. PostgreSQL remains relational and is mapped explicitly.
type JobStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Definition     *JobDefinition         `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	NextRunAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	IntervalAnchor *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=interval_anchor,json=intervalAnchor,proto3" json:"interval_anchor,omitempty"`
	ActiveRuns     uint32                 `protobuf:"varint,5,opt,name=active_runs,json=activeRuns,proto3" json:"active_runs,omitempty"`
	LastRun        *RunSummary            `protobuf:"bytes,6,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_cron_v1_cron_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{11}
}

func (x *JobStatus) GetDefinition() *JobDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *JobStatus) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *JobStatus) GetIntervalAnchor() *timestamppb.Timestamp {
	if x != nil {
		return x.IntervalAnchor
	}
	return nil
}

func (x *JobStatus) GetActiveRuns() uint32 {
	if x != nil {
		return x.ActiveRuns
	}
	return 0
}

func (x *JobStatus) GetLastRun() *RunSummary {
	if x != nil {
		return x.LastRun
	}
	return nil
}

type StatusSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Jobs          []*JobStatus           `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusSnapshot) Reset() {
	*x = StatusSnapshot{}
	mi := &file_cron_v1_cron_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSnapshot) ProtoMessage() {}

func (x *StatusSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSnapshot.ProtoReflect.Descriptor instead.
func (*StatusSnapshot) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{12}
}

func (x *StatusSnapshot) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *StatusSnapshot) GetJobs() []*JobStatus {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_cron_v1_cron_proto protoreflect.FileDescriptor

const file_cron_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x12cron/v1/cron.proto\x12\x0fcandace.cron.v1\x1a\x1fliquidproto/v1/refinement.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\tTimeOfDay\x12$\n" +
	"\x04hour\x18\x01 \x01(\rB\x10\x92\x82\x19\f\n" +
	"\n" +
	"this <= 23R\x04hour\x12(\n" +
	"\x06minute\x18\x02 \x01(\rB\x10\x92\x82\x19\f\n" +
	"\n" +
	"this <= 59R\x06minute\";\n" +
	"\rDailySchedule\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.candace.cron.v1.TimeOfDayR\x02at\"p\n" +
	"\x0eWeeklySchedule\x122\n" +
	"\aweekday\x18\x01 \x01(\x0e2\x18.candace.cron.v1.WeekdayR\aweekday\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.candace.cron.v1.TimeOfDayR\x02at\"\x81\x01\n" +
	"\x12MonthlyDaySchedule\x12?\n" +
	"\fday_of_month\x18\x01 \x01(\rB\x1d\x92\x82\x19\x19\n" +
	"\x17this >= 1 && this <= 31R\n" +
	"dayOfMonth\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.candace.cron.v1.TimeOfDayR\x02at\"D\n" +
	"\x16MonthlyLastDaySchedule\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.candace.cron.v1.TimeOfDayR\x02at\"\x8d\x01\n" +
	"\x10IntervalSchedule\x12E\n" +
	"\x14interval_nanoseconds\x18\x01 \x01(\x03B\x12\x92\x82\x19\x0e\n" +
	"\fthis >= 1000R\x13intervalNanoseconds\x122\n" +
	"\x06anchor\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06anchor\"\x93\x01\n" +
	"\x0fRawCronSchedule\x126\n" +
	"\adialect\x18\x01 \x01(\x0e2\x1c.candace.cron.v1.CronDialectR\adialect\x12H\n" +
	"\n" +
	"expression\x18\x02 \x01(\tB(\x92\x82\x19$\n" +
	"\"len(this) >= 1 && len(this) <= 256R\n" +
	"expression\"\xa7\x04\n" +
	"\fScheduleSpec\x12\x7f\n" +
	"\btimezone\x18\x01 \x01(\tBc\x92\x82\x19_\n" +
	"]len(this) >= 1 && len(this) <= 128 && matches(this, `^[A-Za-z0-9_+.-]+(/[A-Za-z0-9_+.-]+)*$`)R\btimezone\x126\n" +
	"\x05daily\x18\x02 \x01(\v2\x1e.candace.cron.v1.DailyScheduleH\x00R\x05daily\x129\n" +
	"\x06weekly\x18\x03 \x01(\v2\x1f.candace.cron.v1.WeeklyScheduleH\x00R\x06weekly\x12F\n" +
	"\vmonthly_day\x18\x04 \x01(\v2#.candace.cron.v1.MonthlyDayScheduleH\x00R\n" +
	"monthlyDay\x12S\n" +
	"\x10monthly_last_day\x18\x05 \x01(\v2'.candace.cron.v1.MonthlyLastDayScheduleH\x00R\x0emonthlyLastDay\x12?\n" +
	"\binterval\x18\x06 \x01(\v2!.candace.cron.v1.IntervalScheduleH\x00R\binterval\x12=\n" +
	"\braw_cron\x18\a \x01(\v2 .candace.cron.v1.RawCronScheduleH\x00R\arawCronB\x06\n" +
	"\x04rule\"\xc6\x02\n" +
	"\rJobDefinition\x12e\n" +
	"\x04name\x18\x01 \x01(\tBQ\x92\x82\x19M\n" +
	"Klen(this) >= 1 && len(this) <= 128 && matches(this, `^[a-z][a-z0-9._/-]*$`)R\x04name\x129\n" +
	"\bschedule\x18\x02 \x01(\v2\x1d.candace.cron.v1.ScheduleSpecR\bschedule\x12F\n" +
	"\x0fcatch_up_policy\x18\x03 \x01(\x0e2\x1e.candace.cron.v1.CatchUpPolicyR\rcatchUpPolicy\x12E\n" +
	"\x0eoverlap_policy\x18\x04 \x01(\x0e2\x1e.candace.cron.v1.OverlapPolicyR\roverlapPolicyJ\x04\b\x05\x10\x06\"\xde\x02\n" +
	"\n" +
	"Invocation\x12N\n" +
	"\roccurrence_id\x18\x01 \x01(\tB)\x92\x82\x19%\n" +
	"#matches(this, `^occ_[0-9a-f]{64}$`)R\foccurrenceId\x12l\n" +
	"\bjob_name\x18\x02 \x01(\tBQ\x92\x82\x19M\n" +
	"Klen(this) >= 1 && len(this) <= 128 && matches(this, `^[a-z][a-z0-9._/-]*$`)R\ajobName\x12=\n" +
	"\fscheduled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\"\xe4\x02\n" +
	"\n" +
	"RunSummary\x12;\n" +
	"\n" +
	"invocation\x18\x01 \x01(\v2\x1b.candace.cron.v1.InvocationR\n" +
	"invocation\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.candace.cron.v1.RunStateR\x05state\x12;\n" +
	"\vfinished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x123\n" +
	"\tworker_id\x18\x04 \x01(\tB\x16\x92\x82\x19\x12\n" +
	"\x10len(this) <= 128R\bworkerId\x12<\n" +
	"\rerror_summary\x18\x05 \x01(\tB\x17\x92\x82\x19\x13\n" +
	"\x11len(this) <= 4096R\ferrorSummary\x128\n" +
	"\vskip_reason\x18\x06 \x01(\tB\x17\x92\x82\x19\x13\n" +
	"\x11len(this) <= 4096R\n" +
	"skipReason\"\xc2\x02\n" +
	"\tJobStatus\x12>\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x1e.candace.cron.v1.JobDefinitionR\n" +
	"definition\x12:\n" +
	"\vnext_run_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12C\n" +
	"\x0finterval_anchor\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eintervalAnchor\x126\n" +
	"\vactive_runs\x18\x05 \x01(\rB\x15\x92\x82\x19\x11\n" +
	"\x0fthis <= 1000000R\n" +
	"activeRuns\x126\n" +
	"\blast_run\x18\x06 \x01(\v2\x1b.candace.cron.v1.RunSummaryR\alastRunJ\x04\b\x03\x10\x04\"}\n" +
	"\x0eStatusSnapshot\x12;\n" +
	"\vobserved_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12.\n" +
	"\x04jobs\x18\x02 \x03(\v2\x1a.candace.cron.v1.JobStatusR\x04jobs*\xb6\x01\n" +
	"\aWeekday\x12\x17\n" +
	"\x13WEEKDAY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eWEEKDAY_SUNDAY\x10\x01\x12\x12\n" +
	"\x0eWEEKDAY_MONDAY\x10\x02\x12\x13\n" +
	"\x0fWEEKDAY_TUESDAY\x10\x03\x12\x15\n" +
	"\x11WEEKDAY_WEDNESDAY\x10\x04\x12\x14\n" +
	"\x10WEEKDAY_THURSDAY\x10\x05\x12\x12\n" +
	"\x0eWEEKDAY_FRIDAY\x10\x06\x12\x14\n" +
	"\x10WEEKDAY_SATURDAY\x10\a*M\n" +
	"\vCronDialect\x12\x1c\n" +
	"\x18CRON_DIALECT_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCRON_DIALECT_ROBFIG_STANDARD\x10\x01*\x7f\n" +
	"\rCatchUpPolicy\x12\x1f\n" +
	"\x1bCATCH_UP_POLICY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CATCH_UP_POLICY_NONE\x10\x01\x12\x1a\n" +
	"\x16CATCH_UP_POLICY_LATEST\x10\x02\x12\x17\n" +
	"\x13CATCH_UP_POLICY_ALL\x10\x03*b\n" +
	"\rOverlapPolicy\x12\x1e\n" +
	"\x1aOVERLAP_POLICY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OVERLAP_POLICY_SKIP\x10\x01\x12\x18\n" +
	"\x14OVERLAP_POLICY_ALLOW\x10\x02*\xb1\x01\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RUN_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11RUN_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13RUN_STATE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10RUN_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12RUN_STATE_CANCELED\x10\x05\x12\x15\n" +
	"\x11RUN_STATE_SKIPPED\x10\x06B/Z-github.com/candacelabs/csf/pkg/cron/v1;cronv1b\x06proto3"

var (
	file_cron_v1_cron_proto_rawDescOnce sync.Once
	file_cron_v1_cron_proto_rawDescData []byte
)

func file_cron_v1_cron_proto_rawDescGZIP() []byte {
	file_cron_v1_cron_proto_rawDescOnce.Do(func() {
		file_cron_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cron_v1_cron_proto_rawDesc), len(file_cron_v1_cron_proto_rawDesc)))
	})
	return file_cron_v1_cron_proto_rawDescData
}

var file_cron_v1_cron_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_cron_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cron_v1_cron_proto_goTypes = []any{
	(Weekday)(0),                   // 0: candace.cron.v1.Weekday
	(CronDialect)(0),               // 1: candace.cron.v1.CronDialect
	(CatchUpPolicy)(0),             // 2: candace.cron.v1.CatchUpPolicy
	(OverlapPolicy)(0),             // 3: candace.cron.v1.OverlapPolicy
	(RunState)(0),                  // 4: candace.cron.v1.RunState
	(*TimeOfDay)(nil),              // 5: candace.cron.v1.TimeOfDay
	(*DailySchedule)(nil),          // 6: candace.cron.v1.DailySchedule
	(*WeeklySchedule)(nil),         // 7: candace.cron.v1.WeeklySchedule
	(*MonthlyDaySchedule)(nil),     // 8: candace.cron.v1.MonthlyDaySchedule
	(*MonthlyLastDaySchedule)(nil), // 9: candace.cron.v1.MonthlyLastDaySchedule
	(*IntervalSchedule)(nil),       // 10: candace.cron.v1.IntervalSchedule
	(*RawCronSchedule)(nil),        // 11: candace.cron.v1.RawCronSchedule
	(*ScheduleSpec)(nil),           // 12: candace.cron.v1.ScheduleSpec
	(*JobDefinition)(nil),          // 13: candace.cron.v1.JobDefinition
	(*Invocation)(nil),             // 14: candace.cron.v1.Invocation
	(*RunSummary)(nil),             // 15: candace.cron.v1.RunSummary
	(*JobStatus)(nil),              // 16: candace.cron.v1.JobStatus
	(*StatusSnapshot)(nil),         // 17: candace.cron.v1.StatusSnapshot
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
}
var file_cron_v1_cron_proto_depIdxs = []int32{
	5,  // 0: candace.cron.v1.DailySchedule.at:type_name -> candace.cron.v1.TimeOfDay
	0,  // 1: candace.cron.v1.WeeklySchedule.weekday:type_name -> candace.cron.v1.Weekday
	5,  // 2: candace.cron.v1.WeeklySchedule.at:type_name -> candace.cron.v1.TimeOfDay
	5,  // 3: candace.cron.v1.MonthlyDaySchedule.at:type_name -> candace.cron.v1.TimeOfDay
	5,  // 4: candace.cron.v1.MonthlyLastDaySchedule.at:type_name -> candace.cron.v1.TimeOfDay
	18, // 5: candace.cron.v1.IntervalSchedule.anchor:type_name -> google.protobuf.Timestamp
	1,  // 6: candace.cron.v1.RawCronSchedule.dialect:type_name -> candace.cron.v1.CronDialect
	6,  // 7: candace.cron.v1.ScheduleSpec.daily:type_name -> candace.cron.v1.DailySchedule
	7,  // 8: candace.cron.v1.ScheduleSpec.weekly:type_name -> candace.cron.v1.WeeklySchedule
	8,  // 9: candace.cron.v1.ScheduleSpec.monthly_day:type_name -> candace.cron.v1.MonthlyDaySchedule
	9,  // 10: candace.cron.v1.ScheduleSpec.monthly_last_day:type_name -> candace.cron.v1.MonthlyLastDaySchedule
	10, // 11: candace.cron.v1.ScheduleSpec.interval:type_name -> candace.cron.v1.IntervalSchedule
	11, // 12: candace.cron.v1.ScheduleSpec.raw_cron:type_name -> candace.cron.v1.RawCronSchedule
	12, // 13: candace.cron.v1.JobDefinition.schedule:type_name -> candace.cron.v1.ScheduleSpec
	2,  // 14: candace.cron.v1.JobDefinition.catch_up_policy:type_name -> candace.cron.v1.CatchUpPolicy
	3,  // 15: candace.cron.v1.JobDefinition.overlap_policy:type_name -> candace.cron.v1.OverlapPolicy
	18, // 16: candace.cron.v1.Invocation.scheduled_at:type_name -> google.protobuf.Timestamp
	18, // 17: candace.cron.v1.Invocation.started_at:type_name -> google.protobuf.Timestamp
	14, // 18: candace.cron.v1.RunSummary.invocation:type_name -> candace.cron.v1.Invocation
	4,  // 19: candace.cron.v1.RunSummary.state:type_name -> candace.cron.v1.RunState
	18, // 20: candace.cron.v1.RunSummary.finished_at:type_name -> google.protobuf.Timestamp
	13, // 21: candace.cron.v1.JobStatus.definition:type_name -> candace.cron.v1.JobDefinition
	18, // 22: candace.cron.v1.JobStatus.next_run_at:type_name -> google.protobuf.Timestamp
	18, // 23: candace.cron.v1.JobStatus.interval_anchor:type_name -> google.protobuf.Timestamp
	15, // 24: candace.cron.v1.JobStatus.last_run:type_name -> candace.cron.v1.RunSummary
	18, // 25: candace.cron.v1.StatusSnapshot.observed_at:type_name -> google.protobuf.Timestamp
	16, // 26: candace.cron.v1.StatusSnapshot.jobs:type_name -> candace.cron.v1.JobStatus
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_cron_v1_cron_proto_init() }
func file_cron_v1_cron_proto_init() {
	if File_cron_v1_cron_proto != nil {
		return
	}
	file_cron_v1_cron_proto_msgTypes[7].OneofWrappers = []any{
		(*ScheduleSpec_Daily)(nil),
		(*ScheduleSpec_Weekly)(nil),
		(*ScheduleSpec_MonthlyDay)(nil),
		(*ScheduleSpec_MonthlyLastDay)(nil),
		(*ScheduleSpec_Interval)(nil),
		(*ScheduleSpec_RawCron)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cron_v1_cron_proto_rawDesc), len(file_cron_v1_cron_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cron_v1_cron_proto_goTypes,
		DependencyIndexes: file_cron_v1_cron_proto_depIdxs,
		EnumInfos:         file_cron_v1_cron_proto_enumTypes,
		MessageInfos:      file_cron_v1_cron_proto_msgTypes,
	}.Build()
	File_cron_v1_cron_proto = out.File
	file_cron_v1_cron_proto_goTypes = nil
	file_cron_v1_cron_proto_depIdxs = nil
}
