// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/pkg/widget (interfaces: IWidget)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mocks.go -package=mocks github.com/candacelabs/csf/pkg/widget IWidget
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	templ "github.com/a-h/templ"
	live "github.com/candacelabs/csf/pkg/gotth/live"
	widget "github.com/candacelabs/csf/pkg/widget"
	gomock "go.uber.org/mock/gomock"
)

// MockIWidget is a mock of IWidget interface.
type MockIWidget[S any, I live.IIdentity] struct {
	ctrl     *gomock.Controller
	recorder *MockIWidgetMockRecorder[S, I]
	isgomock struct{}
}

// MockIWidgetMockRecorder is the mock recorder for MockIWidget.
type MockIWidgetMockRecorder[S any, I live.IIdentity] struct {
	mock *MockIWidget[S, I]
}

// NewMockIWidget creates a new mock instance.
func NewMockIWidget[S any, I live.IIdentity](ctrl *gomock.Controller) *MockIWidget[S, I] {
	mock := &MockIWidget[S, I]{ctrl: ctrl}
	mock.recorder = &MockIWidgetMockRecorder[S, I]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWidget[S, I]) EXPECT() *MockIWidgetMockRecorder[S, I] {
	return m.recorder
}

// Mount mocks base method.
func (m *MockIWidget[S, I]) Mount(ctx context.Context, session live.Session[I]) (S, []live.Effect[I], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mount", ctx, session)
	ret0, _ := ret[0].(S)
	ret1, _ := ret[1].([]live.Effect[I])
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Mount indicates an expected call of Mount.
func (mr *MockIWidgetMockRecorder[S, I]) Mount(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockIWidget[S, I])(nil).Mount), ctx, session)
}

// Reduce mocks base method.
func (m *MockIWidget[S, I]) Reduce(state S, event live.Event) (S, []live.Effect[I]) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reduce", state, event)
	ret0, _ := ret[0].(S)
	ret1, _ := ret[1].([]live.Effect[I])
	return ret0, ret1
}

// Reduce indicates an expected call of Reduce.
func (mr *MockIWidgetMockRecorder[S, I]) Reduce(state, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reduce", reflect.TypeOf((*MockIWidget[S, I])(nil).Reduce), state, event)
}

// Register mocks base method.
func (m *MockIWidget[S, I]) Register() widget.Registration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(widget.Registration)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIWidgetMockRecorder[S, I]) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIWidget[S, I])(nil).Register))
}

// Render mocks base method.
func (m *MockIWidget[S, I]) Render(state S) templ.Component {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", state)
	ret0, _ := ret[0].(templ.Component)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockIWidgetMockRecorder[S, I]) Render(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockIWidget[S, I])(nil).Render), state)
}

// Snapshot mocks base method.
func (m *MockIWidget[S, I]) Snapshot(state S) widget.Snapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", state)
	ret0, _ := ret[0].(widget.Snapshot)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockIWidgetMockRecorder[S, I]) Snapshot(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockIWidget[S, I])(nil).Snapshot), state)
}

// Unmount mocks base method.
func (m *MockIWidget[S, I]) Unmount(ctx context.Context, session live.Session[I], state S) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unmount", ctx, session, state)
}

// Unmount indicates an expected call of Unmount.
func (mr *MockIWidgetMockRecorder[S, I]) Unmount(ctx, session, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmount", reflect.TypeOf((*MockIWidget[S, I])(nil).Unmount), ctx, session, state)
}
