package uigen

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/candacelabs/csf/pkg/widget/internal/ir"
)

// titleIDSuffix is shared by the default title constant and instance views.
const titleIDSuffix = "-title"

// generatedBy is the first line of every file this package emits.
//
// It is the marker the repository's gates read: the coverage denominator, the
// Go reuse check and the style census all recognise a file by this line, and a
// generated file that did not carry it would be measured as if somebody had
// written it. The wording names the widget rather than a path, because a path
// would make the output depend on where generation was run from.
func generatedBy(document *ir.Document) string {
	return fmt.Sprintf(
		"// Code generated by pkg/widget/internal/uigen from the %s widget document. DO NOT EDIT.",
		document.Name)
}

// emitScaffold writes the Go half of a widget: its state, its lifecycle, and
// the pure derivations its view reads.
func emitScaffold(document *ir.Document, identifiers *names, options Options) ([]byte, error) {
	source := &strings.Builder{}

	fmt.Fprintf(source, "%s\n\n", generatedBy(document))
	fmt.Fprintf(source, "// Package %s is the generated %s widget.\n", options.Package, document.Name)
	fmt.Fprintf(source, "//\n")
	fmt.Fprintf(source, "// Edit the widget document and regenerate; edits here are overwritten.\n")
	fmt.Fprintf(source, "package %s\n\n", options.Package)

	writeImports(source, document)
	writeConstants(source, document, identifiers)
	writeStateType(source, document, identifiers)
	writeLifecycle(source, document, identifiers)
	writeDerivations(source, document, identifiers)

	formatted, formatError := format.Source([]byte(source.String()))
	if formatError != nil {
		return nil, fmt.Errorf("uigen: the scaffold generated for %s does not parse: %w", document.Name, formatError)
	}
	return formatted, nil
}

// writeImports emits exactly the imports the emitted code uses. strconv is the
// only conditional one: a widget whose every state field is text formats
// nothing.
//
// fmt left this list on 2026-09-03 with the Effect method that was its only
// user. A generated widget schedules no effect, and now that a [live.Effect]
// carries its own Run there is no method for one to arrive at wrongly, so
// there is nothing left to format an error about.
func writeImports(source *strings.Builder, document *ir.Document) {
	source.WriteString("import (\n\t\"context\"\n")
	if needsStrconv(document) {
		source.WriteString("\t\"strconv\"\n")
	}
	source.WriteString("\n\t\"github.com/a-h/templ\"\n\n")
	source.WriteString("\t\"github.com/candacelabs/csf/pkg/gotth/live\"\n")
	source.WriteString("\t\"github.com/candacelabs/csf/pkg/widget\"\n)\n\n")
}

// needsStrconv reports whether the emitted code formats anything through
// strconv: every state field but text is rendered that way, and so are the two
// booleans a motion gate and a pressed control put into an attribute.
func needsStrconv(document *ir.Document) bool {
	for _, field := range document.StateFields {
		if field.Type != ir.FieldText {
			return true
		}
	}
	if document.Motion != nil {
		return true
	}
	for _, control := range document.Controls {
		if control.PressedWhen != nil {
			return true
		}
	}
	return false
}

// writeConstants emits the widget's identity and its wire names. They are
// constants because each is a contract in two places at once — the registration
// and the markup, or the registration and the browser — and a literal repeated
// is a literal that drifts.
func writeConstants(source *strings.Builder, document *ir.Document, identifiers *names) {
	// The four are commented as a group rather than one by one, so that a
	// widget whose name is long does not emit a comment line nobody can read.
	fmt.Fprintf(source, "// This widget's identity. The region is the only one that crosses the wire: a\n")
	fmt.Fprintf(source, "// patch names it, so changing it is a client-visible change. The palette is a\n")
	fmt.Fprintf(source, "// name a host resolves to values; this widget carries no colour of its own.\n")
	fmt.Fprintf(source, "// The title id is what the widget's landmark is labelled by.\n")
	fmt.Fprintf(source, "const (\n\t%s = %s\n\t%s = %s\n\t%s = %s\n\t%s = %s\n)\n\n",
		identifiers.nameConst, strconv.Quote(document.Name),
		identifiers.regionConst, strconv.Quote(document.Region),
		identifiers.paletteConst, strconv.Quote(document.Palette),
		identifiers.titleIDConst, strconv.Quote(titleID(document)))

	if len(document.Events) == 0 {
		return
	}
	fmt.Fprintf(source, "// The wire names this widget accepts. The set is exhaustive and default-deny:\n")
	fmt.Fprintf(source, "// a name absent from the registration is refused before any reducer runs.\n")
	source.WriteString("const (\n")
	for _, event := range document.Events {
		fmt.Fprintf(source, "\t%s = %s\n", identifiers.events[event], strconv.Quote(event.Wire))
	}
	source.WriteString(")\n\n")

	writeFieldConstants(source, document, identifiers)
}

// titleID is the identifier the widget's title carries and its landmark is
// labelled by. It is derived from the region rather than authored, because the
// region is already the one identity a widget owns that is unique within a
// host — two widgets on one page cannot collide on it, and the registry refuses
// them at startup if they try.
func titleID(document *ir.Document) string {
	return document.Region + titleIDSuffix
}

// writeFieldConstants emits one constant per declared payload field.
//
// The names are a contract with whatever fills the event — a host adapter
// resolving a declared stream, or the browser — and until they were emitted
// that other half was a literal somebody typed. A field renamed in the document
// then still compiled everywhere and silently stopped updating the widget,
// because an event carrying a field name nothing reads applies nothing. With a
// constant, the rename is a compile error at every site that fills it.
func writeFieldConstants(source *strings.Builder, document *ir.Document, identifiers *names) {
	described := make([]*ir.EventDeclaration, 0, len(document.Events))
	for _, event := range document.Events {
		if len(event.Fields) > 0 {
			described = append(described, event)
		}
	}
	if len(described) == 0 {
		return
	}

	fmt.Fprintf(source, "// The wire field names each event carries. They are the other half of an\n")
	fmt.Fprintf(source, "// event's contract: the widget reads these out of a delivery, and whatever\n")
	fmt.Fprintf(source, "// produced the delivery wrote them in. Registration.Payloads carries the same\n")
	fmt.Fprintf(source, "// names as data, for a host that fills an event it cannot name at compile time.\n")
	source.WriteString("const (\n")
	for index, event := range described {
		if index > 0 {
			source.WriteString("\n")
		}
		for _, field := range event.Fields {
			fmt.Fprintf(source, "\t%s = %s\n",
				identifiers.eventFields[field], strconv.Quote(field.WireName))
		}
	}
	source.WriteString(")\n\n")
}

// writeStateType emits the widget's own state, one Go field per declared state
// field, in declaration order.
func writeStateType(source *strings.Builder, document *ir.Document, identifiers *names) {
	fmt.Fprintf(source, "// %s is this widget's own state, and the type argument every\n", identifiers.stateType)
	fmt.Fprintf(source, "// method below is written in. The host holds it without knowing it; nothing\n")
	fmt.Fprintf(source, "// in this file asserts it back, because nothing in this file ever loses it.\n")
	fmt.Fprintf(source, "type %s struct {\n", identifiers.stateType)
	for index, field := range document.StateFields {
		if index > 0 {
			source.WriteString("\n")
		}
		fmt.Fprintf(source, "\t// %s is the %s state field, declared type %s.\n",
			identifiers.fields[field], strconv.Quote(field.Name), field.Type)
		fmt.Fprintf(source, "\t%s %s\n", identifiers.fields[field], goType(field))
	}
	source.WriteString("}\n\n")
}

// goType is a state field's Go type. A counter is unsigned because it is
// monotonic; a count is an ordinary signed number.
func goType(field *ir.StateField) string {
	switch field.Type {
	case ir.FieldFlag:
		return "bool"
	case ir.FieldCounter:
		return "uint64"
	case ir.FieldCount:
		return "int64"
	default:
		return "string"
	}
}

// writeLifecycle emits the six methods of the SDK's widget contract, plus the
// optional dirty declaration.
func writeLifecycle(source *strings.Builder, document *ir.Document, identifiers *names) {
	fmt.Fprintf(source, "// %s is the generated %s widget.\n", identifiers.widgetType, document.Name)
	fmt.Fprintf(source, "//\n")
	fmt.Fprintf(source, "// I is the HOST's identity type, threaded through and never read: a widget\n")
	fmt.Fprintf(source, "// document names no host, no address and no credential, so nothing here can\n")
	fmt.Fprintf(source, "// look at an identity. It is a type parameter because the SDK's contract\n")
	fmt.Fprintf(source, "// carries one — live.Session stopped erasing the application's identity type\n")
	fmt.Fprintf(source, "// on 2026-09-03 — and a generated widget must fit whatever host registers it.\n")
	fmt.Fprintf(source, "type %s[I live.IIdentity] struct {\n\tregion string\n}\n\n", identifiers.widgetType)
	fmt.Fprintf(source, "// %s returns the widget a host registers, instantiated on that\n", identifiers.constructor)
	fmt.Fprintf(source, "// host's own identity type.\n")
	fmt.Fprintf(source, "func %s[I live.IIdentity]() *%s[I] { return %s[I](%s) }\n\n",
		identifiers.constructor, identifiers.widgetType, identifiers.constructorAt, identifiers.regionConst)
	fmt.Fprintf(source, "// %s gives one instance its host-assigned region. The host validates\n", identifiers.constructorAt)
	fmt.Fprintf(source, "// region syntax and uniqueness when assembling its live configuration.\n")
	fmt.Fprintf(source, "func %s[I live.IIdentity](region string) *%s[I] { return &%s[I]{region: region} }\n\n",
		identifiers.constructorAt, identifiers.widgetType, identifiers.widgetType)
	fmt.Fprintf(source, "// The contract, asserted at one instantiation. Anonymous is the identity a\n")
	fmt.Fprintf(source, "// host with no accounts uses, and any other I satisfies the same interfaces:\n")
	fmt.Fprintf(source, "// nothing below branches on it.\n")
	fmt.Fprintf(source, "var (\n\t_ widget.IWidget[%s, live.AnonymousIdentity]        = (*%s[live.AnonymousIdentity])(nil)\n"+
		"\t_ widget.IDirtyDeclarer[%s] = (*%s[live.AnonymousIdentity])(nil)\n)\n\n",
		identifiers.stateType, identifiers.widgetType,
		identifiers.stateType, identifiers.widgetType)

	writeRegister(source, document, identifiers)
	writeMount(source, identifiers)
	writeReduce(source, document, identifiers)
	writeRender(source, identifiers)
	writeDirty(source, document, identifiers)
	writeUnmount(source, identifiers)
	writeSnapshot(source, document, identifiers)
}

// writeRegister emits the `register` phase, with the declared events split
// across the two sides of the registration's own line.
//
// The split is the whole of the widget's inbound security posture and it is
// computed here rather than asked of the author: an event a declared stream
// delivers goes to Internal, everything else to Events. Registration is what
// makes a wire name sendable by a browser, so an event that arrives from a
// server-side subscription must not be registered — otherwise any browser can
// post the source's own truth and the widget cannot tell the two apart.
//
// Before this, every declared event was emitted into Events and the first host
// to adopt a generated widget subtracted the stream-delivered ones by hand. The
// SDK's own demo did not, and a livetest client could forge a cluster snapshot
// into it. A subtraction each host has to remember is a subtraction the second
// host forgets.
func writeRegister(source *strings.Builder, document *ir.Document, identifiers *names) {
	fmt.Fprintf(source, "// Register declares this instance's definition and assigned region.\n")
	fmt.Fprintf(source, "//\n")
	fmt.Fprintf(source, "// Events are the names a browser may send; Internal are the names only a\n")
	fmt.Fprintf(source, "// declared stream delivers, which the host routes without registering.\n")
	fmt.Fprintf(source, "func (instance *%s[I]) Register() widget.Registration {\n", identifiers.widgetType)
	source.WriteString("\treturn widget.Registration{\n")
	fmt.Fprintf(source, "\t\tName:   %s,\n\t\tRegion: instance.region,\n", identifiers.nameConst)

	sendable, internal := splitEvents(document)
	writeEventNames(source, "Events", sendable, identifiers)
	writeEventNames(source, "Internal", internal, identifiers)

	if len(document.Streams) > 0 {
		source.WriteString("\t\tStreams: []widget.StreamDeclaration{\n")
		for _, stream := range document.Streams {
			fmt.Fprintf(source, "\t\t\t{Name: %s, Source: %s, Delivers: %s},\n",
				strconv.Quote(stream.Name), strconv.Quote(stream.Source), identifiers.events[stream.Delivers])
		}
		source.WriteString("\t\t},\n")
	}
	writePayloads(source, document, identifiers)
	source.WriteString("\t}\n}\n\n")
}

// splitEvents divides the declared events into the browser-sendable ones and
// the ones a declared stream delivers, each in declaration order.
func splitEvents(document *ir.Document) ([]*ir.EventDeclaration, []*ir.EventDeclaration) {
	delivered := make(map[*ir.EventDeclaration]struct{}, len(document.Streams))
	for _, stream := range document.Streams {
		delivered[stream.Delivers] = struct{}{}
	}

	sendable := make([]*ir.EventDeclaration, 0, len(document.Events))
	internal := make([]*ir.EventDeclaration, 0, len(document.Events))
	for _, event := range document.Events {
		if _, streamed := delivered[event]; streamed {
			internal = append(internal, event)
			continue
		}
		sendable = append(sendable, event)
	}
	return sendable, internal
}

// writeEventNames emits one side of the split, or nothing when that side is
// empty: a registration with no Internal names should read as one, rather than
// carrying an empty slice that looks like a decision.
func writeEventNames(
	source *strings.Builder, field string, events []*ir.EventDeclaration, identifiers *names,
) {
	if len(events) == 0 {
		return
	}
	fmt.Fprintf(source, "\t\t%s: []string{", field)
	for index, event := range events {
		if index > 0 {
			source.WriteString(", ")
		}
		source.WriteString(identifiers.events[event])
	}
	source.WriteString("},\n")
}

// writePayloads emits the wire field names each event carries, as data beside
// the constants that name them: a host filling an event it cannot name at
// compile time reads this, and a specification asserting that a host fills
// exactly the declared set compares against it.
func writePayloads(source *strings.Builder, document *ir.Document, identifiers *names) {
	described := make([]*ir.EventDeclaration, 0, len(document.Events))
	for _, event := range document.Events {
		if len(event.Fields) > 0 {
			described = append(described, event)
		}
	}
	if len(described) == 0 {
		return
	}

	source.WriteString("\t\tPayloads: []widget.EventPayload{\n")
	for _, event := range described {
		fmt.Fprintf(source, "\t\t\t{Event: %s, Fields: []string{\n", identifiers.events[event])
		for _, field := range event.Fields {
			fmt.Fprintf(source, "\t\t\t\t%s,\n", identifiers.eventFields[field])
		}
		source.WriteString("\t\t\t}},\n")
	}
	source.WriteString("\t\t},\n")
}

func writeMount(source *strings.Builder, identifiers *names) {
	fmt.Fprintf(source, "// Mount opens one session's copy of the widget. It schedules no effect: the\n")
	fmt.Fprintf(source, "// streams this widget declared are the host's to open, because a widget document\n")
	fmt.Fprintf(source, "// names no host, no address and no credential.\n")
	fmt.Fprintf(source, "func (instance *%s[I]) Mount(\n\tctx context.Context, session live.Session[I],\n"+
		") (%s, []live.Effect[I], error) {\n", identifiers.widgetType, identifiers.stateType)
	fmt.Fprintf(source, "\treturn %s{}, nil, nil\n}\n\n", identifiers.stateType)
}

// writeReduce emits the event phase: one case per declared event, plus the two
// runtime signals if any state field carries one.
func writeReduce(source *strings.Builder, document *ir.Document, identifiers *names) {
	fmt.Fprintf(source, "// Reduce is the pure transition from one state to the next. It performs no I/O,\n")
	fmt.Fprintf(source, "// reads no clock and mutates nothing it was given.\n")
	fmt.Fprintf(source, "func (instance *%s[I]) Reduce(\n\tstate %s, event live.Event,\n"+
		") (%s, []live.Effect[I]) {\n",
		identifiers.widgetType, identifiers.stateType, identifiers.stateType)
	source.WriteString("\tcurrent := state\n")

	signalled := signalFields(document)
	if len(document.Events) > 0 || len(signalled) > 0 {
		source.WriteString("\tswitch event.Name {\n")
		for _, event := range document.Events {
			fmt.Fprintf(source, "\tcase %s:\n", identifiers.events[event])
			writeEventBody(source, event, identifiers)
		}
		if len(signalled) > 0 {
			source.WriteString("\tcase live.SlowClientEvent:\n")
			for _, field := range signalled {
				fmt.Fprintf(source, "\t\tcurrent.%s = true\n", identifiers.fields[field])
			}
			source.WriteString("\tcase live.ClientRecoveredEvent:\n")
			for _, field := range signalled {
				fmt.Fprintf(source, "\t\tcurrent.%s = false\n", identifiers.fields[field])
			}
		}
		source.WriteString("\t}\n")
	}
	source.WriteString("\treturn current, nil\n}\n\n")
}

// writeEventBody applies one event to state: a toggle, or one assignment per
// payload field it carries.
func writeEventBody(source *strings.Builder, event *ir.EventDeclaration, identifiers *names) {
	if event.Toggles != nil {
		fmt.Fprintf(source, "\t\tcurrent.%s = !current.%s\n",
			identifiers.fields[event.Toggles], identifiers.fields[event.Toggles])
	}
	for _, field := range event.Fields {
		target := identifiers.fields[field.Writes]
		fmt.Fprintf(source, "\t\tif raw, present := event.Fields.Lookup(%s); present {\n",
			identifiers.eventFields[field])
		fmt.Fprintf(source, "\t\t\tcurrent.%s = %s\n\t\t}\n", target, parseExpression(field.Writes, target))
	}
	if event.Toggles == nil && len(event.Fields) == 0 {
		source.WriteString("\t\t// This event carries no payload and writes no field.\n")
	}
}

// parseExpression reads one wire value into a state field, keeping the field's
// current value when the wire value is unreadable.
func parseExpression(field *ir.StateField, target string) string {
	switch field.Type {
	case ir.FieldFlag:
		return fmt.Sprintf("widget.ParseFlag(raw, current.%s)", target)
	case ir.FieldCounter:
		return fmt.Sprintf("widget.ParseCounter(raw, current.%s)", target)
	case ir.FieldCount:
		return fmt.Sprintf("widget.ParseCount(raw, current.%s)", target)
	default:
		return "raw"
	}
}

// signalFields returns the state fields the runtime writes, in declaration
// order.
func signalFields(document *ir.Document) []*ir.StateField {
	var signalled []*ir.StateField
	for _, field := range document.StateFields {
		if field.Signal != "" {
			signalled = append(signalled, field)
		}
	}
	return signalled
}

func writeRender(source *strings.Builder, identifiers *names) {
	fmt.Fprintf(source, "// Render draws the widget's live region. It is a pure function of state:\n")
	fmt.Fprintf(source, "// equal state renders byte-identical markup.\n")
	fmt.Fprintf(source, "func (instance *%s[I]) Render(state %s) templ.Component {\n",
		identifiers.widgetType, identifiers.stateType)
	fmt.Fprintf(source, "\treturn %s(state, instance.region)\n}\n\n", identifiers.viewAtFunc)
}

// writeDirty emits the widget's own answer to "did this transition reach my
// region", from the document's computed dirty projection.
//
// The projection is derived from the same document the render is, which is the
// whole of why a widget may declare one at all: over-declaring costs a
// suppressed render, under-declaring is a correctness bug the compiler cannot
// see, and a set maintained by hand beside a render drifts in the second
// direction.
func writeDirty(source *strings.Builder, document *ir.Document, identifiers *names) {
	fmt.Fprintf(source, "// Dirty reports whether a transition may have changed this widget's markup: the\n")
	fmt.Fprintf(source, "// state fields its bindings, its predicates and its tick read, and no others.\n")
	fmt.Fprintf(source, "func (instance *%s[I]) Dirty(previous %s, next %s) bool {\n",
		identifiers.widgetType, identifiers.stateType, identifiers.stateType)

	fields := document.DirtyProjection.Fields
	if len(fields) == 0 {
		source.WriteString("\t// Nothing this widget renders reads state, so no transition can move it.\n")
		source.WriteString("\treturn false\n}\n\n")
		return
	}

	comparisons := make([]string, 0, len(fields))
	for _, field := range fields {
		comparisons = append(comparisons, fmt.Sprintf("previous.%s != next.%s",
			identifiers.fields[field], identifiers.fields[field]))
	}
	fmt.Fprintf(source, "\treturn %s\n}\n\n", strings.Join(comparisons, " ||\n\t\t"))
}

func writeUnmount(source *strings.Builder, identifiers *names) {
	fmt.Fprintf(source, "// Unmount releases what the session held. This widget holds nothing.\n")
	fmt.Fprintf(source, "func (instance *%s[I]) Unmount(ctx context.Context, session live.Session[I], state %s) {}\n\n",
		identifiers.widgetType, identifiers.stateType)
}

func writeSnapshot(source *strings.Builder, document *ir.Document, identifiers *names) {
	fmt.Fprintf(source, "// Snapshot projects state into ordered name/value pairs, in state-field\n")
	fmt.Fprintf(source, "// declaration order.\n")
	fmt.Fprintf(source, "func (instance *%s[I]) Snapshot(state %s) widget.Snapshot {\n",
		identifiers.widgetType, identifiers.stateType)
	fmt.Fprintf(source, "\treturn widget.Snapshot{\n\t\tWidget: %s,\n", identifiers.nameConst)
	source.WriteString("\t\tFields: []widget.SnapshotField{\n")
	for _, field := range document.StateFields {
		fmt.Fprintf(source, "\t\t\t{Name: %s, Value: %s},\n",
			strconv.Quote(field.Name), formatExpression(field, "state."+identifiers.fields[field]))
	}
	source.WriteString("\t\t},\n\t}\n}\n\n")
}

// formatExpression renders one state field as text.
func formatExpression(field *ir.StateField, reference string) string {
	switch field.Type {
	case ir.FieldFlag:
		return "strconv.FormatBool(" + reference + ")"
	case ir.FieldCounter:
		return "strconv.FormatUint(" + reference + ", 10)"
	case ir.FieldCount:
		return "strconv.FormatInt(" + reference + ", 10)"
	default:
		return reference
	}
}

// writeDerivations emits the pure reads the view calls: one method per composed
// predicate, per binding and per label, in declaration order.
func writeDerivations(source *strings.Builder, document *ir.Document, identifiers *names) {
	for _, predicate := range document.Predicates {
		if predicate.Kind == ir.PredicateAtomic {
			continue
		}
		fmt.Fprintf(source, "// %s is the %s predicate.\n",
			identifiers.predicates[predicate], strconv.Quote(predicate.Name))
		fmt.Fprintf(source, "func (state %s) %s() bool {\n\treturn %s\n}\n\n",
			identifiers.stateType, identifiers.predicates[predicate], composedExpression(predicate, identifiers))
	}

	for _, binding := range document.Bindings {
		fmt.Fprintf(source, "// %s is the %s binding. The first matching clause wins and the\n",
			identifiers.bindings[binding], strconv.Quote(binding.Name))
		fmt.Fprintf(source, "// otherwise arm is always present, so it is total.\n")
		fmt.Fprintf(source, "func (state %s) %s() string {\n", identifiers.stateType, identifiers.bindings[binding])
		for _, clause := range binding.Clauses {
			fmt.Fprintf(source, "\tif %s {\n\t\treturn %s\n\t}\n",
				guardExpression(clause, identifiers), templateExpression(clause.Template, identifiers))
		}
		fmt.Fprintf(source, "\treturn %s\n}\n\n", templateExpression(binding.Otherwise, identifiers))
	}

	for _, label := range document.Labels {
		fmt.Fprintf(source, "// %s is the %s label.\n",
			identifiers.labels[label], strconv.Quote(label.Name))
		fmt.Fprintf(source, "func (state %s) %s() string {\n\treturn %s\n}\n\n",
			identifiers.stateType, identifiers.labels[label], labelExpression(label, identifiers))
	}

	writeMotionDerivations(source, document, identifiers)
	writeIndicatorDerivations(source, document, identifiers)
	writeControlDerivations(source, document, identifiers)
}

// writeMotionDerivations emits the widget's half of the motion gate, and the
// tick identity that re-arms it.
//
// The other half is the host's connection status, which is not this widget's to
// write: the runtime puts it on the document element and the stylesheet reads
// both, so an animation cannot run against a dead connection whatever this
// widget says. The document's own gate is emitted whole here rather than
// per animation, because nothing animates outside it — there is no per-pulse
// override and no animation declared anywhere else.
func writeMotionDerivations(source *strings.Builder, document *ir.Document, identifiers *names) {
	motion := document.Motion
	if motion == nil {
		return
	}

	fmt.Fprintf(source, "// %s is this widget's compiled motion gate: everything its motion\n",
		identifiers.motionActiveFunc)
	fmt.Fprintf(source, "// block requires, and none of what it forbids. The host's own connection status\n")
	fmt.Fprintf(source, "// is the gate's other half and is applied by the stylesheet, so an animation\n")
	fmt.Fprintf(source, "// cannot run against a dead connection whatever this returns.\n")
	fmt.Fprintf(source, "func (state %s) %s() bool {\n\treturn %s\n}\n\n",
		identifiers.stateType, identifiers.motionActiveFunc,
		conjunction(predicateTerms(motion.Requires, motion.Forbids, identifiers)))

	fmt.Fprintf(source, "// %s renders the gate into the attribute the stylesheet selects on.\n",
		identifiers.motionActiveText)
	fmt.Fprintf(source, "func (state %s) %s() string {\n\treturn strconv.FormatBool(state.%s())\n}\n\n",
		identifiers.stateType, identifiers.motionActiveText, identifiers.motionActiveFunc)

	if motion.RestartOn == nil {
		return
	}
	fmt.Fprintf(source, "// %s is the scene's identity for one tick.\n", identifiers.motionTickFunc)
	fmt.Fprintf(source, "//\n")
	fmt.Fprintf(source, "// Every animation is finite and none repeats, so what starts one again is a new\n")
	fmt.Fprintf(source, "// element: the scene carries this as its id, the tick advances, and the picture\n")
	fmt.Fprintf(source, "// moves exactly as often as the data does.\n")
	fmt.Fprintf(source, "func (state %s) %s() string {\n\treturn state.%s(%s)\n}\n\n",
		identifiers.stateType, identifiers.motionTickFunc, identifiers.motionTickAtFunc, identifiers.regionConst)
	fmt.Fprintf(source, "// %s namespaces the scene's tick identity under its live instance.\n", identifiers.motionTickAtFunc)
	fmt.Fprintf(source, "func (state %s) %s(region string) string {\n\treturn region + \"-tick-\" + strconv.FormatUint(state.%s, 10)\n}\n\n",
		identifiers.stateType, identifiers.motionTickAtFunc, identifiers.fields[motion.RestartOn])
}

// writeIndicatorDerivations emits each indicator's tone.
//
// Tone is binary and unauthored: the predicate holding selects the palette's
// positive token, not holding selects its warning one. There is no third state,
// which is what stops an indicator drifting into a general-purpose coloured dot.
func writeIndicatorDerivations(source *strings.Builder, document *ir.Document, identifiers *names) {
	for _, indicator := range document.Indicators {
		fmt.Fprintf(source, "// %s is the %s indicator's tone: %s while its predicate holds, %s otherwise.\n",
			identifiers.indicatorTones[indicator], strconv.Quote(indicator.Name),
			ir.TokenPositive, ir.TokenWarning)
		fmt.Fprintf(source, "func (state %s) %s() string {\n\tif %s {\n\t\treturn %s\n\t}\n\treturn %s\n}\n\n",
			identifiers.stateType, identifiers.indicatorTones[indicator],
			predicateExpression(indicator.Predicate, identifiers),
			strconv.Quote(string(ir.TokenPositive)), strconv.Quote(string(ir.TokenWarning)))
	}
}

// writeControlDerivations emits the pressed state of each control that declared
// one. A control without a pressed-state predicate gets no method and renders no
// aria-pressed, because there is no "sometimes pressed" control.
func writeControlDerivations(source *strings.Builder, document *ir.Document, identifiers *names) {
	for _, control := range document.Controls {
		if control.PressedWhen == nil {
			continue
		}
		fmt.Fprintf(source, "// %s renders the %s control's pressed state.\n",
			identifiers.controlPressed[control], strconv.Quote(control.Name))
		fmt.Fprintf(source, "func (state %s) %s() string {\n\treturn strconv.FormatBool(%s)\n}\n\n",
			identifiers.stateType, identifiers.controlPressed[control],
			predicateExpression(control.PressedWhen, identifiers))
	}
}

// composedExpression is a composed predicate as one boolean expression:
// everything it requires, nothing it forbids, and every numeric bound.
func composedExpression(predicate *ir.Predicate, identifiers *names) string {
	terms := predicateTerms(predicate.Requires, predicate.Forbids, identifiers)
	for _, bound := range predicate.Bounds {
		comparison := ">="
		if bound.Comparison == ir.ComparisonAtMost {
			comparison = "<="
		}
		terms = append(terms, fmt.Sprintf("state.%s %s %d",
			identifiers.fields[bound.Field], comparison, bound.Value))
	}
	return conjunction(terms)
}

// predicateTerms is what a conjunction of predicates requires and forbids, as Go
// expressions in declaration order.
//
// A composed predicate and a motion gate are the same conjunction of the same
// two clause lists — the dialect spells both with `requires` and `forbids` — so
// they read it here rather than each building it, and a change to what a
// negation emits cannot reach one of them and miss the other.
func predicateTerms(requires []*ir.Predicate, forbids []*ir.Predicate, identifiers *names) []string {
	terms := make([]string, 0, len(requires)+len(forbids))
	for _, required := range requires {
		terms = append(terms, predicateExpression(required, identifiers))
	}
	for _, forbidden := range forbids {
		terms = append(terms, "!"+predicateExpression(forbidden, identifiers))
	}
	return terms
}

// conjunction joins terms, or is `true` for none of them.
//
// An empty conjunction is vacuously true, and writing it out is deliberate: a
// motion block that gates on nothing animates whenever the host is live, and a
// generated `true` says so where an empty expression would not compile.
func conjunction(terms []string) string {
	if len(terms) == 0 {
		return "true"
	}
	return strings.Join(terms, " && ")
}

// predicateExpression reads one predicate: a flag field under its own name, or
// a call to the composition's method.
func predicateExpression(predicate *ir.Predicate, identifiers *names) string {
	if predicate.Kind == ir.PredicateAtomic {
		return "state." + identifiers.fields[predicate.Field]
	}
	return "state." + identifiers.predicates[predicate] + "()"
}

// guardExpression is one binding clause's guard, in its declared polarity. The
// two polarities are two constructs rather than two spellings of one.
func guardExpression(clause *ir.BindingClause, identifiers *names) string {
	expression := predicateExpression(clause.Predicate, identifiers)
	if clause.Polarity == ir.GuardWhenNot {
		return "!" + expression
	}
	return expression
}

// templateExpression is a text template as one Go string expression: literal
// runs quoted, interpolated fields formatted.
func templateExpression(template *ir.TextTemplate, identifiers *names) string {
	if template == nil || len(template.Segments) == 0 {
		return `""`
	}
	parts := make([]string, 0, len(template.Segments))
	for _, segment := range template.Segments {
		if segment.Field == nil {
			parts = append(parts, strconv.Quote(segment.Literal))
			continue
		}
		parts = append(parts,
			formatExpression(segment.Field, "state."+identifiers.fields[segment.Field]))
	}
	return strings.Join(parts, " + ")
}

// labelExpression is a label's one source: a literal template, or the binding
// it is bound to.
func labelExpression(label *ir.Label, identifiers *names) string {
	if label.SourceKind == ir.LabelBound {
		return "state." + identifiers.bindings[label.Binding] + "()"
	}
	return templateExpression(label.Literal, identifiers)
}
