package main

import (
	"os"
	"path/filepath"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

const (
	cleanDocument   = "../../../docs/examples/02-node-status.widget"
	clusterDocument = "../../../docs/examples/01-cluster-heartbeats.widget"
	wrongDocument   = "../../../docs/examples/04-wrong-on-purpose.widget"
)

// changeTriggerDocument is a document the interpreter accepts and the generator
// refuses: a control bound to `change`, which needs a form control the dialect
// has no way to describe. It is written here rather than added to docs/examples
// because those four are the language's worked cases, and a fifth that exists to
// trip a generator would be teaching an author a construct not to use.
const changeTriggerDocument = `widget Typed
dialect 0
region "widget.typed"
palette fieldStation

state
  field armed type flag
end

bindings
  binding captionText
    when armed then "Disarm"
    otherwise "Arm"
  end

  binding sceneDescriptionText
    when armed then "One armed node."
    otherwise "One idle node."
  end
end

labels
  label titleLabel text "Typed"
  label sceneDescriptionLabel binds sceneDescriptionText
  label nodeALabel text "node-a"
  label captionLabel binds captionText
end

chrome
  title titleLabel
end

roles
  role node
    token accent
    marker large
    emphasis forbidden
  end
end

placements
  placement centre left 50 top 50
end

scene solo
  description sceneDescriptionLabel

  node nodeA
    role node
    at centre
    title nodeALabel
  end
end

controls
  control armToggle
    caption captionLabel
    trigger change
    emits toggleArmed
  end
end

events
  event toggleArmed
    wire "widget.typed.toggle"
    toggles armed
  end
end
`

func invoke(arguments ...string) (int, string, string) {
	output, errorOutput := &strings.Builder{}, &strings.Builder{}
	status := run(arguments, output, errorOutput)
	return status, output.String(), errorOutput.String()
}

var _ = Describe("widgetc validate", func() {
	It("says nothing and exits clean for a document with no findings", func() {
		status, output, errorOutput := invoke("validate", cleanDocument)
		Expect(status).To(Equal(exitClean))
		Expect(output).To(BeEmpty())
		Expect(errorOutput).To(BeEmpty())
	})

	It("prints every finding and exits 1 for a document with findings", func() {
		status, output, _ := invoke("validate", wrongDocument)
		Expect(status).To(Equal(exitFindings))
		Expect(output).To(ContainSubstring("04-wrong-on-purpose.widget:23:1: W002:"))
		Expect(output).To(ContainSubstring("    fix: "))
		Expect(output).To(HaveSuffix("04-wrong-on-purpose.widget: 29 findings\n"))
	})

	It("reports through the exit status alone when asked to be quiet", func() {
		status, output, _ := invoke("validate", "-quiet", wrongDocument)
		Expect(status).To(Equal(exitFindings))
		Expect(output).To(BeEmpty())
	})

	It("validates several documents in one run", func() {
		status, output, _ := invoke("validate", cleanDocument, wrongDocument)
		Expect(status).To(Equal(exitFindings))
		Expect(output).To(ContainSubstring("29 findings"))
		Expect(output).ToNot(ContainSubstring("02-node-status.widget:"))
	})

	It("exits 2 when a document cannot be read, so an unrun check never reads as a pass", func() {
		status, _, errorOutput := invoke("validate", cleanDocument, "absent.widget")
		Expect(status).To(Equal(exitUnreadable))
		Expect(errorOutput).To(ContainSubstring("read widget document absent.widget"))
	})

	It("keeps the unreadable status even when another document had findings", func() {
		status, _, _ := invoke("validate", wrongDocument, "absent.widget")
		Expect(status).To(Equal(exitUnreadable))
	})
})

var _ = Describe("widgetc generate", func() {
	var outputDirectory string

	BeforeEach(func() {
		outputDirectory = GinkgoT().TempDir()
	})

	It("writes both artifacts and names them, for a document with no findings", func() {
		status, output, errorOutput := invoke(
			"generate", "-package", "nodestatus", "-out", outputDirectory, cleanDocument)

		Expect(status).To(Equal(exitClean))
		Expect(errorOutput).To(BeEmpty())
		Expect(output).To(ContainSubstring(filepath.Join(outputDirectory, "view.templ")))
		Expect(output).To(ContainSubstring(filepath.Join(outputDirectory, "widget.gen.go")))

		for _, name := range []string{"view.templ", "widget.gen.go"} {
			written, readError := os.ReadFile(filepath.Join(outputDirectory, name))
			Expect(readError).ToNot(HaveOccurred())
			Expect(string(written)).To(HavePrefix(
				"// Code generated by pkg/widget/internal/uigen from the NodeStatus widget document. DO NOT EDIT.\n"))
		}
	})

	It("refuses a document with findings, printing them rather than only the refusal", func() {
		status, output, errorOutput := invoke(
			"generate", "-package", "wrong", "-out", outputDirectory, wrongDocument)

		Expect(status).To(Equal(exitFindings))
		Expect(output).To(ContainSubstring("29 findings"))
		Expect(errorOutput).To(ContainSubstring("nothing generates before it validates"))
		Expect(os.ReadDir(outputDirectory)).To(BeEmpty())
	})

	It("generates the widest exemplar the dialect has", func() {
		status, output, errorOutput := invoke(
			"generate", "-package", "heartbeats", "-out", outputDirectory, clusterDocument)

		Expect(errorOutput).To(BeEmpty())
		Expect(status).To(Equal(exitClean))
		Expect(output).To(ContainSubstring(filepath.Join(outputDirectory, "view.templ")))
		Expect(output).To(ContainSubstring(filepath.Join(outputDirectory, "widget.gen.go")))
	})

	It("refuses a document using a construct the generator does not emit, naming it", func() {
		document := filepath.Join(GinkgoT().TempDir(), "typed.widget")
		Expect(os.WriteFile(document, []byte(changeTriggerDocument), 0o644)).To(Succeed())

		status, _, errorOutput := invoke(
			"generate", "-package", "typed", "-out", outputDirectory, document)

		Expect(status).To(Equal(exitFindings))
		Expect(errorOutput).To(ContainSubstring("a control with a change trigger"))
		Expect(os.ReadDir(outputDirectory)).To(BeEmpty())
	})

	It("exits 2 when the document cannot be read", func() {
		status, _, errorOutput := invoke(
			"generate", "-package", "nodestatus", "-out", outputDirectory, "absent.widget")

		Expect(status).To(Equal(exitUnreadable))
		Expect(errorOutput).To(ContainSubstring("read widget document absent.widget"))
	})
})

var _ = DescribeTable("A command line that is not one",
	func(arguments []string) {
		status, output, errorOutput := invoke(arguments...)
		Expect(status).To(Equal(exitUnreadable))
		Expect(output).To(BeEmpty())
		Expect(errorOutput).To(ContainSubstring("usage: widgetc validate"))
	},
	Entry("no arguments", []string{}),
	Entry("an unknown verb", []string{"check", cleanDocument}),
	Entry("no documents", []string{"validate"}),
	Entry("an unknown flag", []string{"validate", "-strict", cleanDocument}),
	Entry("a generate with no document", []string{"generate", "-package", "p", "-out", "."}),
	Entry("a generate with no package", []string{"generate", "-out", ".", cleanDocument}),
	Entry("a generate with no output directory", []string{"generate", "-package", "p", cleanDocument}),
	Entry("a generate of two documents at once", []string{
		"generate", "-package", "p", "-out", ".", cleanDocument, wrongDocument,
	}),
)

var _ = Describe("Finding text", func() {
	It("counts one finding in the singular", func() {
		Expect(plural("finding", 1)).To(Equal("finding"))
		Expect(plural("finding", 2)).To(Equal("findings"))
	})
})
