ALTER TABLE brainspine_simulations
 ADD COLUMN managed BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN capture_every INTEGER NOT NULL DEFAULT 0 CHECK (capture_every BETWEEN 0 AND 10000),
 ADD COLUMN artifact_volume TEXT NOT NULL DEFAULT '',
 ADD COLUMN trace_url TEXT NOT NULL DEFAULT '',
 ADD COLUMN trace_export_error TEXT NOT NULL DEFAULT '',
 ADD COLUMN trace_retry_at TIMESTAMPTZ NOT NULL DEFAULT now();
