load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "config",
    srcs = [
        "environment.go",
        "origin.go",
        "provider_model.go",
        "refinement.go",
    ],
    importpath = "github.com/candacelabs/csf/pkg/config",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/liquidproto",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
    ],
)

go_test(
    name = "config_test",
    srcs = [
        "config_suite_test.go",
        "environment_test.go",
        "origin_test.go",
        "provider_model_test.go",
    ],
    deps = [
        ":config",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
