package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// These are table-driven standard-library tests rather than Ginkgo specs, for
// the reason ledger_test.go gives one directory over and for one more that is
// specific to this file. tools/ is a separate module so that a minifier's
// dependencies cannot reach a consumer's go.mod, and adding Ginkgo and Gomega
// here to say "given a struct field with no comment, it reports one finding"
// would widen the graph that module's own doc comment exists to keep narrow —
// and would do it to describe a pure function from a directory of source text
// to a list of findings, which is a table.
//
// The extra reason: this file is a gate's gate, and what it has to prove is
// that the checker goes RED, one row per shape of violation. That is the exact
// case a table expresses better than prose, because the interesting thing is
// the completeness of the enumeration rather than the story of any one row.

// pkgFile is a package that passes every rule, used as the base every mutation
// below is a change to.
const pkgFile = `// Package thing does one thing, and this sentence is its overview.
package thing

// Thing is the thing.
type Thing struct {
	// Name is what it is called.
	Name string

	Note string // Note is a trailing comment, which go doc renders as one.

	unexported string
}

// Do does it.
func (t Thing) Do() {}

// hidden is unexported, so its exported method is documentation with no
// reader: go doc drops both.
type hidden struct{}

// (deliberately no comment on the method below)
func (h hidden) Exported() {}

// The kinds, as a group. A group comment documents every name under it, which
// is what go doc renders for an iota enum.
const (
	KindA = 1
	KindB = 2
)

// Answer is the answer.
var Answer = 42

// Doer is something that does.
type Doer interface {
	// Do does it.
	Do()
}
`

// exampleFile is the package's runnable overview plus one named example.
const exampleFile = `package thing_test

// Example is the runnable overview.
func Example() {
	// Output:
	// ok
}

// ExampleThing_Do shows the method.
func ExampleThing_Do() {
	// Output:
	// done
}
`

const goMod = "module example.test\n\ngo 1.25.0\n"

// tree writes a fixture and returns its root. "go.mod" is supplied unless the
// case names its own, because the scope rules are decided by which go.mod is
// nearest and a fixture without one would be measured as a foreign module.
func tree(t *testing.T, files map[string]string) string {
	t.Helper()
	if _, ok := files["go.mod"]; !ok {
		files = withFile(files, "go.mod", goMod)
	}
	return writeTree(t, files)
}

// writeTree writes exactly what it is given, root go.mod included or not. The
// vacuity cases below need a tree with no published module in it at all.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("creating %s: %v", name, err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("writing %s: %v", name, err)
		}
	}
	return root
}

func withFile(files map[string]string, name, content string) map[string]string {
	out := make(map[string]string, len(files)+1)
	for k, v := range files {
		out[k] = v
	}
	out[name] = content
	return out
}

func check(t *testing.T, files map[string]string) *report {
	t.Helper()
	rep, err := run(tree(t, files))
	if err != nil {
		t.Fatalf("walking the fixture: %v", err)
	}
	return rep
}

func summarize(found []finding) string {
	var b strings.Builder
	for _, f := range found {
		b.WriteString("\n  " + f.String())
	}
	if b.Len() == 0 {
		return "\n  (none)"
	}
	return b.String()
}

// The shape that passes. If this ever goes red the table below stops meaning
// anything, because every row there is this fixture with one thing removed.
func TestAcceptsADocumentedPackage(t *testing.T) {
	rep := check(t, map[string]string{
		"thing/thing.go":           pkgFile,
		"thing/example_test.go":    exampleFile,
		"internal/inner/inner.go":  "// Package inner is internal.\npackage inner\n",
		"cmd/tool/main.go":         "// Command tool does a thing.\npackage main\n",
		"vendored/go.mod":          goMod,
		"vendored/other/other.go":  "package other\n\ntype Undocumented struct{ Field string }\n",
		"thing/gen/zz_gen.go":      "// Code generated by a generator - DO NOT EDIT.\n\npackage gen\n\ntype Undocumented struct{ Field string }\n",
		"thing/testdata/broken.go": "this is not go at all",
	})
	if len(rep.Findings) != 0 {
		t.Errorf("a fully documented tree was refused:%s", summarize(rep.Findings))
	}

	// The scope classification the whole argument rests on.
	scopes := map[string]scope{}
	generated := 0
	for _, p := range rep.Packages {
		scopes[p.Path] = p.Scope
		generated += p.Generated
	}
	for path, want := range map[string]scope{
		"thing":           scopeOverview,
		"internal/inner":  scopeLibrary,
		"cmd/tool":        scopeLibrary,
		"vendored/other":  scopeReported,
		"thing/gen":       scopeLibrary,
		"thing/testdata":  "", // testdata is not walked at all
		"nonexistent/pkg": "",
	} {
		if got := scopes[path]; got != want {
			t.Errorf("%s is scope %q, want %q", path, got, want)
		}
	}
	if generated != 1 {
		t.Errorf("skipped %d generated files, want 1", generated)
	}
}

// One row per shape of violation. Every one of these compiles, and every one
// of these would have shipped undocumented before this tool existed.
func TestRefusesEveryShapeOfMissingDoc(t *testing.T) {
	for _, tc := range []struct {
		name  string
		files map[string]string
		wants string
	}{
		{
			name:  "an exported func",
			files: map[string]string{"thing/thing.go": pkgFile + "\nfunc Undocumented() {}\n"},
			wants: "func Undocumented: is exported and has no doc comment",
		},
		{
			name:  "an exported method on an exported type",
			files: map[string]string{"thing/thing.go": pkgFile + "\nfunc (t Thing) Undocumented() {}\n"},
			wants: "method Thing.Undocumented: is exported and has no doc comment",
		},
		{
			name:  "an exported method on a generic exported type",
			files: map[string]string{"thing/thing.go": pkgFile + "\n// Box holds one.\ntype Box[T any] struct{}\n\nfunc (b Box[T]) Undocumented() {}\n"},
			wants: "method Box.Undocumented: is exported and has no doc comment",
		},
		{
			name:  "an exported type",
			files: map[string]string{"thing/thing.go": pkgFile + "\ntype Undocumented struct{}\n"},
			wants: "type Undocumented: is exported and has no doc comment",
		},
		{
			name:  "an exported struct field",
			files: map[string]string{"thing/thing.go": pkgFile + "\n// Box holds one.\ntype Box struct {\n\tUndocumented string\n}\n"},
			wants: "field Box.Undocumented: is exported and has no doc comment",
		},
		{
			name:  "an exported interface method",
			files: map[string]string{"thing/thing.go": pkgFile + "\n// Iface is an interface.\ntype Iface interface {\n\tUndocumented()\n}\n"},
			wants: "interface method Iface.Undocumented: is exported and has no doc comment",
		},
		{
			name:  "an exported const",
			files: map[string]string{"thing/thing.go": pkgFile + "\nconst Undocumented = 1\n"},
			wants: "const Undocumented: is exported and has no doc comment",
		},
		{
			name:  "an exported var",
			files: map[string]string{"thing/thing.go": pkgFile + "\nvar Undocumented = 1\n"},
			wants: "var Undocumented: is exported and has no doc comment",
		},
		{
			name:  "one bare name inside an otherwise documented group",
			files: map[string]string{"thing/thing.go": pkgFile + "\nconst (\n\t// Known is known.\n\tKnown = 1\n\n\tUndocumented = 2\n)\n"},
			wants: "const Undocumented: is exported and has no doc comment",
		},
		{
			name:  "a comment holding only a directive",
			files: map[string]string{"thing/thing.go": pkgFile + "\n//go:noinline\nfunc Undocumented() {}\n"},
			wants: "func Undocumented: is exported and has no doc comment",
		},
		{
			name:  "a package with no package comment",
			files: map[string]string{"quiet/quiet.go": "package quiet\n"},
			wants: "package quiet: has no package comment",
		},
		{
			name:  "a package comment that does not name the package",
			files: map[string]string{"quiet/quiet.go": "// This file holds some helpers.\npackage quiet\n"},
			wants: `does not open with "Package quiet"`,
		},
		{
			name: "a command whose comment does not name it",
			files: map[string]string{
				"thing/thing.go":        pkgFile,
				"thing/example_test.go": exampleFile,
				"cmd/tool/main.go":      "// Some helpers.\npackage main\n",
			},
			wants: `does not open with "Command "`,
		},
		{
			name: "a consumer-reachable package with no runnable overview",
			files: map[string]string{
				"thing/thing.go":        pkgFile,
				"thing/example_test.go": "package thing_test\n\n// ExampleThing_Do shows it.\nfunc ExampleThing_Do() {\n\t// Output:\n\t// done\n}\n",
			},
			wants: "its overview is not runnable",
		},
		{
			name: "a named Example that never runs, beside an overview that does",
			files: map[string]string{
				"thing/thing.go": pkgFile,
				"thing/example_test.go": "package thing_test\n\n// Example is the overview.\nfunc Example() {\n\t// Output:\n\t// ok\n}\n\n" +
					"// ExampleThing_Do shows the method.\nfunc ExampleThing_Do() {\n\tprintln(\"x\")\n}\n",
			},
			wants: "ExampleThing_Do: has no // Output: comment",
		},
		{
			name: "an Example anywhere in the tree that never runs",
			files: map[string]string{
				"thing/thing.go":         pkgFile,
				"thing/example_test.go":  exampleFile,
				"vendored/go.mod":        goMod,
				"vendored/v/v.go":        "// Package v is elsewhere.\npackage v\n",
				"vendored/v/ex_test.go":  "package v_test\n\n// ExampleThingElse compiles and never runs.\nfunc ExampleThingElse() {\n\tprintln(\"x\")\n}\n",
				"vendored/v/pad_test.go": "package v_test\n",
			},
			wants: "ExampleThingElse: has no // Output: comment",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rep := check(t, tc.files)
			if !strings.Contains(summarize(rep.Findings), tc.wants) {
				t.Errorf("the checker passed over %s\nwant a finding containing: %q\ngot:%s",
					tc.name, tc.wants, summarize(rep.Findings))
			}
		})
	}
}

// The "a package-level Example that never runs" row above asserts that the
// OVERVIEW rule fires. This asserts the other half of the same fixture: an
// Example with no // Output: is itself a finding, wherever it sits, because an
// example go test compiles and never executes is FR-68's exact failure.
func TestRefusesAnExampleWithNoOutput(t *testing.T) {
	rep := check(t, map[string]string{
		"thing/thing.go":        pkgFile,
		"thing/example_test.go": "package thing_test\n\n// Example is the overview.\nfunc Example() {\n\tprintln(\"x\")\n}\n",
	})
	got := summarize(rep.Findings)
	for _, want := range []string{
		"example Example: has no // Output: comment",
		"its overview is not runnable",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("want a finding containing %q, got:%s", want, got)
		}
	}
}

// An empty // Output: is a running example: go test expects no output and
// executes the function to find out. Refusing it would push authors towards
// printing something they do not care about.
func TestAcceptsAnEmptyOutputComment(t *testing.T) {
	rep := check(t, map[string]string{
		"thing/thing.go":        pkgFile,
		"thing/example_test.go": "package thing_test\n\n// Example is the overview.\nfunc Example() {\n\t// Output:\n}\n",
	})
	if len(rep.Findings) != 0 {
		t.Errorf("an example with an empty // Output: was refused:%s", summarize(rep.Findings))
	}
}

// The scope decision, stated as behaviour rather than as a paragraph. A module
// that is not the published one is measured and printed, and its undocumented
// symbols do not fail the build — but rule 4 still does, because an example
// that never runs costs the same wherever it sits.
func TestScopeEnforcesTheLibraryAndReportsTheRest(t *testing.T) {
	rep := check(t, map[string]string{
		"thing/thing.go":        pkgFile,
		"thing/example_test.go": exampleFile,
		"apps/demo/go.mod":      goMod,
		"apps/demo/demo.go":     "// Package demo is its own module.\npackage demo\n\ntype Undocumented struct{ Field string }\n",
	})
	if len(rep.Findings) != 0 {
		t.Errorf("a separate module's undocumented symbols failed the build:%s", summarize(rep.Findings))
	}
	got := summarize(rep.Reported)
	for _, want := range []string{"type Undocumented", "field Undocumented.Field"} {
		if !strings.Contains(got, want) {
			t.Errorf("a separate module's undocumented symbols were not reported at all: want %q, got:%s", want, got)
		}
	}

	var reported *pkgReport
	for i := range rep.Packages {
		if rep.Packages[i].Path == "apps/demo" {
			reported = &rep.Packages[i]
		}
	}
	if reported == nil {
		t.Fatalf("apps/demo is missing from the report entirely; the count would be invisible")
	}
	if reported.Undocumented != 2 {
		t.Errorf("apps/demo reports %d undocumented symbols, want 2", reported.Undocumented)
	}
}

// The way this gate would become a check that cannot fail: point it somewhere
// that holds nothing it enforces, and it prints an empty table and exits 0.
// Each of these is an error rather than a clean report.
func TestRefusesATreeItWouldPassVacuously(t *testing.T) {
	for _, tc := range []struct {
		name  string
		files map[string]string
		wants string
	}{
		{
			name:  "no Go package at all",
			files: map[string]string{"README.md": "nothing here compiles\n"},
			wants: "holds no Go package at all",
		},
		{
			// Every package below sits in a nested module. This is what a
			// wrong -root looks like.
			name: "no package of the published library",
			files: map[string]string{
				"apps/demo/go.mod":  goMod,
				"apps/demo/demo.go": "// Package demo is its own module.\npackage demo\n",
			},
			wants: "holds no package of the published library",
		},
		{
			name: "nothing a consumer can import",
			files: map[string]string{
				"go.mod":                  goMod,
				"internal/inner/inner.go": "// Package inner is internal.\npackage inner\n",
			},
			wants: "holds no consumer-reachable package",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := run(writeTree(t, tc.files))
			if err == nil {
				t.Fatalf("a tree holding nothing this gate enforces was reported clean")
			}
			if !strings.Contains(err.Error(), tc.wants) {
				t.Errorf("error does not say what is wrong\n got: %v\nwant it to contain: %q", err, tc.wants)
			}
		})
	}
}

// A stale exception is a finding. A permission nobody is using reads, to the
// next person, as a rule that was relaxed for a reason.
func TestRefusesAStaleNonRunnableException(t *testing.T) {
	nonRunnableExamples["thing.ExampleGone"] = "a reason that expired"
	t.Cleanup(func() { delete(nonRunnableExamples, "thing.ExampleGone") })

	rep := check(t, map[string]string{
		"thing/thing.go":        pkgFile,
		"thing/example_test.go": exampleFile,
	})
	if !strings.Contains(summarize(rep.Findings), "thing.ExampleGone") {
		t.Errorf("an exception naming an example that does not exist was accepted:%s", summarize(rep.Findings))
	}
}

// The tree CI actually walks, walked by the code that walks it. A layout
// change this tool cannot follow — a new module, a package moving out of
// internal/ — is a change that must fail here rather than in a CI log a week
// later.
func TestWalksTheCommittedTree(t *testing.T) {
	rep, err := run(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("the committed tree is unwalkable: %v", err)
	}

	scopes := map[string]scope{}
	generated := 0
	for _, p := range rep.Packages {
		scopes[p.Path] = p.Scope
		generated += p.Generated
	}
	// examples/* is not in this map because it is not in this tree: the three
	// example applications live at candace/examples/gotth/, and the invocation
	// that covers them is the one TestWalksTheExamplesToo makes.
	for path, want := range map[string]scope{
		"live":                         scopeOverview,
		"live/livetest":                scopeOverview,
		"internal/session":             scopeLibrary,
		"internal/wsx":                 scopeLibrary,
		"docs/guide/_samples":          scopeReported,
		"bench/apps/chat/gotth":        scopeReported,
		"test/routers":                 scopeReported,
		"tools/doccheck":               scopeReported,
		"internal/cmd/gen-clientcodec": scopeLibrary,
	} {
		if got := scopes[path]; got != want {
			t.Errorf("%s is scope %q, want %q", path, got, want)
		}
	}
	if generated == 0 {
		t.Error("no generated file was skipped; the marker match has stopped working, " +
			"and the next gen.sh run would then be asked for doc comments it cannot keep")
	}
}

// The second tree CI walks, and the scope it is walked at.
//
// The examples were their own modules and landed in scopeReported; they moved
// out of the library tree and, for one landing, out of this gate altogether.
// This asserts both halves of the repair: they are seen, and they are seen at
// the scope they always had — rule 4 enforced, rules 1 to 3 not, because their
// exported identifiers are JSON payload fields rather than an author's API.
func TestWalksTheExamplesToo(t *testing.T) {
	examples := filepath.Join("..", "..", "..", "..", "examples", "gotth")
	rep, err := runAll([]treeRoot{
		{Path: filepath.Join("..", "..")},
		{Path: examples, Reported: true},
	})
	if err != nil {
		t.Fatalf("the committed trees are unwalkable: %v", err)
	}

	seen := map[string]scope{}
	for _, p := range rep.Packages {
		seen[filepath.ToSlash(p.Path)] = p.Scope
	}
	prefix := filepath.ToSlash(filepath.Clean(examples))
	for _, app := range []string{"counter", "chat", "dashboard"} {
		path := prefix + "/" + app
		got, walked := seen[path]
		if !walked {
			t.Errorf("%s was not walked; the examples are outside this gate again", path)
			continue
		}
		if got != scopeReported {
			t.Errorf("%s is scope %q, want %q", path, got, scopeReported)
		}
	}
	// And the library is still in the same report, at its own scope, so one
	// invocation covers both trees.
	if got := seen[filepath.ToSlash(filepath.Join("..", "..", "live"))]; got != scopeOverview {
		t.Errorf("the library tree is scope %q, want %q", got, scopeOverview)
	}
}

// A reported root is measured, and rule 4 is the one rule that still fails it.
// The whole point of walking those trees is that an Example with no Output
// compiles, never runs, and would otherwise pass.
func TestAReportedRootEnforcesRule4AndNothingElse(t *testing.T) {
	lib := tree(t, map[string]string{
		"thing/thing.go":        pkgFile,
		"thing/example_test.go": exampleFile,
	})
	reported := writeTree(t, map[string]string{
		"app/main.go":         "package main\n\ntype Wire struct {\n\tHTML string\n}\n\nfunc main() {}\n",
		"app/example_test.go": "package main\n\nfunc ExampleWire() {\n}\n",
	})

	rep, err := runAll([]treeRoot{{Path: lib}, {Path: reported, Reported: true}})
	if err != nil {
		t.Fatalf("walking the fixtures: %v", err)
	}

	enforced := summarize(rep.Findings)
	if !strings.Contains(enforced, "ExampleWire") {
		t.Errorf("an example with no // Output: in a reported root was not enforced:%s", enforced)
	}
	for _, unwanted := range []string{"Wire.HTML", "package main", "has no package comment"} {
		if strings.Contains(enforced, unwanted) {
			t.Errorf("rules 1 to 3 were enforced on a reported root (%q):%s", unwanted, enforced)
		}
	}
	if !strings.Contains(summarize(rep.Reported), "Wire.HTML") {
		t.Errorf("the reported root was not MEASURED; it has to be printed, not dropped:%s",
			summarize(rep.Reported))
	}
}

// A reported root that resolves to nothing is this tool's own recurring
// failure: a walk that finds nothing prints an empty table and exits 0. It is
// exactly how the examples went unchecked, so it is an error rather than a
// clean report.
func TestRefusesAReportedRootThatHoldsNoPackage(t *testing.T) {
	lib := tree(t, map[string]string{
		"thing/thing.go":        pkgFile,
		"thing/example_test.go": exampleFile,
	})
	empty := writeTree(t, map[string]string{"README.md": "nothing here compiles\n"})

	_, err := runAll([]treeRoot{{Path: lib}, {Path: empty, Reported: true}})
	if err == nil {
		t.Fatal("a reported root holding no Go package was accepted")
	}
	if !strings.Contains(err.Error(), "holds no Go package at all") {
		t.Errorf("error does not say what is wrong: %v", err)
	}
}

// Two roots have to be told apart in the report, or two packages called
// "counter" are one line and a finding names a file the reader cannot open.
func TestMultipleRootsArePrefixedByTheirTree(t *testing.T) {
	lib := tree(t, map[string]string{
		"thing/thing.go":        pkgFile,
		"thing/example_test.go": exampleFile,
	})
	other := writeTree(t, map[string]string{"thing/thing.go": pkgFile})

	rep, err := runAll([]treeRoot{{Path: lib}, {Path: other, Reported: true}})
	if err != nil {
		t.Fatalf("walking the fixtures: %v", err)
	}
	paths := map[string]bool{}
	for _, p := range rep.Packages {
		paths[filepath.ToSlash(p.Path)] = true
	}
	for _, want := range []string{
		filepath.ToSlash(filepath.Join(lib, "thing")),
		filepath.ToSlash(filepath.Join(other, "thing")),
	} {
		if !paths[want] {
			t.Errorf("%s is missing from the report; the two trees collided", want)
		}
	}
	// And a single root is unprefixed, exactly as it always printed.
	single, err := run(lib)
	if err != nil {
		t.Fatalf("walking one tree: %v", err)
	}
	for _, p := range single.Packages {
		if filepath.ToSlash(p.Path) != "thing" {
			t.Errorf("a single-root run printed %q, want %q", p.Path, "thing")
		}
	}
}
