load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "work",
    srcs = [
        "work.pb.go",
        "work_liquid.pb.go",
    ],
    importpath = "github.com/candacelabs/csf/proto/candace/work/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/liquidproto",
        "//pkg/liquidproto/v1:liquidproto",
        "//proto/candace/telemetry/v1:telemetry",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
