// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: candace/work/v1/work.proto

package workv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/csf/pkg/liquidproto"
	regexp "regexp"
)

var (
	_liquidEvidenceUrlRe0               = regexp.MustCompile("^https?://[^ ]+$")
	_liquidCheckpointIdRe0              = regexp.MustCompile("^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
	_liquidCheckpointTaskUrlRe0         = regexp.MustCompile("^https://github.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/issues/[1-9][0-9]*$")
	_liquidCheckpointRevisionRe0        = regexp.MustCompile("^[a-f0-9]{40}$")
	_liquidCheckpointTaskFingerprintRe0 = regexp.MustCompile("^[a-f0-9]{64}$")
	_liquidTicketDependencyIssueUrlRe0  = regexp.MustCompile("^https://github.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/issues/[1-9][0-9]*$")
	_liquidTicketSpecRepositoryRe0      = regexp.MustCompile("^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*$")
	_liquidTicketSpecTitleRe0           = regexp.MustCompile("[^\\s]")
	_liquidTicketSpecTitleRe1           = regexp.MustCompile("[\\r\\n]")
	_liquidTicketSpecGoalRe0            = regexp.MustCompile("[^\\s]")
)

// ValidateEvidence checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateEvidence(message *Evidence) error {
	if message == nil {
		return fmt.Errorf("ValidateEvidence: nil *Evidence")
	}
	if !(len(message.Description) >= 1 && len(message.Description) <= 4096) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Evidence",
			Field:     "description",
			Predicate: "len(this) >= 1 && len(this) <= 4096",
			Value:     message.Description,
		}
	}
	if !(_liquidEvidenceUrlRe0.MatchString(message.Url)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Evidence",
			Field:     "url",
			Predicate: "matches(this, `^https?://[^ ]+$`)",
			Value:     message.Url,
		}
	}
	if !(len(message.Result) >= 1 && len(message.Result) <= 4096) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Evidence",
			Field:     "result",
			Predicate: "len(this) >= 1 && len(this) <= 4096",
			Value:     message.Result,
		}
	}
	return nil
}

// ValidateCheckpoint checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateCheckpoint(message *Checkpoint) error {
	if message == nil {
		return fmt.Errorf("ValidateCheckpoint: nil *Checkpoint")
	}
	if !(message.SchemaVersion == 1) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Checkpoint",
			Field:     "schema_version",
			Predicate: "this == 1",
			Value:     message.SchemaVersion,
		}
	}
	if !(_liquidCheckpointIdRe0.MatchString(message.Id)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Checkpoint",
			Field:     "id",
			Predicate: "matches(this, `^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$`)",
			Value:     message.Id,
		}
	}
	if !(_liquidCheckpointTaskUrlRe0.MatchString(message.TaskUrl)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Checkpoint",
			Field:     "task_url",
			Predicate: "matches(this, `^https://github.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/issues/[1-9][0-9]*$`)",
			Value:     message.TaskUrl,
		}
	}
	if !(_liquidCheckpointRevisionRe0.MatchString(message.Revision)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Checkpoint",
			Field:     "revision",
			Predicate: "matches(this, `^[a-f0-9]{40}$`)",
			Value:     message.Revision,
		}
	}
	if !(len(message.Owner) >= 1 && len(message.Owner) <= 128) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Checkpoint",
			Field:     "owner",
			Predicate: "len(this) >= 1 && len(this) <= 128",
			Value:     message.Owner,
		}
	}
	if !(len(message.NextAction) >= 1 && len(message.NextAction) <= 8192) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Checkpoint",
			Field:     "next_action",
			Predicate: "len(this) >= 1 && len(this) <= 8192",
			Value:     message.NextAction,
		}
	}
	if !(_liquidCheckpointTaskFingerprintRe0.MatchString(message.TaskFingerprint)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.Checkpoint",
			Field:     "task_fingerprint",
			Predicate: "matches(this, `^[a-f0-9]{64}$`)",
			Value:     message.TaskFingerprint,
		}
	}
	return nil
}

// ValidateTicketDependency checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateTicketDependency(message *TicketDependency) error {
	if message == nil {
		return fmt.Errorf("ValidateTicketDependency: nil *TicketDependency")
	}
	if !(_liquidTicketDependencyIssueUrlRe0.MatchString(message.IssueUrl)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.TicketDependency",
			Field:     "issue_url",
			Predicate: "matches(this, `^https://github.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/issues/[1-9][0-9]*$`)",
			Value:     message.IssueUrl,
		}
	}
	if !(message.Condition == 1 || message.Condition == 2 || message.Condition == 3) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.TicketDependency",
			Field:     "condition",
			Predicate: "this == 1 || this == 2 || this == 3",
			Value:     message.Condition,
		}
	}
	return nil
}

// ValidateTicketSpec checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateTicketSpec(message *TicketSpec) error {
	if message == nil {
		return fmt.Errorf("ValidateTicketSpec: nil *TicketSpec")
	}
	if !(message.SchemaVersion == 1) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.TicketSpec",
			Field:     "schema_version",
			Predicate: "this == 1",
			Value:     message.SchemaVersion,
		}
	}
	if !(_liquidTicketSpecRepositoryRe0.MatchString(message.Repository)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.TicketSpec",
			Field:     "repository",
			Predicate: "matches(this, `^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*$`)",
			Value:     message.Repository,
		}
	}
	if !(len(message.Title) >= 1 && len(message.Title) <= 256 && _liquidTicketSpecTitleRe0.MatchString(message.Title) && !_liquidTicketSpecTitleRe1.MatchString(message.Title)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.TicketSpec",
			Field:     "title",
			Predicate: "len(this) >= 1 && len(this) <= 256 && matches(this, `[^\\s]`) && !matches(this, `[\\r\\n]`)",
			Value:     message.Title,
		}
	}
	if !(len(message.Goal) >= 1 && len(message.Goal) <= 8192 && _liquidTicketSpecGoalRe0.MatchString(message.Goal)) {
		return &liquidproto.Error{
			Message:   "candace.work.v1.TicketSpec",
			Field:     "goal",
			Predicate: "len(this) >= 1 && len(this) <= 8192 && matches(this, `[^\\s]`)",
			Value:     message.Goal,
		}
	}
	return nil
}
