let expect message condition = if not condition then failwith message

let candace_header = "// Code generated by Candacegen csfc. DO NOT EDIT.\n"
let upstream_header producer = "// Code generated by " ^ producer ^ ". DO NOT EDIT.\n"

let clean path source =
  expect (path ^ ": unexpected generated-file finding")
    (Generated_policy.inspect ~path ~source = [])

let rejected path source code =
  match Generated_policy.inspect ~path ~source with
  | [diagnostic] ->
      expect (path ^ ": wrong diagnostic code") (diagnostic.Model.code = code);
      expect (path ^ ": wrong diagnostic location")
        (diagnostic.at = { Model.file = path; line = 1; column = 1 })
  | _ -> failwith (path ^ ": expected one generated-file finding")

let test_owned_output () =
  let configured = Codegen_header.render Codegen_header.Ocaml in
  clean "architecture_cgen.ml" configured;
  rejected "architecture.ml" configured "CSF_GENERATED_NAME";
  List.iter (fun extension ->
    clean ("generated/model_cgen" ^ extension) candace_header;
    rejected ("generated/model" ^ extension) candace_header "CSF_GENERATED_NAME";
    rejected ("generated/model_cgen" ^ extension) "" "CSF_GENERATED_HEADER")
    [".go"; ".py"; ".cc"; ".cpp"; ".h"; ".rs"; ".ml"];
  clean "architecture_cgen.ml" "(* Code generated by Candacegen csfc. DO NOT EDIT. *)\n";
  clean "model_cgen.go" "// Code generated by Candacegen. DO NOT EDIT.\n";
  rejected "model_cgen.ml" "(* Code generated by Candacegen csfc. *)" "CSF_GENERATED_HEADER";
  rejected "model_cgen.ml" "(* DO NOT EDIT. *)" "CSF_GENERATED_HEADER";
  clean "ordinary.ml" "";
  clean "README_cgen.md" "";
  clean "README.md" candace_header

let test_upstream_names () =
  List.iter (fun (path, producer) -> clean path (upstream_header producer)) [
    "model.pb.go", "protoc-gen-go";
    "model_liquid.pb.go", "protoc-gen-liquidproto";
    "db.go", "sqlc";
    "api.gen.go", "MockGen";
    "model_pb2.py", "the protocol buffer compiler";
  ];
  rejected "model_cgen.go" (upstream_header "protoc-gen-go") "CSF_GENERATED_OWNER";
  rejected "model_cgen.ml" (upstream_header "Other") "CSF_GENERATED_OWNER";
  rejected "model.pb.go" candace_header "CSF_GENERATED_NAME";
  rejected "model_cgen.pb.go" candace_header "CSF_GENERATED_NAME";
  rejected "directory_cgen/model.ml" candace_header "CSF_GENERATED_NAME"

let test_header_boundaries () =
  rejected "model_cgen.ml" (upstream_header (Codegen_header.generator_name ^ "Extra")) "CSF_GENERATED_OWNER";
  rejected "model_cgen.ml" (upstream_header "CandacegenExtra") "CSF_GENERATED_OWNER";
  rejected "model_cgen.ml" "ungenerated by Candacegen. DO NOT EDIT." "CSF_GENERATED_OWNER";
  rejected "model_cgen.ml" "Generated by Candacegen. DO NOT EDIT." "CSF_GENERATED_OWNER";
  rejected "model_cgen.ml" (String.make Generated_policy.header_prefix_bytes ' ' ^ candace_header) "CSF_GENERATED_HEADER";
  clean "model.ml" (String.make Generated_policy.header_prefix_bytes ' ' ^ candace_header);
  let padding = String.make (Generated_policy.header_prefix_bytes - String.length candace_header) ' ' in
  clean "model_cgen.ml" (padding ^ candace_header ^ "outside header");
  rejected "model_cgen.ml" "// Code generated by Candacegen. do not edit." "CSF_GENERATED_HEADER"

let () =
  test_owned_output ();
  test_upstream_names ();
  test_header_boundaries ();
  print_endline "CSF generated-file policy tests passed"
