(** [_cgen] denotes an artifact emitted by the project-owned CandaceCodegen
    tooling (historically called Candacegen).
    Edit its source definition or generator, then regenerate. The suffix does
    not mean "written by an AI", and upstream generators keep their own naming
    conventions, such as protobuf's [.pb.go]. *)

(* Inspect only the leading KiB: generated disclaimers belong in the header,
   and checking a large generated file must not require reading its body. *)
let header_prefix_bytes = 1024

let checked_extension = function
  | ".go" | ".py" | ".cc" | ".cpp" | ".h" | ".rs" | ".ml" -> true
  | _ -> false

let word_character = function
  | 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' -> true
  | _ -> false

let contains ?(whole_words = false) text phrase =
  let length = String.length phrase in
  let boundary index = index < 0 || index >= String.length text || not (word_character text.[index]) in
  let rec search index =
    index + length <= String.length text &&
    ((String.sub text index length = phrase &&
      (not whole_words || (boundary (index - 1) && boundary (index + length)))) || search (index + 1)) in
  search 0

let diagnostic path code message =
  { Model.at = { file = path; line = 1; column = 1 }; code; message }

(* Ownership comes from the header convention, not merely from the extension.
   An upstream foo.pb.go remains foo.pb.go. Our foo_cgen.go must name
   its generator and prohibit editing in its header. This is a convention check,
   not proof that the file was produced by that generator or is up to date. *)
let inspect ~path ~source =
  if not (checked_extension (Filename.extension path)) then []
  else
    let header = String.sub source 0 (min header_prefix_bytes (String.length source)) in
    let generated = contains (String.lowercase_ascii header) "generated" && contains header "DO NOT EDIT" in
    (* Keep the old identity for generators outside this compiler's migration. *)
    let owned = List.exists (contains ~whole_words:true header)
      ["generated by " ^ Codegen_header.generator_name; "generated by Candacegen"] in
    let stem = Filename.remove_extension (Filename.basename path) in
    let named = Filename.check_suffix stem "_cgen" in
    if owned && not named then
      [diagnostic path "CSF_GENERATED_NAME" "CandaceCodegen output requires _cgen suffix"]
    else if named && not generated then
      [diagnostic path "CSF_GENERATED_HEADER" "CandaceCodegen output requires generated-code disclaimer"]
    else if named && generated && not owned then
      [diagnostic path "CSF_GENERATED_OWNER" "preserve upstream generator naming; _cgen is only for CandaceCodegen"]
    else []
