(* Build-time projection of the executable Extended Backus-Naur Form (EBNF)
   grammar's vocabulary into OCaml variants.
   Model remains the handwritten semantic contract; this generator produces the
   grammar-to-Model names that the OCaml compiler can check against that contract.
   Adding a grammar keyword therefore requires regeneration, not a second manual
   keyword table in the decoder. *)
module Grammar = Frontend_grammar

type symbol = { spelling : string; constructor : string; at : Model.location }

let word_tail = function
  | 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' | '\'' -> true
  | _ -> false

let identifier first name =
  String.length name > 0 && first name.[0] && String.for_all word_tail name

(* OCaml 5.3 binding/type keywords; these belong to the emitted language,
   independently of the architecture grammar's terminal vocabulary. *)
let reserved_identifier = function
  | "and" | "as" | "assert" | "asr" | "begin" | "class" | "constraint"
  | "do" | "done" | "downto" | "effect" | "else" | "end" | "exception"
  | "external" | "false" | "for" | "fun" | "function" | "functor" | "if"
  | "in" | "include" | "inherit" | "initializer" | "land" | "lazy" | "let"
  | "lor" | "lsl" | "lsr" | "lxor" | "match" | "method" | "mod" | "module"
  | "mutable" | "new" | "nonrec" | "object" | "of" | "open" | "or" | "private"
  | "rec" | "sig" | "struct" | "then" | "to" | "true" | "try" | "type"
  | "val" | "virtual" | "when" | "while" | "with" -> true
  | _ -> false

let symbol_error at code message = Frontend_lexer.fail at code message

let make_symbol at spelling constructor =
  if not (identifier (function 'A' .. 'Z' -> true | _ -> false) constructor) then
    symbol_error at "CSF_SYMBOL_NAME"
      (Printf.sprintf "%S does not produce a valid OCaml constructor: %S" spelling constructor);
  { spelling; constructor; at }

let terminal_constructor = function
  | "->" -> "Arrow"
  | ";" -> "Semicolon"
  | "{" -> "LeftBrace"
  | "}" -> "RightBrace"
  | text when Frontend_lexer.is_word text -> String.capitalize_ascii text
  | "" -> "Symbol_Empty"
  | text ->
      let bytes = String.to_seq text |> List.of_seq in
      "Symbol_" ^ String.concat "_" (List.map (fun byte -> Printf.sprintf "%02X" (Char.code byte)) bytes)

(* Capitalization and punctuation naming must stay injective within a namespace.
   Reject collisions rather than inventing suffixes that would make decoder
   constructors depend on unrelated additions to the grammar. *)
let check_collisions namespace symbols =
  let names = Hashtbl.create (List.length symbols) in
  List.iter (fun symbol ->
    match Hashtbl.find_opt names symbol.constructor with
    | Some previous -> symbol_error symbol.at "CSF_SYMBOL_COLLISION"
        (Printf.sprintf "%s constructor %s maps both %S and %S"
           namespace symbol.constructor previous symbol.spelling)
    | None -> Hashtbl.add names symbol.constructor symbol.spelling) symbols

(* Hash-table iteration is not an output order. Sorting at the projection
   boundary keeps generated bytes stable across runs and declaration reorderings
   that leave the vocabulary unchanged. *)
let ordered_rules grammar =
  Hashtbl.to_seq_values grammar.Grammar.rules |> List.of_seq
  |> List.sort (fun (left : Grammar.rule) right -> String.compare left.name right.name)

let rule_symbols rules at =
  let declared = List.map (fun (rule : Grammar.rule) ->
    make_symbol rule.at rule.name (String.capitalize_ascii rule.name)) rules in
  let builtins = List.map (fun name -> make_symbol at name (String.capitalize_ascii name))
    Grammar.builtin_names in
  make_symbol at "$terminal" "Terminal" :: builtins @ declared
  |> List.sort (fun left right -> String.compare left.spelling right.spelling)

let terminal_symbols rules grammar =
  let locations = Hashtbl.create 64 in
  List.iter (fun (rule : Grammar.rule) -> Grammar.visit (function
    | Grammar.Terminal spelling when not (Hashtbl.mem locations spelling) ->
        Hashtbl.add locations spelling rule.at
    | _ -> ()) rule.body) rules;
  List.map (fun spelling -> make_symbol (Hashtbl.find locations spelling)
    spelling (terminal_constructor spelling)) grammar.Grammar.terminals

(* [name] recovers source spelling; [constructor_name] supplies OCaml spelling
   for typed projections. [%S] escapes source strings as valid OCaml literals.
   For an empty variant, the emitted [_ -> .] is OCaml's refutation case: no
   value can reach it, so an arbitrary fallback string would hide the invariant. *)
let emit_enum output namespace symbols =
  Printf.bprintf output "module %s = struct\n  type t =\n" namespace;
  if symbols = [] then Buffer.add_string output "    |\n";
  List.iter (fun symbol -> Printf.bprintf output "    | %s\n" symbol.constructor) symbols;
  Buffer.add_string output "\n  let of_string : string -> t option = function\n";
  List.iter (fun symbol -> Printf.bprintf output "    | %S -> Some %s\n"
    symbol.spelling symbol.constructor) symbols;
  Buffer.add_string output "    | _ -> None\n\n  let name : t -> string = function\n";
  List.iter (fun symbol -> Printf.bprintf output "    | %s -> %S\n"
    symbol.constructor symbol.spelling) symbols;
  if symbols = [] then Buffer.add_string output "    | _ -> .\n";
  Buffer.add_string output "\n  let constructor_name : t -> string = function\n";
  List.iter (fun symbol -> Printf.bprintf output "    | %s -> %S\n"
    symbol.constructor symbol.constructor) symbols;
  if symbols = [] then Buffer.add_string output "    | _ -> .\n";
  Buffer.add_string output "end\n\n"

(* Only literal-only choices declare enum mappings. For example,
   state = "existing" | "planned" maps Terminal.Existing to Model.Existing.
   A sequence or reference has structural meaning and is left to Decode rather
   than guessed to be a Model enum. *)
let rec enum_terminals = function
  | Grammar.Terminal terminal -> Some [terminal]
  | Grammar.Choice choices ->
      let branches = List.map enum_terminals choices in
      if List.for_all Option.is_some branches then Some (List.concat_map Option.get branches)
      else None
  | Grammar.Reference _ | Grammar.Sequence _ | Grammar.Optional _ | Grammar.Repeat _ -> None

(* Convention: the rule names a Model type and its terminals name constructors.
   Missing types/constructors fail when generated OCaml compiles. The inverse
   mapping's [@warning "@8"] also makes non-exhaustiveness an error: adding a
   Model constructor without a matching grammar alternative cannot pass quietly. *)
let emit_mapping output (rule : Grammar.rule) terminals =
  if reserved_identifier rule.name ||
     not (identifier (function 'a' .. 'z' | '_' -> true | _ -> false) rule.name) then
    symbol_error rule.at "CSF_SYMBOL_NAME"
      (Printf.sprintf "enum rule %S must name an unreserved OCaml value and Model type" rule.name);
  let terminals = List.sort_uniq String.compare terminals in
  Printf.bprintf output "let %s : Terminal.t -> Model.%s option = function\n" rule.name rule.name;
  List.iter (fun terminal ->
    let constructor = terminal_constructor terminal in
    Printf.bprintf output "  | Terminal.%s -> Some Model.%s\n" constructor constructor) terminals;
  Buffer.add_string output "  | _ -> None\n\n";
  Printf.bprintf output "let[@warning \"@8\"] %s_terminal : Model.%s -> Terminal.t = function\n" rule.name rule.name;
  List.iter (fun terminal ->
    let constructor = terminal_constructor terminal in
    Printf.bprintf output "  | Model.%s -> Terminal.%s\n" constructor constructor) terminals;
  Buffer.add_char output '\n'

let check_mapping_names mappings =
  let names = Hashtbl.create 16 in
  List.iter (fun ((rule : Grammar.rule), _) ->
    List.iter (fun name -> match Hashtbl.find_opt names name with
      | Some previous -> symbol_error rule.at "CSF_SYMBOL_COLLISION"
          (Printf.sprintf "generated value %S is owned by enum rules %S and %S" name previous rule.name)
      | None -> Hashtbl.add names name rule.name)
      [rule.name; rule.name ^ "_terminal"]) mappings

let generate ~grammar =
  try
    let grammar = Grammar.parse ~filename:"<grammar>" grammar in
    let rules = ordered_rules grammar in
    let at = (Hashtbl.find grammar.rules grammar.start).Grammar.at in
    let rule_symbols = rule_symbols rules at in
    let terminal_symbols = terminal_symbols rules grammar in
    let mappings = List.filter_map (fun (rule : Grammar.rule) ->
      Option.map (fun terminals -> rule, terminals) (enum_terminals rule.body)) rules in
    check_collisions "Rule" rule_symbols;
    check_collisions "Terminal" terminal_symbols;
    check_mapping_names mappings;
    let output = Buffer.create 4096 in
    Buffer.add_string output (Codegen_header.render Codegen_header.Ocaml ^ "\n");
    emit_enum output "Rule" rule_symbols;
    emit_enum output "Terminal" terminal_symbols;
    List.iter (fun (rule, terminals) -> emit_mapping output rule terminals) mappings;
    Ok (Buffer.contents output)
  with Frontend_lexer.Error diagnostic -> Error [diagnostic]
