// Code generated by pkg/widget/internal/uigen from the RelayPipeline widget document. DO NOT EDIT.

// Package relaypipeline is the generated RelayPipeline widget.
//
// Edit the widget document and regenerate; edits here are overwritten.
package relaypipeline

import (
	"context"
	"strconv"

	"github.com/a-h/templ"

	"github.com/candacelabs/csf/pkg/gotth/live"
	"github.com/candacelabs/csf/pkg/widget"
)

// This widget's identity. The region is the only one that crosses the wire: a
// patch names it, so changing it is a client-visible change. The palette is a
// name a host resolves to values; this widget carries no colour of its own.
// The title id is what the widget's landmark is labelled by.
const (
	RelayPipelineName    = "RelayPipeline"
	RelayPipelineRegion  = "widget.relay-pipeline"
	RelayPipelinePalette = "fieldStation"
	RelayPipelineTitleID = "widget.relay-pipeline-title"
)

// The wire names this widget accepts. The set is exhaustive and default-deny:
// a name absent from the registration is refused before any reducer runs.
const (
	RelayPipelineEventAdvance = "widget.relay.advance"
)

// The wire field names each event carries. They are the other half of an
// event's contract: the widget reads these out of a delivery, and whatever
// produced the delivery wrote them in. Registration.Payloads carries the same
// names as data, for a host that fills an event it cannot name at compile time.
const (
	RelayPipelineEventAdvanceFieldCursor    = "cursor"
	RelayPipelineEventAdvanceFieldIngressUp = "ingress_up"
	RelayPipelineEventAdvanceFieldRelayUp   = "relay_up"
	RelayPipelineEventAdvanceFieldSinkUp    = "sink_up"
	RelayPipelineEventAdvanceFieldBacklog   = "backlog"
)

// RelayPipelineState is this widget's own state, and the type argument every
// method below is written in. The host holds it without knowing it; nothing
// in this file asserts it back, because nothing in this file ever loses it.
type RelayPipelineState struct {
	// Cursor is the "cursor" state field, declared type counter.
	Cursor uint64

	// IngressUp is the "ingressUp" state field, declared type flag.
	IngressUp bool

	// RelayUp is the "relayUp" state field, declared type flag.
	RelayUp bool

	// SinkUp is the "sinkUp" state field, declared type flag.
	SinkUp bool

	// Backlog is the "backlog" state field, declared type count.
	Backlog int64

	// Slow is the "slow" state field, declared type flag.
	Slow bool
}

// RelayPipeline is the generated RelayPipeline widget.
//
// I is the HOST's identity type, threaded through and never read: a widget
// document names no host, no address and no credential, so nothing here can
// look at an identity. It is a type parameter because the SDK's contract
// carries one — live.Session stopped erasing the application's identity type
// on 2026-09-03 — and a generated widget must fit whatever host registers it.
type RelayPipeline[I live.IIdentity] struct {
	region string
}

// NewRelayPipeline returns the widget a host registers, instantiated on that
// host's own identity type.
func NewRelayPipeline[I live.IIdentity]() *RelayPipeline[I] {
	return NewRelayPipelineAt[I](RelayPipelineRegion)
}

// NewRelayPipelineAt gives one instance its host-assigned region. The host validates
// region syntax and uniqueness when assembling its live configuration.
func NewRelayPipelineAt[I live.IIdentity](region string) *RelayPipeline[I] {
	return &RelayPipeline[I]{region: region}
}

// The contract, asserted at one instantiation. Anonymous is the identity a
// host with no accounts uses, and any other I satisfies the same interfaces:
// nothing below branches on it.
var (
	_ widget.IWidget[RelayPipelineState, live.AnonymousIdentity] = (*RelayPipeline[live.AnonymousIdentity])(nil)
	_ widget.IDirtyDeclarer[RelayPipelineState]                  = (*RelayPipeline[live.AnonymousIdentity])(nil)
)

// Register declares this instance's definition and assigned region.
//
// Events are the names a browser may send; Internal are the names only a
// declared stream delivers, which the host routes without registering.
func (instance *RelayPipeline[I]) Register() widget.Registration {
	return widget.Registration{
		Name:     RelayPipelineName,
		Region:   instance.region,
		Internal: []string{RelayPipelineEventAdvance},
		Streams: []widget.StreamDeclaration{
			{Name: "pipelineWatch", Source: "widget.relay.watch", Delivers: RelayPipelineEventAdvance},
		},
		Payloads: []widget.EventPayload{
			{Event: RelayPipelineEventAdvance, Fields: []string{
				RelayPipelineEventAdvanceFieldCursor,
				RelayPipelineEventAdvanceFieldIngressUp,
				RelayPipelineEventAdvanceFieldRelayUp,
				RelayPipelineEventAdvanceFieldSinkUp,
				RelayPipelineEventAdvanceFieldBacklog,
			}},
		},
	}
}

// Mount opens one session's copy of the widget. It schedules no effect: the
// streams this widget declared are the host's to open, because a widget document
// names no host, no address and no credential.
func (instance *RelayPipeline[I]) Mount(
	ctx context.Context, session live.Session[I],
) (RelayPipelineState, []live.Effect[I], error) {
	return RelayPipelineState{}, nil, nil
}

// Reduce is the pure transition from one state to the next. It performs no I/O,
// reads no clock and mutates nothing it was given.
func (instance *RelayPipeline[I]) Reduce(
	state RelayPipelineState, event live.Event,
) (RelayPipelineState, []live.Effect[I]) {
	current := state
	switch event.Name {
	case RelayPipelineEventAdvance:
		if raw, present := event.Fields.Lookup(RelayPipelineEventAdvanceFieldCursor); present {
			current.Cursor = widget.ParseCounter(raw, current.Cursor)
		}
		if raw, present := event.Fields.Lookup(RelayPipelineEventAdvanceFieldIngressUp); present {
			current.IngressUp = widget.ParseFlag(raw, current.IngressUp)
		}
		if raw, present := event.Fields.Lookup(RelayPipelineEventAdvanceFieldRelayUp); present {
			current.RelayUp = widget.ParseFlag(raw, current.RelayUp)
		}
		if raw, present := event.Fields.Lookup(RelayPipelineEventAdvanceFieldSinkUp); present {
			current.SinkUp = widget.ParseFlag(raw, current.SinkUp)
		}
		if raw, present := event.Fields.Lookup(RelayPipelineEventAdvanceFieldBacklog); present {
			current.Backlog = widget.ParseCount(raw, current.Backlog)
		}
	case live.SlowClientEvent:
		current.Slow = true
	case live.ClientRecoveredEvent:
		current.Slow = false
	}
	return current, nil
}

// Render draws the widget's live region. It is a pure function of state:
// equal state renders byte-identical markup.
func (instance *RelayPipeline[I]) Render(state RelayPipelineState) templ.Component {
	return RelayPipelineViewAt(state, instance.region)
}

// Dirty reports whether a transition may have changed this widget's markup: the
// state fields its bindings, its predicates and its tick read, and no others.
func (instance *RelayPipeline[I]) Dirty(previous RelayPipelineState, next RelayPipelineState) bool {
	return previous.Cursor != next.Cursor ||
		previous.IngressUp != next.IngressUp ||
		previous.RelayUp != next.RelayUp ||
		previous.SinkUp != next.SinkUp ||
		previous.Backlog != next.Backlog ||
		previous.Slow != next.Slow
}

// Unmount releases what the session held. This widget holds nothing.
func (instance *RelayPipeline[I]) Unmount(ctx context.Context, session live.Session[I], state RelayPipelineState) {
}

// Snapshot projects state into ordered name/value pairs, in state-field
// declaration order.
func (instance *RelayPipeline[I]) Snapshot(state RelayPipelineState) widget.Snapshot {
	return widget.Snapshot{
		Widget: RelayPipelineName,
		Fields: []widget.SnapshotField{
			{Name: "cursor", Value: strconv.FormatUint(state.Cursor, 10)},
			{Name: "ingressUp", Value: strconv.FormatBool(state.IngressUp)},
			{Name: "relayUp", Value: strconv.FormatBool(state.RelayUp)},
			{Name: "sinkUp", Value: strconv.FormatBool(state.SinkUp)},
			{Name: "backlog", Value: strconv.FormatInt(state.Backlog, 10)},
			{Name: "slow", Value: strconv.FormatBool(state.Slow)},
		},
	}
}

// Flowing is the "flowing" predicate.
func (state RelayPipelineState) Flowing() bool {
	return state.IngressUp && state.RelayUp && state.SinkUp && !state.Slow
}

// BackedUp is the "backedUp" predicate.
func (state RelayPipelineState) BackedUp() bool {
	return state.Backlog >= 1
}

// IngressCaptionText is the "ingressCaptionText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state RelayPipelineState) IngressCaptionText() string {
	if state.IngressUp {
		return "accepting"
	}
	return "closed"
}

// RelayCaptionText is the "relayCaptionText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state RelayPipelineState) RelayCaptionText() string {
	if state.RelayUp {
		return "relaying"
	}
	return "stalled"
}

// SinkCaptionText is the "sinkCaptionText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state RelayPipelineState) SinkCaptionText() string {
	if state.SinkUp {
		return "committing"
	}
	return "closed"
}

// PipelineDescriptionText is the "pipelineDescriptionText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state RelayPipelineState) PipelineDescriptionText() string {
	if state.Flowing() {
		return "Three stages; records move from node-a through node-b to node-c."
	}
	if !state.IngressUp {
		return "Three stages; the first stage is not accepting records."
	}
	return "Three stages; records are not moving end to end."
}

// BacklogStatText is the "backlogStatText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state RelayPipelineState) BacklogStatText() string {
	if state.BackedUp() {
		return strconv.FormatInt(state.Backlog, 10) + " records waiting"
	}
	return "no backlog"
}

// TitleLabel is the "titleLabel" label.
func (state RelayPipelineState) TitleLabel() string {
	return "Relay pipeline"
}

// SourceLabel is the "sourceLabel" label.
func (state RelayPipelineState) SourceLabel() string {
	return "Read-only pipeline stream"
}

// SceneDescriptionLabel is the "sceneDescriptionLabel" label.
func (state RelayPipelineState) SceneDescriptionLabel() string {
	return state.PipelineDescriptionText()
}

// IngressLabel is the "ingressLabel" label.
func (state RelayPipelineState) IngressLabel() string {
	return "node-a"
}

// IngressCaptionLabel is the "ingressCaptionLabel" label.
func (state RelayPipelineState) IngressCaptionLabel() string {
	return state.IngressCaptionText()
}

// RelayLabel is the "relayLabel" label.
func (state RelayPipelineState) RelayLabel() string {
	return "node-b"
}

// RelayCaptionLabel is the "relayCaptionLabel" label.
func (state RelayPipelineState) RelayCaptionLabel() string {
	return state.RelayCaptionText()
}

// SinkLabel is the "sinkLabel" label.
func (state RelayPipelineState) SinkLabel() string {
	return "node-c"
}

// SinkCaptionLabel is the "sinkCaptionLabel" label.
func (state RelayPipelineState) SinkCaptionLabel() string {
	return state.SinkCaptionText()
}

// RecordLegendLabel is the "recordLegendLabel" label.
func (state RelayPipelineState) RecordLegendLabel() string {
	return "record"
}

// CursorStatLabel is the "cursorStatLabel" label.
func (state RelayPipelineState) CursorStatLabel() string {
	return "cursor " + strconv.FormatUint(state.Cursor, 10)
}

// BacklogStatLabel is the "backlogStatLabel" label.
func (state RelayPipelineState) BacklogStatLabel() string {
	return state.BacklogStatText()
}

// MotionActive is this widget's compiled motion gate: everything its motion
// block requires, and none of what it forbids. The host's own connection status
// is the gate's other half and is applied by the stylesheet, so an animation
// cannot run against a dead connection whatever this returns.
func (state RelayPipelineState) MotionActive() bool {
	return state.Flowing()
}

// MotionActiveText renders the gate into the attribute the stylesheet selects on.
func (state RelayPipelineState) MotionActiveText() string {
	return strconv.FormatBool(state.MotionActive())
}

// MotionTickID is the scene's identity for one tick.
//
// Every animation is finite and none repeats, so what starts one again is a new
// element: the scene carries this as its id, the tick advances, and the picture
// moves exactly as often as the data does.
func (state RelayPipelineState) MotionTickID() string {
	return state.MotionTickIDAt(RelayPipelineRegion)
}

// MotionTickIDAt namespaces the scene's tick identity under its live instance.
func (state RelayPipelineState) MotionTickIDAt(region string) string {
	return region + "-tick-" + strconv.FormatUint(state.Cursor, 10)
}
