package clientcodec

import (
	"fmt"
	"strconv"
	"strings"
)

// EmitCodec renders client/codec.gen.js.
//
// The file is three parts: a generated schema table, a generated enum block,
// and a fixed encoder/decoder pair that interprets the table. Only the first
// two vary with the schema, which is the point — the wire knowledge is data
// read out of the descriptors, and the code that consumes it never has to be
// re-reviewed when a field is added.
func EmitCodec(s *Schema) []byte {
	var b strings.Builder

	b.WriteString(codecHeader)

	b.WriteString("var S = [\n")
	for _, m := range s.Messages {
		b.WriteString("  " + quote(tableLine(m)) + ",\n")
	}
	b.WriteString("];\n\n")

	b.WriteString(codecBody)

	for _, e := range s.Enums {
		b.WriteString("\nexport var " + e.Name + " = {")
		for i, v := range e.Values {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(v.Name + ": " + strconv.Itoa(int(v.Number)))
		}
		b.WriteString("};\n")
	}

	return []byte(b.String())
}

// tableLine renders one message as NAME=num,kind,name[,arg];...
func tableLine(m Message) string {
	var parts []string
	for _, f := range m.Fields {
		p := strconv.Itoa(f.Number) + "," + f.Kind + "," + f.Name
		if f.Arg != "" {
			p += "," + f.Arg
		}
		parts = append(parts, p)
	}
	return m.Name + "=" + strings.Join(parts, ";")
}

func quote(s string) string { return `"` + s + `"` }

const codecHeader = `// Code generated by internal/cmd/gen-clientcodec. DO NOT EDIT.
//
// The gotth-live wire codec for the browser. It encodes and decodes exactly
// one message — gotthlive.v1.Frame — and it is generated from the same
// FileDescriptorSet that drives the Go refinement generator, so the two sides
// cannot disagree about a field number or a wire type (docs/protocol.md
// §10.2). There is no general protobuf runtime here and there will not be
// one: a general runtime would consume most of the 12,288-byte client budget
// on its own (PRD NFR-2).
//
// Unknown tags are skipped by wire type and never throw, so a newer server
// cannot break an older client (docs/protocol.md §8.4, FR-10).
//
// Predicate enforcement is directional and deliberate. The decoder enforces
// length bounds, because it has already read the length prefix and the check
// costs two comparisons. It enforces neither numeric ranges nor regular
// expressions: an RE2 engine is not in the budget, and the attacker is on the
// other side of this connection, where enforcement is total. The full
// asymmetry is listed field by field in predicates.manifest.txt.
//
// Table format, one entry per message:
//
//	NAME=number,kind,name[,arg];number,kind,name[,arg];...
//
//	v  varint scalar or enum      b  bool
//	s  string                     y  bytes
//	m  singular message           r  repeated message
//	p  repeated packed varint
//
// arg is "min:max" for s and y when a length predicate bounds the field, and
// the message name for m and r.

`

// codecBody is the fixed half: one generic encoder, one generic decoder, and
// the varint primitives. Numbers are read and written as JavaScript numbers,
// which are exact to 2^53 — every uint64 in this protocol is a session-scoped
// counter or a 64-bit identifier minted by the server as a counter, so the
// range is not reachable, and carrying BigInt would cost bytes to buy nothing.
const codecBody = `var T = {};
S.forEach(function (l) {
  var i = l.indexOf("=");
  T[l.slice(0, i)] = l.slice(i + 1).split(";").map(function (f) { return f.split(","); });
});

var TE = new TextEncoder(), TD = new TextDecoder(), B, P;

function rv() {
  var r = 0, s = 1, c;
  do { c = B[P++]; r += (c & 127) * s; s *= 128; } while (c & 128);
  return r;
}

// sk skips one field of an unknown tag, by wire type. FR-10 lives here.
//
// The length is read into a local first. "P += rv()" would evaluate P before
// rv() advances it and skip one byte too few, which is a bug that only shows
// up on a frame from a newer server — exactly the case with no other test.
function sk(w) {
  var l;
  if (w === 0) rv();
  else if (w === 2) { l = rv(); P += l; }
  else if (w === 5) P += 4;
  else if (w === 1) P += 8;
  else throw Error("wire type " + w);
}

// bd is the only predicate the client enforces: a length bound, on decode.
function bd(f, n) {
  var a = f[3];
  if (a) {
    a = a.split(":");
    if (n < +a[0] || n > +a[1]) throw Error(f[2] + ": length " + n);
  }
}

function rd(e, m) {
  var o = {}, fs = T[m], t, n, w, f, l, i, k, q;
  while (P < e) {
    t = rv(); n = Math.floor(t / 8); w = t % 8; f = null;
    for (i = 0; i < fs.length; i++) if (+fs[i][0] === n) { f = fs[i]; break; }
    if (!f) { sk(w); continue; }
    k = f[1];
    if (k === "v") o[f[2]] = rv();
    else if (k === "b") o[f[2]] = rv() !== 0;
    else if (k === "p") {
      q = o[f[2]] || (o[f[2]] = []);
      // A packed repeated field may also arrive unpacked, one tag per value,
      // from an encoder that chose to. Both are legal; both are accepted.
      if (w === 0) q.push(rv());
      else { l = rv(); l += P; while (P < l) q.push(rv()); }
    } else {
      l = rv();
      if (k === "s") { bd(f, l); o[f[2]] = TD.decode(B.subarray(P, P + l)); P += l; }
      else if (k === "y") { bd(f, l); o[f[2]] = B.slice(P, P + l); P += l; }
      else if (k === "m") o[f[2]] = rd(P + l, f[3]);
      else (o[f[2]] || (o[f[2]] = [])).push(rd(P + l, f[3]));
    }
  }
  P = e;
  return o;
}

function wv(a, n) {
  while (n > 127) { a.push((n % 128) | 128); n = Math.floor(n / 128); }
  a.push(n);
}

function wb(a, b) { wv(a, b.length); for (var i = 0; i < b.length; i++) a.push(b[i]); }

function wr(m, o) {
  var a = [], fs = T[m], i, j, f, n, k, v, q;
  for (i = 0; i < fs.length; i++) {
    f = fs[i]; n = +f[0] * 8; k = f[1]; v = o[f[2]];
    if (v === undefined || v === null) continue;
    if (k === "v") { if (v) { wv(a, n); wv(a, v); } }
    else if (k === "b") { if (v) { wv(a, n); a.push(1); } }
    else if (k === "s") { v = TE.encode(v); if (v.length) { wv(a, n + 2); wb(a, v); } }
    else if (k === "y") { if (v.length) { wv(a, n + 2); wb(a, v); } }
    else if (k === "m") { wv(a, n + 2); wb(a, wr(f[3], v)); }
    else if (k === "r") { for (j = 0; j < v.length; j++) { wv(a, n + 2); wb(a, wr(f[3], v[j])); } }
    else if (v.length) { q = []; for (j = 0; j < v.length; j++) wv(q, v[j]); wv(a, n + 2); wb(a, q); }
  }
  return a;
}

export function decodeFrame(u8) { B = u8; P = 0; return rd(u8.length, "Frame"); }

export function encodeFrame(o) { return new Uint8Array(wr("Frame", o)); }
`

// EmitManifest renders client/predicates.manifest.txt.
//
// docs/protocol.md §10.3 requires this file and requires CI to fail when it
// drifts from the descriptors. Its job is to make the enforcement asymmetry a
// generated artifact a reviewer can read, rather than a paragraph somebody has
// to remember.
func EmitManifest(s *Schema) []byte {
	var b strings.Builder
	b.WriteString(manifestHeader)

	const (
		wField = 38
		wExpr  = 46
		wClass = 9
	)
	b.WriteString(pad("FIELD", wField) + pad("PREDICATE TERM", wExpr) + pad("CLASS", wClass) + "CLIENT\n")
	b.WriteString(strings.Repeat("-", wField+wExpr+wClass+len("CLIENT")) + "\n")

	var enforced, total int
	for _, p := range s.Predicates {
		name := p.Message + "." + p.Field
		for i, c := range p.Conjuncts {
			total++
			verdict := "no"
			if c.Enforced {
				enforced++
				verdict = "yes (decode)"
			}
			label := name
			if i > 0 {
				label = ""
			}
			b.WriteString(pad(label, wField) + pad(c.Text, wExpr) + pad(c.Class, wClass) + verdict + "\n")
		}
	}

	b.WriteString(fmt.Sprintf(
		"\n%d predicate terms over %d fields; %d enforced by the client decoder, %d not.\n",
		total, len(s.Predicates), enforced, total-enforced))
	b.WriteString(manifestFooter)
	return []byte(b.String())
}

func pad(s string, n int) string {
	if len(s)+1 > n {
		return s + " "
	}
	return s + strings.Repeat(" ", n-len(s))
}

const manifestHeader = `gotth-live client predicate manifest
====================================

Generated by internal/cmd/gen-clientcodec from proto/gotthlive/v1/frame.proto.
DO NOT EDIT. Regenerate with gen.sh; CI fails if this file drifts from the
descriptors (docs/protocol.md §10.2, §10.3).

Every refinement predicate in the schema appears below, split into its
&&-separated terms, with the verdict on whether the generated client codec
enforces it. The server enforces all of them, in both directions: inbound
through generated Validate* boundaries, outbound through ValidateOutbound
(docs/protocol.md §5.3).

Why the asymmetry, stated once here so no reader has to infer it:

  length    ENFORCED on decode. The decoder has already read the length
            prefix, so the bound is two comparisons at effectively zero
            marginal size.
  numeric   NOT enforced. A predicate evaluator is not in the 12,288-byte
            budget (PRD NFR-2), and these frames come from our own server,
            which constructed them from values that already passed the
            refinement constructors.
  matches   NOT enforced. An RE2-compatible engine is estimated at
            600-1,200 B gzip, which is budget being spent on morph
            correctness instead. Full client-side predicate codegen is
            PRD BL-26; this generator is where it plugs in.

The claim this file supports is therefore precise: every byte the SERVER
accepts crosses a generated refinement boundary before any application code
sees it. It is NOT the claim that the protocol is typed end to end in both
runtimes, and docs must not say so (docs/protocol.md §10.3).

`

const manifestFooter = `
Consequence for the wire audit (docs/instrumentation.md §5.2): decoding a
capture with this codec is independent of the server's encoder AS TO FRAMING
- field numbers, wire types, message structure - and only partially as to
field validity. A numeric-range or regular-expression violation in an
outbound frame would pass this decode. ValidateOutbound is what covers that
gap on the server.
`
