package clientcodec

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	// Linked so that extension 51234 is in the global registry when the
	// descriptor set is unmarshalled. Without it the refinement options
	// survive only as unknown bytes and every predicate silently disappears
	// from the manifest — which is the one failure this file must not have.
	liquidv1 "github.com/candacelabs/csf/pkg/liquidproto/v1"
)

// protoFile is the schema the client speaks. It is spelled out rather than
// discovered so that a descriptor set containing something else fails here
// instead of generating a codec for the wrong protocol.
const protoFile = "gotthlive/v1/frame.proto"

// Schema is the whole input to code generation, in the order it was declared.
// Order is the determinism guarantee: nothing below is sorted, keyed by map,
// or otherwise given a chance to vary between runs.
type Schema struct {
	// Messages are the wire messages, in declaration order.
	Messages []Message

	// Enums are the enumerations the client reads or writes, in declaration
	// order and without their zero members.
	Enums []Enum

	// Predicates are the refinement expressions, one per refined field, in the
	// order the fields were declared. They drive the manifest rather than the
	// codec: most of them are not enforced client-side, and the manifest is
	// where that is said out loud.
	Predicates []Predicate
}

// Message is one wire message and its fields.
type Message struct {
	// Name is the message's proto name, unqualified, and the identifier the
	// emitted codec's table is keyed by.
	Name string

	// Fields are its fields in declaration order, not field-number order: the
	// emitted table's order is part of the generated bytes.
	Fields []Field
}

// Field is one field, reduced to what a codec needs: where it sits, how it is
// framed, what to call it, and — for length-delimited scalars — the bound the
// decoder enforces.
type Field struct {
	// Number is the proto field number, which is what actually appears on the
	// wire and therefore what the decoder dispatches on.
	Number int
	// Kind is the single-letter wire kind the emitted table uses:
	//
	//	v  varint scalar or enum      b  bool
	//	s  string                     y  bytes
	//	m  singular message           r  repeated message
	//	p  repeated packed varint
	Kind string

	// Name is the field's proto name. The emitted JavaScript uses it verbatim,
	// so the client's object keys are the schema's names rather than a
	// camel-cased translation of them.
	Name string
	// Arg is "min:max" for s and y when a length predicate bounds them, the
	// message name for m and r, and empty otherwise.
	Arg string
}

// Enum is an enumeration the client reads or writes. The zero member is
// dropped: docs/protocol.md §3.5 says it is never valid on the wire, so
// emitting it would only invite somebody to send it.
type Enum struct {
	// Name is the enum's proto name, unqualified.
	Name string

	// Values are its non-zero members in declaration order.
	Values []EnumValue
}

// EnumValue is one non-zero member.
type EnumValue struct {
	// Name is the member's proto name, emitted verbatim.
	Name string

	// Number is the value on the wire.
	Number int32
}

// Predicate is one field's refinement expression, split into the conjuncts the
// manifest reports individually. Splitting matters: a field can carry a length
// bound the client enforces and a regular expression it does not, and a
// manifest that reported one verdict per field could not say so.
type Predicate struct {
	// Message is the unqualified name of the message the field belongs to.
	Message string

	// Field is the field's proto name. The pair identifies the row in the
	// manifest.
	Field string

	// Expr is the predicate source text from the .proto option, verbatim. It
	// is reproduced rather than rewritten so the manifest quotes what a
	// reviewer will find in the schema.
	Expr string

	// Conjuncts is Expr split on `&&`, because enforcement is decided term by
	// term: a field can carry a length bound the client checks and a regular
	// expression it does not.
	Conjuncts []Conjunct
}

// Conjunct is one `&&`-separated term of a predicate.
type Conjunct struct {
	// Text is the term's source, verbatim.
	Text string
	// Class is length, numeric or matches — the three rows of
	// docs/protocol.md §10.3's table.
	Class string
	// Enforced records whether the generated client decoder checks it. Only
	// length conjuncts on string and bytes fields are.
	Enforced bool
}

const (
	classLength  = "length"
	classNumeric = "numeric"
	classMatches = "matches"
)

var (
	reLen     = regexp.MustCompile(`^len\(this\)\s*(==|>=|<=|>|<)\s*(\d+)$`)
	reNumeric = regexp.MustCompile(`^this\s*(==|!=|>=|<=|>|<)\s*(\d+)$`)
	reMatches = regexp.MustCompile("^matches\\(this,\\s*`.*`\\)$")
)

// Load reads a FileDescriptorSet — the same one that drives
// protoc-gen-liquidproto — and reduces it to a Schema.
func Load(descriptorSetPath string) (*Schema, error) {
	raw, err := os.ReadFile(descriptorSetPath)
	if err != nil {
		return nil, err
	}

	var fdset descriptorpb.FileDescriptorSet
	if err := proto.Unmarshal(raw, &fdset); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", descriptorSetPath, err)
	}

	files, err := protodesc.NewFiles(&fdset)
	if err != nil {
		return nil, fmt.Errorf("resolving %s: %w", descriptorSetPath, err)
	}

	fd, err := files.FindFileByPath(protoFile)
	if err != nil {
		return nil, fmt.Errorf("%s not in the descriptor set (generate it with "+
			"protoc --descriptor_set_out --include_imports): %w", protoFile, err)
	}

	s := &Schema{}
	if err := s.loadMessages(fd.Messages()); err != nil {
		return nil, err
	}
	s.loadEnums(fd.Enums())
	return s, nil
}

func (s *Schema) loadMessages(mds protoreflect.MessageDescriptors) error {
	for i := 0; i < mds.Len(); i++ {
		md := mds.Get(i)
		m := Message{Name: string(md.Name())}

		fds := md.Fields()
		for j := 0; j < fds.Len(); j++ {
			fd := fds.Get(j)

			pred, err := predicateOf(md, fd)
			if err != nil {
				return err
			}
			if pred != nil {
				s.Predicates = append(s.Predicates, *pred)
			}

			f, err := fieldOf(md, fd, pred)
			if err != nil {
				return err
			}
			m.Fields = append(m.Fields, f)
		}

		s.Messages = append(s.Messages, m)
	}
	return nil
}

func (s *Schema) loadEnums(eds protoreflect.EnumDescriptors) {
	for i := 0; i < eds.Len(); i++ {
		ed := eds.Get(i)
		e := Enum{Name: string(ed.Name())}
		vs := ed.Values()
		for j := 0; j < vs.Len(); j++ {
			v := vs.Get(j)
			if v.Number() == 0 {
				continue // never valid on the wire (docs/protocol.md §3.5)
			}
			e.Values = append(e.Values, EnumValue{
				Name:   string(v.Name()),
				Number: int32(v.Number()),
			})
		}
		s.Enums = append(s.Enums, e)
	}
}

// fieldOf reduces one descriptor to a table row.
//
// Every kind the schema does not use is a hard error rather than a default
// case. A fixed64, a float, a map or a repeated string added later would
// otherwise be encoded by whatever branch happened to catch it, and the first
// symptom would be a corrupt frame in a browser. Failing here costs whoever
// adds the field ten minutes and costs nobody a debugging session.
func fieldOf(md protoreflect.MessageDescriptor, fd protoreflect.FieldDescriptor, pred *Predicate) (Field, error) {
	f := Field{Number: int(fd.Number()), Name: string(fd.Name())}
	where := fmt.Sprintf("%s.%s", md.Name(), fd.Name())

	if fd.IsMap() {
		return f, fmt.Errorf("%s: map fields are not supported by the client codec "+
			"(and docs/protocol.md §2 forbids them in this schema)", where)
	}

	switch fd.Kind() {
	case protoreflect.MessageKind:
		f.Arg = string(fd.Message().Name())
		if fd.IsList() {
			f.Kind = "r"
		} else {
			f.Kind = "m"
		}
		return f, nil

	case protoreflect.BoolKind:
		if fd.IsList() {
			return f, fmt.Errorf("%s: repeated bool is not supported", where)
		}
		f.Kind = "b"
		return f, nil

	case protoreflect.StringKind, protoreflect.BytesKind:
		if fd.IsList() {
			return f, fmt.Errorf("%s: repeated string/bytes is not supported", where)
		}
		if fd.Kind() == protoreflect.StringKind {
			f.Kind = "s"
		} else {
			f.Kind = "y"
		}
		f.Arg = lengthBound(pred)
		return f, nil

	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.EnumKind:
		if fd.IsList() {
			f.Kind = "p"
		} else {
			f.Kind = "v"
		}
		return f, nil
	}

	return f, fmt.Errorf("%s: wire kind %s is not supported by the client codec; "+
		"extend internal/clientcodec before adding it to the schema", where, fd.Kind())
}

// lengthBound turns a field's length conjuncts into the "min:max" the decoder
// checks. A field with no length predicate gets no bound and no check.
func lengthBound(pred *Predicate) string {
	if pred == nil {
		return ""
	}

	min, max := 0, -1
	for _, c := range pred.Conjuncts {
		if c.Class != classLength {
			continue
		}
		op, n := reLen.FindStringSubmatch(c.Text)[1], mustAtoi(reLen.FindStringSubmatch(c.Text)[2])
		switch op {
		case "==":
			min, max = n, n
		case ">":
			min = n + 1
		case ">=":
			min = n
		case "<":
			max = n - 1
		case "<=":
			max = n
		}
	}

	if max < 0 {
		return ""
	}
	return strconv.Itoa(min) + ":" + strconv.Itoa(max)
}

// predicateOf reads the (candace.liquid.v1.field) option and splits it into
// conjuncts.
//
// An unrecognised conjunct is a hard error, not an "unknown" row. The manifest
// claims to list every predicate and say who enforces it; a term the generator
// could not classify would make that claim false while looking like it held,
// which is precisely the unwritten assumption docs/protocol.md §10.3 exists to
// prevent.
func predicateOf(md protoreflect.MessageDescriptor, fd protoreflect.FieldDescriptor) (*Predicate, error) {
	opts, ok := fd.Options().(*descriptorpb.FieldOptions)
	if !ok || opts == nil || !proto.HasExtension(opts, liquidv1.E_Field) {
		return nil, nil
	}

	ref, ok := proto.GetExtension(opts, liquidv1.E_Field).(*liquidv1.FieldRefinement)
	if !ok || ref == nil || ref.GetExpr() == "" {
		return nil, nil
	}

	p := &Predicate{
		Message: string(md.Name()),
		Field:   string(fd.Name()),
		Expr:    normalizeSpace(ref.GetExpr()),
	}

	isText := fd.Kind() == protoreflect.StringKind || fd.Kind() == protoreflect.BytesKind
	for _, term := range strings.Split(p.Expr, "&&") {
		c := Conjunct{Text: normalizeSpace(term)}
		switch {
		case reLen.MatchString(c.Text):
			c.Class = classLength
			// Enforced on decode: the decoder has already read the length
			// prefix, so the bound is two comparisons (protocol.md §10.3).
			c.Enforced = isText
		case reNumeric.MatchString(c.Text):
			c.Class = classNumeric
		case reMatches.MatchString(c.Text):
			c.Class = classMatches
		default:
			return nil, fmt.Errorf("%s.%s: cannot classify predicate term %q; "+
				"teach internal/clientcodec about it rather than letting the "+
				"manifest under-report", md.Name(), fd.Name(), c.Text)
		}
		p.Conjuncts = append(p.Conjuncts, c)
	}

	return p, nil
}

func normalizeSpace(s string) string { return strings.Join(strings.Fields(s), " ") }

func mustAtoi(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		panic(err) // unreachable: the regexp matched \d+
	}
	return n
}
