load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "render",
    srcs = [
        "collection.go",
        "doc.go",
        "registry.go",
        "renderer.go",
    ],
    importpath = "github.com/candacelabs/csf/pkg/gotth/internal/render",
    visibility = ["//pkg/gotth:__subpackages__"],
)

go_test(
    name = "render_test",
    srcs = [
        "collection_test.go",
        "render_suite_test.go",
        "renderer_test.go",
    ],
    deps = [
        ":render",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
